### ISSUE TITLE
Measure tool doesn't take into account the curvature of the earth (closer to poles the area is many times larger than expected)

### ISSUE THREAD

**Issue by wohnout** [hslayers/hslayers-ng#1]
OpenLayers 3 doesnt support geodesic measurement at this moment

Discussion: https://redmine.ccss.cz/issues/4721

**Comment by raitisbe** [comment]
fixed in https://github.com/hslayers/hslayers-ng/commit/b7e57fbd828a017e9abf3b0d1d7a53648bd7f8ae
