### ISSUE TITLE
SPOI relevant paramaters for every new SPOI

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#100]
It is probably for broader discussion, but we need discussed, relevant paramaters for every types of points.
Now if I am starting to edit new point for example from cNature like dune, I am reciving only two issue, NAme and Opening hours (probably not to much relevant).
So will be good or to have for every point full list of paramanter like Comments, url etc. Or define relevant list for every subject.
COuld be that at begining some full list of paramatr could start including comemnts, url etc

**Comment by raitisbe** [comment]
agree, fax and mobile number for bus stops is irrelevant too
