### ISSUE TITLE
SPOI Hidden list of objects

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#101]
When I am editing new point on right side of Map List of objects is hidden under Layer panel

**Comment by raitisbe** [comment]
cant imagine how it looks

**Comment by kcharvat** [comment]
See

![error editing](https://cloud.githubusercontent.com/assets/16701286/23341479/ead8e416-fc48-11e6-9dc6-dc34a1887757.png)

**Comment by raitisbe** [comment]
ah that list. Ok, will solve it somehow.
