### ISSUE TITLE
Feature styler svg images are not being loaded

### ISSUE THREAD

**Issue by DailisLangovskis** [hslayers/hslayers-ng#1010]
![icons](https://user-images.githubusercontent.com/46564459/92116566-a8ef0680-edfc-11ea-91ec-2331bd336ca6.png)

**Comment by jmacura** [comment]
This is a webpack config problem. I have seen it before. Where do you observe it? In the full example running on localhost?

**Comment by DailisLangovskis** [comment]
@jmacura Correct!

**Comment by jmacura** [comment]
The problem is a `url-loader` settings in webpack config, if I remember correctly. I gonna try it on my machine and report back.

**Comment by jmacura** [comment]
I can only replicate it in this strange way: 
![image](https://user-images.githubusercontent.com/5598693/92159677-11a2a700-ee2e-11ea-841a-3dc991a0b0f0.png)
Is it the same at your side?

**Comment by DailisLangovskis** [comment]
@jmacura Weird :D Why is only first image shown?

**Comment by jmacura** [comment]
It is the selected one. And it only appears after I select it. Yet in the box bellow, it remains hidden 🤪

**Comment by DailisLangovskis** [comment]
@jmacura Idk why, but now all the icons are shown, didn't change anything :D Yet there is another bug...
![bug2](https://user-images.githubusercontent.com/46564459/92162647-2b96b680-ee3b-11ea-97f5-c3bceeea1acd.png)
![bug1](https://user-images.githubusercontent.com/46564459/92162650-2c2f4d00-ee3b-11ea-9786-2985ef4d0ed0.png)
This happens to few of the svg images

**Comment by raitisbe** [comment]
I had missing icons in groundwater project. Was due to file-load for images instead of url-loader and probably also wrong paths for the statics files. Changing the rule to use url-loader fixed it.

**Comment by jmacura** [comment]
I see the img url as unsafe.
![image](https://user-images.githubusercontent.com/5598693/93753142-f55d8300-fbff-11ea-9e2f-b9a512c14994.png)

**Comment by raitisbe** [comment]
Now clicking produces this error
webpack-internal:///../node_modules/@angular/core/fesm5/core.js:2188 ERROR 
error: "<!DOCTYPE html>↵<html lang="en">↵<head>↵<meta charset="utf-8">↵<title>Error</title>↵</head>↵<body>↵<pre>Cannot GET /SafeValue%20must%20use%20[property]=binding:
