### ISSUE TITLE
SPOI in LArge scales SPOI are not displayed

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#102]
It is reasonable, that in small scaless SPOI are  not visible But they are also not visible, when you go to bigger detail. See image
![scale spoi](https://cloud.githubusercontent.com/assets/16701286/23342520/6b2f7356-fc5c-11e6-8080-ee5e9135ec87.png)

**Comment by kcharvat** [comment]
Tested in IE and Chrome

**Comment by raitisbe** [comment]
Yes, thats on purpose. It should tell it also in the exclamation mark in layer manager
