### ISSUE TITLE
Graphical buttons are working not correctly

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#106]
Buton of OSM is swithing off all POI
Wheather button is able switch on open weather but not switch off.
Please check and think about some logic

**Comment by raitisbe** [comment]
Jan can you look on this, since you started fixing theme switcher?

**Comment by ChcJohnie** [comment]
Ok will look on it.
How should it work?
My suggestion: Button switch on/off all layers from its group but does nothing with other groups. Also question is what to do when there are some layers on and some off from one group. Should they all be switched on or should they be switched on/off based on last setting of groups button?

**Comment by kcharvat** [comment]
OK

**Comment by ChcJohnie** [comment]
Check changed behaviour if its ok

**Comment by kcharvat** [comment]
Seems that now is something realy wrong
