### ISSUE TITLE
TranslateSevice.instant works only with default language

### ISSUE THREAD

**Issue by FilipLeitner** [hslayers/hslayers-ng#1064]
![image](https://user-images.githubusercontent.com/44566616/93753225-1b832300-fc00-11ea-8982-35657bc058e8.png)

**Comment by FilipLeitner** [comment]
Just not properly translated
this.TranslateService.instant('Confirm clear') -->  this.TranslateService.instant('COMMON.confirmDelete'),

**Comment by DailisLangovskis** [comment]
@FilipLeitner Must have missed this one, because i don't use this.TranslateService.instant. If some translations are needed inside .ts files please use HsLanguageService.getTranslation() method. I had already fixed this, yet it seems that my changes have vanished

**Comment by FilipLeitner** [comment]
Ok sure, no problem. Ill have some other changes coming today so Ill just fix these.

**Comment by DailisLangovskis** [comment]
@FilipLeitner What, there is a set of commits missing from query component. I had all of  that translated, just need to find it

**Comment by DailisLangovskis** [comment]
I have all of the translations inside my getttext removal branch, You don't need to go over them, I will PR this
