### ISSUE TITLE
Datasources keep loading until map is moved

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#1089]
Micka and Layman datasources keeps "loading" in never-ending cycle, while actually not loading anything (no request is sent).

The request to the endpoints is only send after map moves.

![image](https://user-images.githubusercontent.com/5598693/94815170-88659c80-03fa-11eb-8994-ad8d1f8c8cf4.png)

**Comment by fzadrazil** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release 2.4.0](https://trello.com/c/ZPfH6ews/106-release-240)
