### ISSUE TITLE
Select objects from Virtuoso

### ISSUE THREAD

**Issue by wohnout** [hslayers/hslayers-ng#11]
Could be, that my idea is crazy, but what will be nice to be able similary like in catalogue select in Virtuso some type of objects. some class and this add to the composition. If we will store a lot of diferent types of objects in Virtuoso, this will be nice for building customised maps. And then use this objects like other type of layers. Do you think, that such apporach could be possible?

Original at https://redmine.ccss.cz/issues/5095

**Comment by kcharvat** [comment]
Such function could us help realy bring LOD word to our applications. Be able select object on typology, area etc and add them to compossition. We will need catalogue client to define paramaters and then add objects. This will help to build local apllications in different domains. Or other possibility could be store this data as kml or JSON add add them
