### ISSUE TITLE
SPOI not working in Chrome

### ISSUE THREAD

**Issue by bvj** [hslayers/hslayers-ng#110]
http://ng.hslayers.org/examples/geosparql/ 
is not working in Chrome - in FF, MSIE on W7 is working, on Safari on OS X working too
error messages form Chrome:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:140 Uncaught Error: Script error for "danidemo"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:165)
    at HTMLScriptElement.onScriptError (require.js:1732)
dmuploader.js Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:140 Uncaught Error: Script error for "dmuploader"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:165)
    at HTMLScriptElement.onScriptError (require.js:1732)
```

**Comment by raitisbe** [comment]
Looks like danidemo.js and dmuploader.js was not loaded. They are on different server, but for me are loading fine. Can you look in network inspector what could be blocking them for you?

**Comment by bvj** [comment]
only 404 - Not Found

**Comment by bvj** [comment]
And Junior was trying it with different result:
![image](https://cloud.githubusercontent.com/assets/8994271/23743382/ba6d2dee-04b0-11e7-988b-62fc9ef72ae6.png)

**Comment by bvj** [comment]
wrong click, sorry

**Comment by ChcJohnie** [comment]
Working fine for me, once I got same screen as that from Junior but couldnt reproduce it..

**Comment by bvj** [comment]
after clearing cache now started working for me

**Comment by raitisbe** [comment]
I think i know why its like this. Everything is not cached except hslayers.js file and it contained pointers to new modules which were not in the cache so had problems loading them. Must also uncache hslayers.js now.

**Comment by bvj** [comment]
I thought, gitsha is here for this



Dne 12. 3. 2017 4:05 PM napsal uživatel "Raitis Berzins" <
notifications@github.com>:

**Comment by raitisbe** [comment]
yes but hslayers.js isn't loaded with requirejs but from html. See how I solved it in geosparql example.
