### ISSUE TITLE
Parse composition from URL

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#1178]
https://app.hslayers.org/ows-browser/?composition=https://hub.lesprojekt.cz/rest/pekarekro/maps/aktualni_pocet_nakazenych

shall load the composition specified in the composition parametre and add its layers to the map.
The functionality is implemented but buggy:
![image](https://user-images.githubusercontent.com/5598693/96987149-e3cf0a00-1522-11eb-9429-e892eaf9e6ad.png)

**Comment by jmacura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Load composition at startup from url param](https://trello.com/c/lFbCQZXq/123-load-composition-at-startup-from-url-param)

**Comment by raitisbe** [comment]
You are loading from the wrong file. https://hub.lesprojekt.cz/rest/pekarekro/maps/aktualni_pocet_nakazenych is the laymans composition wrapper, not the composition itself. 

It should be:
https://app.hslayers.org/ows-browser/?composition=https://hub.lesprojekt.cz/rest/pekarekro/maps/aktualni_pocet_nakazenych/file

**Comment by jmacura** [comment]
> 
> 
> You are loading from the wrong file. https://hub.lesprojekt.cz/rest/pekarekro/maps/aktualni_pocet_nakazenych is the laymans composition wrapper, not the composition itself.
> 
> It should be:
> https://app.hslayers.org/ows-browser/?composition=https://hub.lesprojekt.cz/rest/pekarekro/maps/aktualni_pocet_nakazenych/file

Well, that is awesome then 👍 
But how can one access the composition's self link?
Perhaps we can try to parse that wrapper as well? I would investigate that possibility.

**Comment by jmacura** [comment]
Done in 1.x branch, needs port to 2.x and 3.x

**Comment by jmacura** [comment]
Done in 1.x and 2.x branches, needs port to 3.x

**Comment by jmacura** [comment]
Done.
