### ISSUE TITLE
Make layer abstract translatable and with tooltip over layer name

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#1189]

**Comment by raitisbe** [comment]
![image](https://user-images.githubusercontent.com/395514/97156733-c8146f80-177f-11eb-95b4-fef0b1664c71.png)

**Comment by FilipLeitner** [comment]
Why not adding info to layer-editor?

**Comment by raitisbe** [comment]
Its there too, but we have to have also a tooltip. See https://github.com/hslayers/project-agro-climatic/issues/10

**Comment by FilipLeitner** [comment]
> Its there too, but we have to have also a tooltip. See [hslayers/project-agro-climatic#10](https://github.com/hslayers/project-agro-climatic/issues/10)

I see now, looks nice tho
