### ISSUE TITLE
By clicking on a layer feature (point) open a link directly

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#1212]
A requirement for https://hub.sieusoil.eu/home and https://hub.polirural.eu/home .

In a simple app, there is a layer with points. Currently, a pop-up displays on click
![image](https://user-images.githubusercontent.com/5598693/97873170-80f62380-1d17-11eb-8522-b5e9697143d7.png)
but the requirement is to directly open an associated link (http://www.lesprojekt.cz/ in the case of the example above).
So something like `directUrl` parametre shall be configurable at each layer. When it's defined, the other click options (like info panel and pop-up) are ignored and the URL is opened in a new tab.

Any volunteer for this feature-request?

This must go into 1.x branch and then be ported to 2.x.

**Comment by raitisbe** [comment]
I would create this a bit differently. Add onFeatureSelected attribute to layer object which would be a function which takes the feature as parameter. For this particular layer wwe would then disable or just not configure hoverPopup. In Query-vector sevice we would call the function when a feaature is selected if its configured for that layer. 
In the callback function we could do anything this way - display popups, change content outside hslayers etc.

**Comment by jmacura** [comment]
> 
> I would create this a bit differently. Add onFeatureSelected attribute to layer object which would be a function which takes the feature as parameter. For this particular layer we would then disable or just not configure hoverPopup. In Query-vector sevice we would call the function when a feature is selected if it's configured for that layer.
> In the callback function we could do anything this way - display popups, change content outside hslayers etc.

That sounds quite interesting. Definitely, it would be more versatile and generic solution.

**Comment by jmacura** [comment]
FTR: implemented on https://hub.polirural.eu/home and works great ;-)
