### ISSUE TITLE
Add support for WMTS GetFeatureInfo requests

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#1251]
Example of WMTS request
https://gis.lesprojekt.cz/geoserver/gwc/service/wmts?VERSION=1.0.0&LAYER=S-JTSK:S2_NDVI_2020&STYLE=&TILEMATRIX=S-JTSK:7&TILEMATRIXSET=EPSG:5514_OGC&SERVICE=WMTS&FORMAT=image/png8&SERVICE=WMTS&REQUEST=GetFeatureInfo&INFOFORMAT=text/html&TileCol=88&TileRow=45&I=225&J=226

**Comment by FilipLeitner** [comment]
With given WMTS works for gml, xml, text, html responses.
1x - #1292
2x - #1298
