### ISSUE TITLE
Avoid adding duplicate layers

### ISSUE THREAD

**Issue by SLeitgeb** [hslayers/hslayers-ng#126]
When adding a new layer into the map, check if there is not a similar layer already added (and prompt the user to add a duplicate).

**Comment by SLeitgeb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Checking duplicate layers](https://trello.com/c/rCx36H9L/32-checking-duplicate-layers)

**Comment by raitisbe** [comment]
Commits solving this: https://github.com/hslayers/hslayers-ng/commit/1f883b89198ac583d802865f1b911761b81206b3
https://github.com/hslayers/hslayers-ng/commit/e972b4012ffbdce5e06d077d540fe9ac578e05f1
