### ISSUE TITLE
Don't use unidecode 

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#1271]
Unidecode is too expensive imho for such a small task (80KB gziped, or ~300KB pure). It's more than our whole css code.
The functionality of unidecode should be provided serverside - Layman in our case.

**Comment by jmacura** [comment]
Using @unidecode (the same library that Layman uses internally) seemed to me as the most straightforward way of implementing (mitigating) the Layman naming principles. If Layman could provide this via its API, that would be of course much nicer.

**Comment by raitisbe** [comment]
Dropped this library in https://github.com/hslayers/hslayers-ng/commit/f4ad828fd0a84f6681c4d500756a172454cc5378 for no-angularjs branch.
Now the non-ascii letters are just removed. Maybe its something to consider also for 2.x versions.
