### ISSUE TITLE
HsDialog components do not inherit font style

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#1310]
Relevant to 2.x version.
![image](https://user-images.githubusercontent.com/5598693/100935933-117b7b80-34f1-11eb-9b46-1695b004542a.png)

**Comment by DailisLangovskis** [comment]
@jmacura Hey, I was trying to find the issue here, but to be fair have no idea what I should be looking for.

**Comment by jmacura** [comment]
@DailisLangovskis This issue is not about the actual error on the screenshot, but about its style (the error I have fixed already). We use some sans-serif font everywhere so I do not see why HsDialog istances display text with serif font (Times New Roman I guess).
Do we understand each other? Or were you asking about something else? 😀

**Comment by DailisLangovskis** [comment]
@jmacura Yeah I understood that the issue was about the font style. I just then realized I was blind! :D
