### ISSUE TITLE
Redundant FROMCRS parameter causes WMS loading to fail

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#1324]
https://github.com/hslayers/hslayers-ng/blob/2a3d1f7ccb4d264d3986e80c6d82f015b111d097/components/compositions/compositions-parser.service.ts#L160

Is there a reason to have 'EPSG:3857' hardcoded here? In case of application with different projection, WMS fails to serve GetMap requests if the service does not support 3857.

**Comment by jmacura** [comment]
@FilipLeitner https://github.com/hslayers/hslayers-ng/blame/2a3d1f7ccb4d264d3986e80c6d82f015b111d097/components/compositions/compositions-parser.service.ts#L160

**Comment by FilipLeitner** [comment]
Good point...I jsut probably wanted to copy the content of laymans respose of the composition request, thats why I included that. Was trying to find the purpose of the param but I wasnt successful. Feel like it might be just deleted. 
Although I am not sure how s that supposed to influence the getMap request if it just doesnt mean anything..maybe I am just missing something @raitisbe ?

**Comment by raitisbe** [comment]
We used to have server side proxy components which was also reprojecting
wms tiles. Prox4ows it was called and it used this special parameter. I
dont think its needed anymore.

**Comment by fzadrazil** [comment]
The parameter is used on more places in the code. I was suprised it influenced the particular WMS as it is not standard WMS parameter. But it did...the service simple doesn't return map when FROMCRS is there. So if we can remove it completely, it will be for the best.

**Comment by raitisbe** [comment]
Agree
