### ISSUE TITLE
Keep layer title black when turned off

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#1326]
Layer title in layer manager should be in black color even when the layer is turned off. Grey out the title only for the case when the layer is outside the visible scale range.

**Comment by fzadrazil** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Layer title in black color when in the visible scale range](https://trello.com/c/NLiJiE3B/136-layer-title-in-black-color-when-in-the-visible-scale-range)

**Comment by FilipLeitner** [comment]
Actually I kinda link it the way it is now: but ok if thats the way we want it :)
