### ISSUE TITLE
Hide logo in sidebar when screen size is smaller

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#1327]
Logo shall be automagically replaced by plain text when the height of its container element is smaller then the calculated height of the image. E.g. when there are many panel buttons, on smaller screens or with reduce-sized browser window. So the sidebar won't get scrollable only because of the logo.

![image](https://user-images.githubusercontent.com/5598693/101336332-a4fad680-387a-11eb-8671-859b002a37d7.png)

spin-off of #1318

**Comment by DailisLangovskis** [comment]
Hiding logo in not needed anymore, because of the new way sidebar is rescaling and adapting to screen size!
