### ISSUE TITLE
Info pop-up for WMS layer appears with an error where no data exist

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#1345]
![image](https://user-images.githubusercontent.com/5598693/101794870-9aa13c80-3b07-11eb-9b9a-71a46819c1be.png)

Reported on Redmine by @kcharvat .

**Comment by raitisbe** [comment]
What layer is it and how it was added to the map?

**Comment by raitisbe** [comment]
The purplish, blueish overlay layer I mean

**Comment by jmacura** [comment]
> 
> 
> What layer is it and how was it added to the map?

That one I do not know. It was actually two WMS layers, named "Mokřady Ramsarské úmluvy" and "Evropsky významná lokalita (EVL)". I believe they were added from Micka, either separately or as a part of some composition.
But try another one. E.g. this composition https://hub.plan4all.eu/cat/record/basic/5a0afe1d-97c8-48f6-b2fc-1866c0a80138 from Micka. When added to map and you click to the map window, you can see this
![obrazek](https://user-images.githubusercontent.com/5598693/102619735-343aa080-413d-11eb-82bc-84bd7bb59c9f.png)
not only it returns error into the pop-up it also magically en-smalls the font-size of all the text in HSLayers :-/

**Comment by DailisLangovskis** [comment]
> Mokřady Ramsarské úmluvy

I found this only to be WFS layer from SpuerCAT, so I am confused.
