### ISSUE TITLE
Implement ES6/ES7 transpiler to development workflow

### ISSUE THREAD

**Issue by SLeitgeb** [hslayers/hslayers-ng#135]
Use Babel or another library for compatibility with older browsers.
* accompany this to the existing `build.sh` script together with browserify and grunt

**Comment by raitisbe** [comment]
Babel should probably be a dependency on the speciffic project, not hslayers itself.

**Comment by raitisbe** [comment]
Since we are using webpack babel is included by default into dev-dependencies.
