### ISSUE TITLE
Sharing ends with Status Manager error

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#1361]
Trying to share a map in the testing app https://hub.lesprojekt.cz/hsl-ng/hsl-ng-2.x/apps/full, request to the Status Manager fails with blocked:mixed-content error. The configuration seems all right. It is working in the 1.x.

**Comment by fzadrazil** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release 2.5.0](https://trello.com/c/ve259N2U/132-release-250)

**Comment by fzadrazil** [comment]
The mixed-content error has been solved by changing proxy settings. But there remains another issue as there is no thumbnail in the shared article as it was in the 1.x version. Tried sharing to Facebook.

**Comment by raitisbe** [comment]
It because the wmts requests are not proxified: https://gis.lesprojekt.cz/geoserver/gwc/service/wmts?layer=S-JTSK%3AS2_NDVI_2020&style=NDVI&tilematrixset=EPSG%3A5514_OGC&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fpng8&TileMatrix=S-JTSK%3A2&TileCol=2&TileRow=1

**Comment by raitisbe** [comment]
Was it the case that 1.x version didnt have wmts layer? I cant imageni how it could have worked otherwise because canvas gets tainted by not proxified requests
