### ISSUE TITLE
Zoom controls missing 

### ISSUE THREAD

**Issue by ChcJohnie** [hslayers/hslayers-ng#137]
Zoom controls (+/-) missing for some apps from certain update 

Might be connected to commit 79c6be9ca7b1dbf545477292c5f0be3be83c03cf

**Comment by ChcJohnie** [comment]
Works ok when default controls used for map 
`me.map = new ol.Map({
         /*controls: ol.control.defaults({
                zoom: false
         }),*/
         target: 'map',
         interactions: [],
         view: cloneView(config.default_view)
});`

We should make default controls list for desktop and mobile version, most likely, and also option to override it in each project. Then correct control list can be loaded with eg. map.addControl iteration.

**Comment by ChcJohnie** [comment]
Created default controls and possible config import in 4a01fa3f6e2436aeb349916c746fd7f9e7597728

Need to check if cordova clause is correct @SLeitgeb 
Also not sure what is desired set of controls for material design, currently it doesnt fit but idk if it is problem of control set or only different design is needed.

**Comment by SLeitgeb** [comment]
I wouldn't base whether zoom controls are displayed on which app version is used (mobile / desktop). This can have some merit as well, but which controls are displayed should be mainly determined upon the design scheme of the application.

**Comment by ChcJohnie** [comment]
Continuing discussion:
So load default controls everywhere and decide by css? (for simplicity)

Possible limitation for this approach is when hslayers map should be embeded, and not full window app (I think there are more designs which wouldnt work with media queries because of this, but not sure).

As for material design, I think zoom controls (in default version) should be place next to geolocation button (under/above), agree/disagree?

**Comment by raitisbe** [comment]
Closed due to inactivity
