### ISSUE TITLE
Share map to Facebook doesn't display thumbnail

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#1379]
The thumbnail is generated just fine in the Share map panel, but is not displayed in the Post on facebook. I haven't tried another social media as I have no account for them.

**Comment by jmacura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release 2.5.0](https://trello.com/c/ve259N2U/132-release-250)

**Comment by raitisbe** [comment]
https://github.com/hslayers/hslayers-ng/commit/c1883f75834b8b058e0ae6df42be0d3efbc9d829 and https://github.com/hslayers/hslayers-ng/commit/34a6fed3cb470dc59172c97c3dcea1ceed19ac0e fixes that
