### ISSUE TITLE
External data>Shape file panel Advanced options not collapsible

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#1382]
Also specifying layer folder doesn't work
![image](https://user-images.githubusercontent.com/395514/102361829-5527b800-3fbc-11eb-961a-157ed1544726.png)

**Comment by DailisLangovskis** [comment]
@raitisbe I fixed this for External data > vectorFiles with ->  
<div class="collapse hs-ows-vector-advanced" *ngIf="advancedPanelVisible">
instead of
<div class="collapse hs-ows-shp-advanced" [ngClass]="{'show': advancedPanelVisible}">

**Comment by raitisbe** [comment]
^ This fix is for 3.x
