### ISSUE TITLE
Response from statusmanager to full app on hub.lesprojekt is exceptionally slow

### ISSUE THREAD

**Issue by FilipLeitner** [hslayers/hslayers-ng#1394]
![image](https://user-images.githubusercontent.com/44566616/102506478-6c7da880-4083-11eb-9e62-0c49b82b8a72.png)
As seen in the picture, safe request to statusmanager took 44s (times vary but it always more than 30s) to process. 
It causes the permalinks generated after share panel is opened to fiail sharing added layers (only app config layers are shared). It is beacuse permalinkRequestUrl has not been set yet so the generated url contain empty permalink param. To be able to share user created layers one needs to wait until request is finished and re-create permalinks.

After that when permalink is opened it once again take longer than expected until permalnk layers appear.  Unless I have a brakpoint set inside parsePermalinkLayers function I am not able to track stastumanager load request as its not send at all.

I can only observe this behavior  on https://hub.lesprojekt.cz/hsl-ng/hsl-ng-2.x/apps/full.

For comparison same requests made from https://hub.lesprojekt.cz/map2/
![image](https://user-images.githubusercontent.com/44566616/102508907-37bf2080-4086-11eb-97e6-ea8d3d9bb105.png)

**Comment by raitisbe** [comment]
@FilipLeitner Its because it encodes all the 5000 cluster layers features in the request. You can see it in the response for loading permalink: https://hub.lesprojekt.cz/statusmanager/?request=load&id=57055282-89a9-4de2-9e50-53136ab8be29

**Comment by raitisbe** [comment]
I noticed another thing, that more information about the features is encoded than needed. It looks like the full openlayers objects properties are stored, not just the Geojson encoded list features.
