### ISSUE TITLE
CSS import ordering

### ISSUE THREAD

**Issue by ChcJohnie** [hslayers/hslayers-ng#140]
HSLayers and dependencies are currently imported in bodies of componentes (hslayers/layout.html).
This means these css rulers take precedence over {app}.css potentialy imported for specific app. 
Only current solution (other than important everywhere), is to place all app-specific links inside body after HS div.

It is working but we should imho at least explore possibility to append all links to head by JS. (e.g. [loadCSS](https://github.com/filamentgroup/loadCSS)). Tricky part gonna be how to order them correctly head, not sure know. Also dont know what effect would be on loading times.

**Comment by raitisbe** [comment]
Its now implemented in layout.directive
