### ISSUE TITLE
Permalink saving on status manager doesn't save added layers, and path and visibility of existing ones

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#1403]
Fixed in several commits in 2.x: 64e9ac364c486f7b3512d9c813b850aacb852382 97327609ff6f97bb43195f05a4efbe54ebd93d47 29cc57515007b513b3efdc0b3a1663630b139d6f 70af352be5ad4b7020b61a39c48b5e908376a476 759df1e9c1bf3363f9f311ba7a24fad07408d7a8 fd83e582ea20f54f1c942d548cf71cd7880e3aac 55ef9312ce1772ca9e1eaa7b129e41b1c20a6f6d

And 3.x: 33944f166b1dbac8e2d2c0f12057710a548674e6
Needs port to 1.x

**Comment by raitisbe** [comment]
Closing due to innacitivity

**Comment by jmacura** [comment]
Obviously backport to 1.x no longer needed.
