### ISSUE TITLE
WMTS layer definition (className, matrix, ..) should also be saved to permalink and composition

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#1410]

**Comment by FilipLeitner** [comment]
Il be adding this in : https://github.com/hslayers/hslayers-ng/pull/1467. For 1x  done in https://github.com/hslayers/hslayers-ng/commit/e0555040ae9baac7f225239c1c1306de93955321

**Comment by FilipLeitner** [comment]
https://github.com/hslayers/hslayers-ng/blob/develop/projects/hslayers/src/components/save-map/save-map.service.ts#L394-L401
