### ISSUE TITLE
Missing ok/cancel buttons from add new draw layer dialog of draw toolbar

### ISSUE THREAD

**Issue by DailisLangovskis** [hslayers/hslayers-ng#1627]
![missing button ok](https://user-images.githubusercontent.com/46564459/109498760-951b1900-7a9c-11eb-9cae-9296b51872ca.png)
Buttons are missing after first layer is added.

**Comment by FilipLeitner** [comment]
Maybe some unexpected behaviour resulting from layman layer list not being refreshed properly. Fixed that in https://github.com/hslayers/hslayers-ng/commit/2f5a1340d98495fd8e83c2b4b443dadcb484bbc5.

**Comment by DailisLangovskis** [comment]
> Maybe some unexpected behaviour resulting from layman layer list not being refreshed properly. Fixed that in [2f5a134](https://github.com/hslayers/hslayers-ng/commit/2f5a1340d98495fd8e83c2b4b443dadcb484bbc5). .. but just guessing for now

Didn't You come across with this bug, while discovering the bug in #1626 ?
