### ISSUE TITLE
Simplify new hslayers-based apps creation

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#1637]
Setting up a new application is cumbersome, even when you can do a lot of copy&pasting.
One one to achieve this is by creating `ng add` schematics. Custom schematics is not an easy way (it's in fact rather complicated), but if implemented properly, it should be the most elegant way.
See https://medium.com/@tomastrajan/total-guide-to-custom-angular-schematics-5c50cf90cdb4

**Comment by DailisLangovskis** [comment]
@jmacura Could this now be resolved with the hslayers-template You made?

**Comment by jmacura** [comment]
@DailisLangovskis Good point. hslayers-template is another approach completely, but solves the same issue.

Superseded by [hslayers-template](https://github.com/hslayers/hslayers-template).
