### ISSUE TITLE
Logo image not available in simple map

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#1644]
Logo element src attribute should point to the assets based on the app location, but not it always looks like this instead
```<img alt="HSLayers-NG" src="/img/hslayers-ng-logo.png">```

**Comment by DailisLangovskis** [comment]
@fzadrazil This is happening because HsConfig.assetsPath most likely has not been provided.

**Comment by fzadrazil** [comment]
@DailisLangovskis Ok. Is it documented somewhere (readme, wiki)? I could not find it.

**Comment by FilipLeitner** [comment]
For apps using hslayersNgConfig possible correct setting is `assetsPath: window.HSL_PATH + 'assets',`
