### ISSUE TITLE
Search tool breaks toolbar styling

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#1651]
![image](https://user-images.githubusercontent.com/48727502/110385627-76e68780-805f-11eb-8224-ba5bb2f7b373.png)
When the list of suggestions appear, measure and reflect tools move downwards.
Another issue is that after picking one of the result, the map zooms to it but stays blured. One has to move or zoom to refresh it.

**Comment by FilipLeitner** [comment]
Basically the same on 2x  https://hub.lesprojekt.cz/cs/map2

**Comment by FilipLeitner** [comment]
Fixed the immediate problem here (3x) https://github.com/hslayers/hslayers-ng/tree/Styles, but not the root problem. Liferays bootstrap is by cascading affecting our styles and as far as Iam aware there is no way from preventing that .

**Comment by raitisbe** [comment]
Should we close this issue maybe?

**Comment by FilipLeitner** [comment]
Was opened just as a reminder.. but I guess these cannot be really forseen so Ill close
