### ISSUE TITLE
Adapt Layman endpoint to the new stucture of workspaces

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#1664]
Layman 1.11.0 introduces slightly different structure of workspaces. It is now possible to request data through all the user workspaces which the current user has a permission to see or edit.
```
<layman_client>/rest/layers
<layman_client>/rest/maps
```

Requests to a particular workspace now has a different endpoint:

Layman 1.10.1
```
<layman_client>/rest/<workspace_name>/layers
<layman_client>/rest/<workspace_name>/maps
```
Layman 1.11.0
```
<layman_client>/rest/workspaces/<workspace_name>/layers
<layman_client>/rest/workspaces/<workspace_name>/maps
```
or
```
<layman_client>/rest/<workspace_name>/layers` (still works, but for backward compatibility only).
```

**Comment by FilipLeitner** [comment]
Will do after #1777 and probably also #1776 are merged

**Comment by fzadrazil** [comment]
Just a note that requests to the "browser" user workspace should be removed at all when searching for data. Use the general requests instead
```
<layman_client>/rest/layers
<layman_client>/rest/maps
```
