### ISSUE TITLE
Reverse order of layer rendering

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#1691]
Enable to reverse the order of rendering layers by some configuration parameter. Common practice in GIS is that the order of layers in layermanager corresponds with the rendering order (the layer which is higher than others in the layer manager should be rendered above those other layers). We are currently rendering in the opposite direction.

**Comment by DailisLangovskis** [comment]
@fzadrazil There already is HsConfig for this, called reverseLayerList. When set to true, You will get the desired layer ordering, being top rendered layers will be displayed on top.
