### ISSUE TITLE
Newly added layers are unorderable

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#1707]
Noticed this on Draw layers but could be also for layers added through datasources panel. It is because both of them have zIndex of Infinity, so cant be swapped.

**Comment by raitisbe** [comment]
Fixed in hslayers-ng-11 branch. Needs downport.

**Comment by FilipLeitner** [comment]
Hmm sure this makes sense. However I dont think its right way to set zIndex automatically to max  in  cases of layers with 'base' option - WMS,WMTS, ArcGIS.  
Also to partialy adress the folder structure within the ordering I made it the way that when layer is added to certain folder z-index is set to be folder max, not 'global' 
https://github.com/hslayers/hslayers-ng/blob/develop/projects/hslayers/src/components/layermanager/layermanager.service.ts#L954
