### ISSUE TITLE
Suppress JSDoc in favor of TSDoc

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#1731]

**Comment by jmacura** [comment]
Can you be more descriptive about this?

**Comment by jmacura** [comment]
@DailisLangovskis has reported similar mismatch before. I will investigate that.

**Comment by raitisbe** [comment]
Managed to fix that, but theres still this:
![image](https://user-images.githubusercontent.com/395514/114106447-7730a780-98d7-11eb-9d45-646ab96bc89b.png)

**Comment by jmacura** [comment]
Oh, I can see now where this has came from: https://github.com/openlayers/eslint-config-openlayers/commit/6de500d1b8e2303bd14a955c989114b368494b39

I knew it was OK some time ago. Actually until I have reinstalled node_modules today.
