### ISSUE TITLE
Vector pop-up displays with transparent background

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#1736]
![image](https://user-images.githubusercontent.com/5598693/114250918-8e3acc80-999f-11eb-8800-e19cd994fe4a.png)

Interesting change. I kind of like it, but it makes the text much worse readable. If this change was intentional, I would propose to use some white-transparent (20% transparency or so) background, so the black text is still readable.

**Comment by FilipLeitner** [comment]
2dda95fb90ac7a4012549abaf6ac6cbe3b496671
