### ISSUE TITLE
Search all data types by default in Datasources

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#1746]
It is set only to Services by default now. Should be Services and Datasets.

**Comment by FilipLeitner** [comment]
Set it like that on purpose beacause 'datasets' without using 'query' param may return a lot of various datasources we are not able to process/display.

**Comment by raitisbe** [comment]
Exactly that. Maybe now we have some more metadata in the catalogue to decide what kind of data it is and if we are able to display it? It used to be quite a mess.

**Comment by fzadrazil** [comment]
There is a validation service in Micka under development which should filter out non-valid records (the "query" param Filip has mentioned]. The problem is that this validation is not ready yet. As soon as it is deployed, I'd go for querying all the data.
