### ISSUE TITLE
Use new filtering and paging params of Layman requests

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#1768]
Layman 1.12 introduces new filtering parameters for GET Layers and GET Maps requests that we can use in Add data and Compositions panels and simplify our code. Can be tested on https://hub.lesprojekt.cz/client

* Full-text filter
* Bounding box filter
* Order by
* Ordering bounding box
* Limit
* Offset

**Comment by FilipLeitner** [comment]
Started with implementation. Ordering and bbox filter seems to be working as expected. 
- Full-text filter behaves a bit differently from the one in Micka. While Micka returns results including queried string of any length, Layman looks for the whole words. So if we insert query string "Dra" layer named "Drawing layer' wont be found.
- Limit and offset parameters are equal to limit and start params in Micka however we are not able to start using them straight away as number of matched layers is not provided. Its causing the following problem:
      -  Lets say that at first query for a set of settings (bbox etc.) we query Layman layers with no limit. It gives us 10 results -> matched = 10
      -  Once the ratio limits are calculated endpoint.datasourcePagination.limit is set accordingly, lets say 3
      -  Query with calculated limit is issued. and it will overwrite endpoin.matched value to limit value - 3.  And thats because the only way we can get the matched layers number  is to read returned layers array length
      -  Ratio limits will be updated which will lower  the limit to 1 most likely. So we end up with one layman layer instead of 3.

**Comment by fzadrazil** [comment]
I will ask about a possibility to quickly address those two issues in the next Layman release.

**Comment by fzadrazil** [comment]
Number of matched records is provided via the standard HTTP headers X-Total-Count and Content-Range, see https://github.com/jirik/layman/blob/master/doc/rest.md#get-layers

Full-text search mechanism will be altered in the next Layman release (05/2021).
