### ISSUE TITLE
Can't resolve 'fulltilt' (1.27)

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#1783]
![image](https://user-images.githubusercontent.com/5598693/116758218-e3eb1d80-aa0f-11eb-9102-1c9507f39ae2.png)

Although we do not actively maintain versions 1 and 2, this seems to be both important enough and easily fixable.
I was trying to update one of our older projects and stuck with this error message. It can be quite easily fixed by changing https://github.com/hslayers/hslayers-ng/blob/08bc32e4676b9907b0a2ab8d418a30e2290638fe/components/geolocation/geolocation.service.js#L1

to
`import FULLTILT from './fulltilt'`;

Can anyone replicate the issue? If so, I would provide a PR and propose to release 1.27.5.

**Comment by DailisLangovskis** [comment]
@jmacura Hey! Which branch are U using for running the container app?

**Comment by jmacura** [comment]
Ah, I eagerly deleted the `.concat(hslPaths.paths)` statement from my webpack.common.js... So no _direct_ error here.
