### ISSUE TITLE
Repeated npm install complains about angular-material being a git repo

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#181]
npm ERR! path /home/raitis/Projects/portal/portal/map-static/node_modules/angular-material
npm ERR! code EISGIT
npm ERR! git /home/raitis/Projects/portal/portal/map-static/node_modules/angular-material: Appears to be a git repo or submodule.
npm ERR! git     /home/raitis/Projects/portal/portal/map-static/node_modules/angular-material
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:

**Comment by SLeitgeb** [comment]
This is a bug in the 1.1.14 version of angular-material, see related [issue](https://github.com/angular/material/issues/11684). We can either wait for a new release (should be out in a few days) or downgrade to 1.1.13 in the meantime.

**Comment by raitisbe** [comment]
Downgraded in 8c8eeea14ba65ecf89fc4395afc9849c9a49cacc
