### ISSUE TITLE
Duplicit WMS layer style

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#1860]
There is a duplicit style for some WMS when selecting layer to add. Could be because the service provides GetStyles request? The capabilities seems all right.

https://gis.lesprojekt.cz/cgi-bin/mapserv?map=/home/dima/maps/africa/africover.map&language=eng&SERVICE=WMS&REQUEST=GetCapabilities
![image](https://user-images.githubusercontent.com/48727502/119032583-a3e2df00-b9ac-11eb-81d7-ca9dbd090dea.png)

**Comment by raitisbe** [comment]
The style gets merged from the root container layers 'MS' into the child uganda layer automatically by openlayers capabilities parser. Its not the way Qgis does that, but seems to be for OL. 
![image](https://user-images.githubusercontent.com/395514/119092100-abd76900-ba16-11eb-9ade-613c212c847c.png)
These styles have different legends, which for some reason we dont display and in both casesshow the child layers legend.

**Comment by raitisbe** [comment]
Dont think theres anything we could do on our side. Maybe better would be to rename any of the styles on server side. We should fixthe legend though.

**Comment by FilipLeitner** [comment]
Its bit strange tho.  Its true the styles differ in legend url but the second one doesnt seem right.

Take a look on layer parameter.

Full url of first[ legend](https://gis.lesprojekt.cz/cgi-bin/mapserv?map=/home/dima/maps/africa/africover.map&language=eng&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=uganda_landcover_cci20_test&format=image/png&STYLE=default)
....version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=uganda_landcover_cci20_test&format=image/png&STYLE=default 

Full url of second [legend](https://gis.lesprojekt.cz/cgi-bin/mapserv?map=/home/dima/maps/africa/africover.map&language=eng&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=MS&format=image/png&STYLE=default)
...version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=MS&format=image/png&STYLE=default

**Comment by fzadrazil** [comment]
Yes, because the second one is for the whole WMS as the style is propagated from the parent MS layer, isn't it?

**Comment by raitisbe** [comment]
> Yes, because the second one is for the whole WMS as the style is propagated from the parent MS layer, isn't it?

Exactly.

I have almost finished a refactor and fix for the legend.

**Comment by FilipLeitner** [comment]
> Yes, because the second one is for the whole WMS as the style is propagated from the parent MS layer, isn't it?

Oh I just couldnt find any layer named 'MS'  and that confused me.

**Comment by jmacura** [comment]
related issue #900
