### ISSUE TITLE
When adding a big list of layers from external url service, it crashes HSL app.

### ISSUE THREAD

**Issue by DailisLangovskis** [hslayers/hslayers-ng#1886]
Need to expect this get capabilities error, when loading layers. Either forbid user to add so many layers or cancel the request on error fired.

**Comment by jmacura** [comment]
relates to #1870 ?

**Comment by DailisLangovskis** [comment]
> relates to #1870 ?

Could be. Only You were mentioning adding a endpoint with many services, that crashes the app. Here I crashed the app, when loading of url services was done, had a list of all layers in datasources url tab, respectively. And only when I tried to add them all to map, the HSL app crashed.
