### ISSUE TITLE
TripPlanner has hidden points

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#1905]
Both in the side-panel
![image](https://user-images.githubusercontent.com/5598693/120772364-87a07f80-c520-11eb-9e29-5c12abea281e.png)

and in the map

![image](https://user-images.githubusercontent.com/5598693/120772396-90915100-c520-11eb-9ed3-4e66ba6b18ed.png)

there are no points displayed

**Comment by jmacura** [comment]
For the reference, this is how it should look like (taken from HSL 2.5):
in the panel...
![image](https://user-images.githubusercontent.com/5598693/120775131-35ad2900-c523-11eb-9575-4498aad5b965.png)
and in the map...
![image](https://user-images.githubusercontent.com/5598693/120775165-3f369100-c523-11eb-844c-bce092e96495.png)

**Comment by raitisbe** [comment]
some problem with assets paths during compilation, i think it might be more
of a configuration issue.

**Comment by raitisbe** [comment]
Did you run this from examples repository with `npm run serve-routing`? For me the images are shown correctly.

**Comment by jmacura** [comment]
> 
> some problem with assets paths during compilation, i think it might be more of a configuration issue.
> […](#)

You are probably correct. The screenshots are from the testing app at https://hub.lesprojekt.cz/hsl-ng/hsl-ng-3.x/apps/full/dist/ where there is a known problem with assets (cf. logo).
I believe we can close this ticket as a non-issue (or not on the hslayers side at least).
