### ISSUE TITLE
'null' record in the url history

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#1908]
We haven't been able to find the exact circumstances when or why this error appears, but can happen...

![image](https://user-images.githubusercontent.com/48727502/120776668-c59fa280-c524-11eb-99e5-9668c116329d.png)

**Comment by jmacura** [comment]
Adding to that, even `undefined` record can happen, obviously...
![image](https://user-images.githubusercontent.com/5598693/122839264-00148800-d2f8-11eb-8ad0-699469083073.png)

Not sure if this is the same bug presented in different form or another bug 😕
