### ISSUE TITLE
Eliminate querySelector in favor of elementRef

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#1945]
![image](https://user-images.githubusercontent.com/5598693/122807309-b01fcc00-d2cb-11eb-849b-cccc554a082b.png)

Steps to reproduce:
~* add this composition to the map: http://localhost:8087/rest/workspaces/vacha/maps/mk_wms (it's located in Lesprojekt Layman)~
* open any composition from Layman on hub.lesprojekt.cz, overwrite any layers you have locally
* open any other composition from Layman on hub.lesprojekt.cz, overwrite any layers you have locally
* try to open any layer settings in the LayerManager

Beside the error log, the settings gear toggle button does not toggle.

**Comment by DailisLangovskis** [comment]
@jmacura Tried to repeat, but did not succeed. Only thing I can say that -> ```
const layerPanel = this.HsLayoutService.contentWrapper.querySelector(
      '.hs-layerpanel'
    ); 
``` is to blame at some point.

**Comment by jmacura** [comment]
Neither I can reproduce the error now... 🙄  Will change the topic to refactoring and keep this issue opened for some next milestone.
