### ISSUE TITLE
Can't disable sidebar in simple map v4

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#1990]
```
function hslayersNgConfig(ol) {
      return {
        componentsEnabled: {
          guiOverlay: false,
          basemapGallery: false,
          sidebar: false,
          toolbar: false,
          geolocationButton: false,
        },
    }
}
```

![image](https://user-images.githubusercontent.com/5598693/125302270-14aed380-e32c-11eb-8d93-3cfb554e479e.png)

All the GUI components shall be disabled by the `guiOverlay: true` option, but neither that nor `sidebar: false` hides the sidebar.

Tested with https://unpkg.com/hslayers-ng-app@4.0.0/

**Comment by jmacura** [comment]
Ideas? Maybe @FilipLeitner ?

**Comment by FilipLeitner** [comment]
componentsEnabled.sidebar seems to be deprecated. Sidebar state can be set using '[sidebarpostion](https://github.com/hslayers/hslayers-ng/wiki/Config-parameters#sidebarposition)' parameter . Hovewer I agree we need to make it response to 'guiOverlay' param properly.

**Comment by FilipLeitner** [comment]
https://github.com/hslayers/hslayers-ng/issues/461

**Comment by FilipLeitner** [comment]
Seems like 'guiOverlay' is also of no use right now. What would be the difference between guiOverlay:false and pureMap?

**Comment by jmacura** [comment]
> 
> 
> Seems like 'guiOverlay' is also of no use right now. What would be the difference between guiOverlay:false and pureMap?

Quoting our documentation for `pureMap`: _This is a shorthand for `componentsEnabled.guiOverlay: false` and `mapInteractionsEnabled: false`_

**Comment by jmacura** [comment]
> 
> 
> componentsEnabled.sidebar seems to be deprecated. Sidebar state can be set using '[sidebarpostion](https://github.com/hslayers/hslayers-ng/wiki/Config-parameters#sidebarposition)' parameter . 

Oh, thanks for pointing that out. We need to update [the docs](https://github.com/hslayers/hslayers-ng/wiki/Config-parameters#componentsenabled) then.. Even though this approach seems quite counter-intuitive to me...

**Comment by DailisLangovskis** [comment]
@jmacura @FilipLeitner I am not sure if we need all of these configs, but me fix would be ->
```
sidebarVisible(state?) {
    if (
      this.HsConfig.sidebarPosition == 'invisible' ||
      this.HsConfig.pureMap ||
      !this.HsConfig.componentsEnabled.guiOverlay ||
      !this.HsConfig.componentsEnabled.sidebar
    ) {
      return false;
    }
    if (state != undefined) {
      this._sidebarVisible = state;
    }
    if (this._sidebarVisible == undefined) {
      return true;
    }
    return this._sidebarVisible;
  }
```

**Comment by DailisLangovskis** [comment]
> > componentsEnabled.sidebar seems to be deprecated. Sidebar state can be set using '[sidebarpostion](https://github.com/hslayers/hslayers-ng/wiki/Config-parameters#sidebarposition)' parameter .
> 
> Oh, thanks for pointing that out. We need to update [the docs](https://github.com/hslayers/hslayers-ng/wiki/Config-parameters#componentsenabled) then.. Even though this approach seems quite counter-intuitive to me...

Also I agree with Jan, that setting sidebar position as invisible doesn't feel right. I'd just remove such option and would just keep right or left.

**Comment by raitisbe** [comment]
It is a bit counterintuitive, yes, but this approach is sometimes used in
other frameworks, just with a better name. I think we had some requirement
to have UI enabled just without sidebar and this was the shortest way to
achieve this. Would need to search a bit in which commit/issue was the
INVISIBLE option introduced.

**Comment by DailisLangovskis** [comment]
But, if we have sidebar boolean under componentsEnabled, why do we need one
more config for it?

Raitis Berzins ***@***.***> (šajā datumā: trešd., 2021. g.
14. jūl. 12:51) rakstīja:

> It is a bit counterintuitive, yes, but this approach is sometimes used in
> other frameworks, just with a better name. I think we had some requirement
> to have UI enabled just without sidebar and this was the shortest way to
> achieve this. Would need to search a bit in which commit/issue was the
> INVISIBLE option introduced.
>

**Comment by jmacura** [comment]
> 
> Would need to search a bit in which commit/issue was the INVISIBLE option introduced.

That was in that #461 Filip has mentioned 😉
