### ISSUE TITLE
Create an attributeTable component

### ISSUE THREAD

**Issue by SLeitgeb** [hslayers/hslayers-ng#202]
The component should be able to:
* load an attribute table from CSV
* merge attribute table data to a loaded OL vector layer

In the next stage:
* display an HTLM table where the attributes can be edited in the OL layer
* highlight and center features being edited (could also maybe be toggled)

**Comment by DailisLangovskis** [comment]
@fzadrazil We now have the attributeTable component, so is the CSV file import still needed feature?

**Comment by fzadrazil** [comment]
I am not aware of any application that would need such a feature. But the original requirment came from @SLeitgeb . Do you still need that in your apps?
