### ISSUE TITLE
Add button to download multiple selected features per layer

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#2062]
# Feature Request

**Is your feature request related to a problem? Please describe.**

Its possible to select multiple features when holding SHIFT but not possible to download them as one Geojsoon/WKT file. Only seperate features can be downloaded.

**Describe the solution you'd like**
A button under layer name which provides downloading all selected features per layer. We could also have shortcuts to layer editor / styler in that same menu / toolbar.

**Describe alternatives you've considered**
Extending Save button in layer editor to download selected features OR all features per layer

**Comment by FilipLeitner** [comment]
What about making in not layer dependant so it will be possible to just 'download selected features'. Or at least add this as another option.

**Comment by raitisbe** [comment]
When the feature picker drills down through many layers and picks features in them, usually the user will need need to download features for just one theme - layer. Depends on the use case I guess. I was just a bit cautious not to clutter the UI too much.
