### ISSUE TITLE
icon-move missing in icon set

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2064]
# Bug

**Describe the bug**
`icon-move` is missing in the styles

**To Reproduce**
1. Add some layers
2. Open "physical layer list"
3. See no icon

**Expected behavior**
Icon should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/5598693/128514260-0d8b01a2-ae54-4b89-a89c-937e05731845.png)

**Additional context**

**Comment by jmacura** [comment]
As a side-note, I realised that this new drag'n'drop UI is very pleasing to desktop users but might be clumsy on mobile...

**Comment by raitisbe** [comment]
Usually on mobile it is solved using long-click
