### ISSUE TITLE
Deemphasize Clear layer button

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#2065]
# Question

![image](https://user-images.githubusercontent.com/395514/128528957-b3017524-d19e-4b03-b098-f50dce2a9283.png)
Shouldn't we make the `Clear layer` button less prominent? I think its a bit too easy clickable

**Comment by fzadrazil** [comment]
Yes, the button should definitelly be less pronounced. I am even thinking whether it makes sense to have the button in the popup window as it only displays info about one feature and is not meant as a control tool for the whole layer. The layer manager seems more appropriate for that to me. What do you think?

**Comment by jmacura** [comment]
> 
> 
> I am even thinking whether it makes sense to have the button in the popup window as it only displays info about one feature and is not meant as a control tool for the whole layer. The layer manager seems more appropriate for that to me. What do you think?

It makes sense to have such a button in the pop-up in applications where sidebar is disabled. It's probably the only use-case I can think of now. In common situations I agree that LayerManager is much more appropriate place for it.

So either having some config option or using some internal logic to satisfy above-mentioned scenario. Or we can decide that it's so unusual scenario that we are OK with ignoring it 🤸‍♂️

**Comment by raitisbe** [comment]
> Yes, the button should definitelly be less pronounced. I am even thinking whether it makes sense to have the button in the popup window as it only displays info about one feature and is not meant as a control tool for the whole layer. The layer manager seems more appropriate for that to me. What do you think?

The history of this button was in groundwater application, where user clicked multiple points on the map and at those places could see the ndvi index. To clear all the markers this button was pressed. I would like to move it somewhere else, but to where?

**Comment by jmacura** [comment]
> I would like to move it somewhere else, but to where? We dont realy have a place in layer manager which deal with the features. I think there it would feel a bit out of place too.

While we are talking about truncating the whole layer, then the layer-editor seems as a quite appropriate place. A bit more dangerous version of the "delete" button can be added, for example.

![image](https://user-images.githubusercontent.com/5598693/128940919-39d34449-f9de-4e9f-a98d-2db593f1cc4f.png)

**Comment by fzadrazil** [comment]
> A bit more dangerous version of the "delete" button can be added, for example.
> 
> ![image](https://user-images.githubusercontent.com/5598693/128940919-39d34449-f9de-4e9f-a98d-2db593f1cc4f.png)

Yes, either here or... Since the Draw toolbar/panel is used to add new geometry, wouldn't it be the best place for a button like this? Or do you add new points in Groundwater in a different way?

**Comment by raitisbe** [comment]
What about extending draw toolbar with a button dropdown to:
* Select 1 (or many with shift/ctrl) by clicking
* Select multiple by draging rectangle
* Select all features in current layer

And then when some features are selected a new buttonwould appear besides the selection toolbar button - `Delete selected`
?

**Comment by fzadrazil** [comment]
Yes, I agree. And probably also a button for downloading selected features (#2062)?

**Comment by fzadrazil** [comment]
We have discused the issue with Filip. He will implement the select, download and delete selected buttons in the Draw panel first. Then we will think about how (and whether) to incorporate those buttons to the Draw toolbar too.

**Comment by raitisbe** [comment]
Good plan

**Comment by FilipLeitner** [comment]
Implemented box selection along with download/delete selected to draw panel [here](https://github.com/hslayers/hslayers-ng/issues/2065).
Regarding whether we want to add something simillar to toolbar...I think it would be a good idea to have another place where the  box selection can be toggled. 
![image](https://user-images.githubusercontent.com/44566616/130444125-e0c8284c-2b2a-4d2d-96f3-d1ebebcbb5a5.png)

Also made a small adjustment to draw-toolbar. Moved finish drawing (do we even need this one?) and remove last point out o the toolbar to map. Thought hat it would be easier for user to work with toolbar when buttons doesnt change that much and potentially if we ll add another button for selection it would just be too much.
![image](https://user-images.githubusercontent.com/44566616/130444356-9729c6b1-881f-4104-8197-2a551c493693.png)

**Comment by raitisbe** [comment]
Regarding the finishing of drawing, it usefull on mobile devices where doubleclick is difficult.

Moving out of toolbar is ok, just have to make sure it doesnt overshadow something when sidebar is on the left side or some other control such as geolocation/tracking is present. We will have create some universal positioning mechanism eventually. Based on flexbox probably.

**Comment by FilipLeitner** [comment]
Added the 'selectin' menu to toolbar. Download/delete all selected are available in Info and Draw panels atm.  Feel free to ask for any improvements or changes. Also had some hard time with naming/translations, could you please take a look @jmacura .
![image](https://user-images.githubusercontent.com/44566616/130581908-0f889dce-e0c0-4cc1-93f1-3234fd428a1e.png)
