### ISSUE TITLE
Drawing invisible features

### ISSUE THREAD

**Issue by FilipLeitner** [hslayers/hslayers-ng#2101]
No default styling is applied for features of certain geometry when SLD defined in app config doesnt include necessary symbolizer.

**To Reproduce**
1. Run test-app
2. Add polygon/line geometry feature to 'Points' layer

**Expected behavior**
All types of geometry should be visualized properly, proper symbolizer should be added to SLD/OL style if new gemetry is added to layer

**Comment by raitisbe** [comment]
I think its a bit overprotective to add symbolizers to layers defined in container application on our own. I think what we can do is issue a warning for the user when starting drawing: "feature will not be visible unless we create a symbolizer. Would you like to do it?"

**Comment by FilipLeitner** [comment]
Ye, you are probably right. Warning is a good idea. And sure Ill include it among the rest of drawing changes
