### ISSUE TITLE
Raster publishing to Layman

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#2139]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Existing issues #356 and #357 could be resolved by this.

**Describe the solution you'd like**
Implement publishing of raster data to Layman as a new file type in the Add data component.

**Additional context**
Layman supports publishing raster files since version 1.14. For more info see https://github.com/LayerManager/layman/issues/167

**Comment by jmacura** [comment]
Additionally, there has been ol@6.7 released just today, which also seems to address the issue #357. See https://github.com/openlayers/openlayers/releases/tag/v6.7.0

**Comment by fzadrazil** [comment]
> Additionally, there has been ol@6.7 released just today, which also seems to address the issue #357. See https://github.com/openlayers/openlayers/releases/tag/v6.7.0

Great, in that case, we could offer to just add GeoTIFF to map or to add and upload. The same as with geoJson files.

**Comment by DailisLangovskis** [comment]
@jmacura @fzadrazil Currently started to refactor add-data, if this feature is not in a rush, after refactoring will try adding this new geotiff support! :)

**Comment by DailisLangovskis** [comment]
Both related issues to this one, has been merged!
