### ISSUE TITLE
Kml and geojson layers, when added from url are empty

### ISSUE THREAD

**Issue by DailisLangovskis** [hslayers/hslayers-ng#2169]
# Bug

**Describe the bug**
When trying to add layer from url as kml or geojson, app doesn't provide any errors, but there are no features loaded into the layer.

This was found in branch #2152 

**To Reproduce**
1. Go to Datasources panel.
2. Click on Url and then select type KML or GEOJSON
3. Connect using (https://app.geology.cz/atom/atom.php?request=getKML&file=7&headerfile=1) or
(https://gis.karvina.cz/public/opendata/hranice_casti_obce/hranice_casti_obce.geojson)
4. Add title and name, and add the layer to the map

**Expected behavior**
Added layer holds source with many features

**Comment by FilipLeitner** [comment]
GeoJSON file works when correct CRS (5514) is set in 'Advaned options'.
KML will test.
