### ISSUE TITLE
Prepare an abstraction for OL feature selection

### ISSUE THREAD

**Issue by SLeitgeb** [hslayers/hslayers-ng#223]
When layer is being added through `config`, create an OL map select interaction for it if it has property `selectable !== undefined`.

Either object or a boolean value should be expected as the value of `selectable`, e.g.:
```
selectable: {
  condition: 'click',
  multi: true
},
```
or
```
selectable: true,
```
if default settings for OL Select should be used.

Document the changes in https://github.com/hslayers/hslayers-ng/wiki/Config-parameters

See the following documentation and example for OL Select:
https://openlayers.org/en/latest/apidoc/module-ol_interaction_Select-Select.html
https://openlayers.org/en/latest/examples/select-features.html

**Comment by raitisbe** [comment]
We already have a Select interaction in query modules which is also used by the draw module. Two Select interactions might conflict with eachother, I think you can have just one active at the same time.

**Comment by raitisbe** [comment]
Subscribe to vectorQueryFeatureSelection in HsEventBusService instead
