### ISSUE TITLE
Vector layer pop-up incorrect

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2291]
# Bug

**Describe the bug**
When multiple vector layers overlap, the pop-up window shows only information from one of them.

**To Reproduce**
1. Add multiple vector layers which overlap each other.
2. Allow popUp in the config (both hsConfig and layers' config)
3. Hover over some feature
4. See incorrect data as on the screenshot below

**Expected behavior**
Information from each layer shall appear (see below).

**Screenshots**
What it does when **two overlapping polygon layers** are visible:
![image](https://user-images.githubusercontent.com/5598693/137461576-551403df-bff8-4de9-935d-e1d7f420b4c8.png)
What it does when **only one polygon layer** is visible:
![image](https://user-images.githubusercontent.com/5598693/137461810-267cea2a-a6bc-4761-92e5-78c6dcd1454c.png)
What it **should do** when two or more overlapping polygon layers are visible (in app running on HSL 2.5):
![image](https://user-images.githubusercontent.com/5598693/137462104-697ebbd3-b81a-44d7-9169-aa09b098e4f6.png)

**Additional context**
Discovered in this app: https://git.lesprojekt.cz/jmacura/rural-attractiveness-cz

**Comment by DailisLangovskis** [comment]
@jmacura I tried to fix this, but apparently I failed!

**Comment by jmacura** [comment]
@DailisLangovskis Thank you! Were you able to reproduce it, at least?
