### ISSUE TITLE
Resurrect hslayers-material

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#2338]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Seems that Hslayers-material library is a bit stale. 

**Describe the solution you'd like**
Needs to be resurrected. I think with the decoupling mechanism, panel containers and Css decoupling and compilation we have the puzzle pieces largely in place.

**Describe alternatives you've considered**
We could let hslayers-material die :/

**Comment by FilipLeitner** [comment]
Support for material will be dropped.
