### ISSUE TITLE
Geometric operations in Drawing

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#2386]
# Feature Request

**Describe the solution you'd like**
Add more tools to drawing for polygons like

- split polygon by polyline
- union
- intersection
- difference
- (symetrical difference)?

**Comment by jmacura** [comment]
An UI/UX question is, whether this should be a part of (already quite complex) drawing panel, or whether it would be better to create a new panel (like "edit"). Or a sub-panel inside of drawing? Composite like the new widgets in query and layer-editor?

**Comment by FilipLeitner** [comment]
Good question. I was thinking of extending drawing panel using https://getbootstrap.com/docs/5.0/components/navs-tabs/#tabs so I guess that could count as 'sub-panel ' option you suggested... Althouh I'll start implementing it this way I am open to a discussion
