### ISSUE TITLE
TreeLayer

### ISSUE THREAD

**Issue by wohnout** [hslayers/hslayers-ng#24]
Old HSLayers had class Layer.TreeLayer (http://redmine.ccss.cz/projects/hslayers/repository/entry/branches/hslayers-3.5/source/HSLayers/Layer/TreeLayer.js)

Init is done:
`LAYERS.geoportal_base_kn = new HSLayers.Layer.TreeLayer("kn",
        "http://geoportal.kraj-lbc.cz/mapserv/hsmap/index.php",
     {project: "geoportal_base", transparent: true, layers: 'parc sprava'},
     {
            title: "&lt;b&gt;Katastr nemovitostí a správní hranice&lt;/b&gt;",
            visibility: true,
            ratio: 1,
            isBaseLayer: false,
            queryable: true
        });`

**Comment by raitisbe** [comment]
Refs #273
