### ISSUE TITLE
Map swipe control panel

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#2421]
# Feature Request

Create new tool which will introduce a map swipe control so the user is able to compare two map contents while the view is synchronized. Eg. https://viglino.github.io/ol-ext/examples/control/map.control.swipe.html
https://github.com/Viglino/ol-ext/blob/master/src/control/Swipe.js
There can be several options how to define the map content of both the windows. That is for a discussion:

- each window displays just one layer, there are two dropdowns with the list of available layers
- left window shows the default map of the application / right window shows one selected layer (dropdown list in the panel)
- content of both windows is defined by checkbox lists of available layers

I guess the selected solution depends on what the swipe control component is capable of.

**Additional context**
One existing application for inspiration https://app.iprpraha.cz/apl/app/prahavcera/
But we would like to have more general tool for HSLayers, not just one specific application.

**Comment by jmacura** [comment]
From the UI and program architecture perspectives I think this can be implemented as a new module with a new panel, where in the panel there would be following controls:

- layer(s) for window 1
- layer(s) for window 2 (some option like "disabled" could be added and the window 2 would then show anything that is set in the LayerManager at the moment)
- swipe direction: horizontal/vertical/(arbitrary? 💭 That would be awesome if it could be set as an azimuth angle... 🙂 )

![image](https://user-images.githubusercontent.com/5598693/144591904-7027a2f0-1a72-4a5f-84a8-78880eceb050.png)

**Comment by fzadrazil** [comment]
Thanks for the doodle, Honza! Yep, that is in accordance with the original idea. I think it will be good to start with the integration of swipe control into the map and then we can solve the exact method of selecting the map windows content.

**Comment by DailisLangovskis** [comment]
@jmacura @raitisbe So this will be a standalone app or module. I would like to start experimenting, but I want to know from which end to start.

**Comment by fzadrazil** [comment]
If possible, we would like to have it as a hslayers module, another tool in the panel. We will then use it in multiple applications.

**Comment by DailisLangovskis** [comment]
> If possible, we would like to have it as a hslayers module, another tool in the panel. We will then use it in multiple applications.

Alright then, I will take on this issue.
