### ISSUE TITLE
Add ArcGIS service as a whole

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#2459]
# Feature Request

**Is your feature request related to a problem? Please describe.**
It is currently only possible to add ArcGIS service layers one by one. But that can be really undesirable and resource consuming.

**Describe the solution you'd like**
ArcGIS services are supposed to be requested as a whole and always by a single request. Eg. this service contains over 250 layers
http://ags.cuzk.cz/arcgis/rest/services/ZABAGED/MapServer. If added to the map now with all the layers selected, it leads to at least 250 requests.
But the service can (and should) be requested by a single export request which will render it whole on the server side
http://ags.cuzk.cz/arcgis/rest/services/ZABAGED/MapServer/export?bbox=-689602.5564075932%2C-1064000.5753358873%2C-688527.8960319683%2C-1063380.8197406242&f=image
If only some of the layers should be rendered, there is a layer parameter for that purpose
http://ags.cuzk.cz/arcgis/sdk/rest/index.html#/02ss00000062000000

Rendering mechanism of ArcGIS services should be changed to follow the supposed way of usage. Might be a good idea to also allow the user to add a whole service as one map layer object without specifying layers.
https://openlayers.org/en/latest/apidoc/module-ol_source_ImageArcGISRest.html with the LAYERS param.

In case of tiled map service (eg. http://ags.cuzk.cz/arcgis/rest/services/zm/MapServer) it does not even make sense to load it layer by layer because it has the tiles prerendered and always returns the same image. Should be in fact treated as XYZ services.

**Additional context**
It is actually similar to WMS which can contain a lot of layers but whole WMS can be rendered by a single GetMap request with the layers specified.
ArcGIS has basically three different types of map services: 
* dynamic (works similar to WMS)
* tiled (similar to XYZ)
* feature (similar to WFS)

**Comment by fzadrazil** [comment]
It seems that OL doesn't have a general ArcGIS layer source and we have to specify the type of source manually. This can be derived from the JSON definition of the service (simply add ?f=json to the service URL entered by user). To clarify and have some reference for testing, those are all the user scenarios or URL formats the user can possibly enter:

* http://ags.cuzk.cz/arcgis/rest/services/ZABAGED/MapServer
  Dynamic ArcGIS service, which should be created as [ImageArcGISRest](https://openlayers.org/en/latest/examples/arcgis-image.html)
  * "MapServer" string at the end of URL and "capabilities" parameter contains "Map" in JSON definition
  * singleFusedMapCache = false and missing tileInfo parameter in the JSON definition
  * User should be able to select all layers (we can ommit the params.LAYERS in the source definition then) or select some of the layers. It should still be just one layer in HSLayers and rendered by single request.
  * It is similar to WMS when user selects multiple layers but those are rendered by a single GetMap with LAYERS parameter

* http://ags.cuzk.cz/arcgis/rest/services/ZABAGED/MapServer/0
  Only one specific layer (with the ID = 0) from the dynamic ArcGIS service. Should be also created as ImageArcGISRest, but with the params.LAYERS specified.
  * "id": <layer index> parameter present and "type": "Feature Layer" in the JSON definition

* http://ags.cuzk.cz/arcgis/rest/services/ortofoto_wm/MapServer
  Tiled ArcGIS service, which should be created as [TileArcGISRest](https://openlayers.org/en/latest/examples/arcgis-tiled.html) or [XYZ](https://openlayers.org/en/latest/examples/xyz-esri.html).
  * "MapServer" string at the end of URL and "capabilities" parameter contains "Map" in JSON definition
  * singleFusedMapCache = true and tileInfo parameter present in the JSON definition.

* http://ags.cuzk.cz/arcgis/rest/services/ortofoto_wm/MapServer/0
  Can be theoretically entered by user, but doesn't make sense and should be created without the /0 index at the end since it has precomputed tiles and doesn't matter what layer is specified. The tiles will be served for the requests.

* https://mapy.georeal.cz/arcgis/rest/services/Testy/Budovy_test/FeatureServer
  Feature service (similar to WFS), user should select specific layer/s which are server separately. Created by [VectorLayer with EsriJSON format](https://openlayers.org/en/latest/examples/vector-esri.html)
  * "FeatureServer" string at the end of URL
  * "capabilities" parameter doesn't contain "Map" in JSON definition (contains Query, Editing, ... based on the settings)

* https://mapy.georeal.cz/arcgis/rest/services/Testy/Budovy_test/FeatureServer/1
  The same but with the specified layer with index = 1

* http://ags.cuzk.cz/arcgis/rest/services/3D/dmr4g_wm/ImageServer
  Less common image service. Should be also created as [ImageArcGISRest](https://openlayers.org/en/latest/examples/arcgis-image.html). Doesn't have layers
  * "ImageServer" string at the end of URL
  * "capabilities" parameter contains "Image" in JSON definition

**Comment by DailisLangovskis** [comment]
@fzadrazil I am only confused how can we tell apart the http://ags.cuzk.cz/arcgis/rest/services/ZABAGED/MapServer from http://ags.cuzk.cz/arcgis/rest/services/ortofoto_wm/MapServer, for example?
