### ISSUE TITLE
Reverse order of layers

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#2475]
# Question

We are currently rendering layers in map from bottom to top as they are listed in layer manager. It can be switched by setting the `reverseLayerList: true`, but I think this should really be the default value. It is habitually like that in GIS SW...what is higher in the layer list is "higher" in the map.

**Comment by raitisbe** [comment]
That would mean that we also have to put base layers at the bottom

**Comment by fzadrazil** [comment]
> That would mean that we also have to put base layers at the bottom

I think simply reversing the meaning of reverseLayerList config could be sufficient. Or is there some catch?

**Comment by raitisbe** [comment]
Backwards compatibility. Let's just asume reverseLayerList: true by default as you said without reversing the meaning.

**Comment by fzadrazil** [comment]
> reverseLayerList: true by default

That is probably good enough.
