### ISSUE TITLE
Allow to turn layers on/off from map swipe panel

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#2478]
# Feature Request

**Describe the solution you'd like**
It might be too much to ask :-) But as I work with the swiper, it would be really great to have a chance to turn on and off the layers directly from the map swipe panel. Sth like that...
![image](https://user-images.githubusercontent.com/48727502/147013254-287c3829-be11-448b-bd40-e947a81d54ad.png)

Do you think it is possible? If you have more layers in the map and need to switch between, it would be really handy not have to always switch to layer manager and back to map swipe.

**Alternative solution**
Another solution would be to display only currently visible layers in the map swipe list (there is no sense to display invisible layers there). The user would see then what layers are available for the swiper, but would still have to switch to layer manager to turn layers on and off.

**Comment by raitisbe** [comment]
The checkbox ticking might interfere with dragging

**Comment by DailisLangovskis** [comment]
I'll see what I can do, but only in the evening.
