### ISSUE TITLE
Module build failed due to "Can't find stylesheet to import"

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2507]
# Bug

**Describe the bug**
Installing hslayers-ng@7.0.2 and running build ends with an error.

**To Reproduce**
1. Into some app install `hslayers-ng@^7`
2. Try to build the app
3. See error

**Expected behavior**
Build should compile the code.

**Screenshots**
![image](https://user-images.githubusercontent.com/5598693/148229631-626d9240-236b-43e9-b0eb-3413bd0b6df4.png)

**Additional context**
Not sure if the problem is on the app site or in the hslayers-ng.

**Comment by raitisbe** [comment]
Don't use hslayers-bootstrap.scss, but instead use:
"styles": [
              "./node_modules/hslayers-ng/css/hslayers-ng.css"
            ],

**Comment by raitisbe** [comment]
Yes, that's a quite unfortunate breaking change which was overriden by the next one which uses hslayers-ng.css

**Comment by raitisbe** [comment]
Changelog rewritten

**Comment by jmacura** [comment]
I can confirm that the settings you have proposed does indeed work. Thank you, also for updating the changelog! I am closing this issue.
