### ISSUE TITLE
Ability to display layer for full map, when using map-swipe component

### ISSUE THREAD

**Issue by DailisLangovskis** [hslayers/hslayers-ng#2509]
# Feature Request

**Describe the solution you'd like**
Sometimes the user would want to have specific layers being displayed for the whole map, while still using the map swipe control.

This could be implemented as another D&D table for full map display.

**Comment by raitisbe** [comment]
Actually I think the layers should be in "Entire Map" section by default if no particular side is specified for them in the config. That would also make the list shorter by default since less wrapping of long layers names would occur.
