### ISSUE TITLE
cloneView function is not working properly

### ISSUE THREAD

**Issue by FilipLeitner** [hslayers/hslayers-ng#2522]
# Bug

**Describe the bug**

view.getProperties() is not returning all 'options' defined in config.default_view. In result we are not able to change projections.

**Expected behavior**
View shoudl be cloned with all the options

**Screenshots**
![image](https://user-images.githubusercontent.com/44566616/148766735-cd7e1e8d-99a2-431a-9f00-30e862cba93f.png)

![image](https://user-images.githubusercontent.com/44566616/148766702-4ae838a1-69e7-4bdb-ba97-452c9adda9ee.png)

https://github.com/hslayers/hslayers-ng/commit/a307da483adc602743ecde9ed68bce5ae247453b

**Comment by raitisbe** [comment]
Ah that was the reason why we ended up with options_ before. It's possible to use getProjection(), but not getMultiWorld. Maybe its time to revisit the usage of the original view in default_view instead of cloning it.

**Comment by jmacura** [comment]
Oddly, the projection does work in my application based on HSL 7.

**Comment by raitisbe** [comment]
The cloning was done due to the fact that OL version in the container application was might be different from the OL in hslayers-ng/node_modules and we ended up with blank screen in some cases. Nowadays we can use `paths` in tsconfig to circumvent that.
