### ISSUE TITLE
hs-wms-to-add param disables Add data panels URL section

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#2541]
# Bug

**Describe the bug**
When we open page with already set hs-wms-to-add GET parameter, then every time we want to open Add data panel, the layer gets again added to the map and layer manager panel is switched on instead.

**To Reproduce**
1. Go to http://localhost:4200/?hs-wms-to-connect=http%3A%2F%2Flvmgeoserver.lvm.lv%2Fgeoserver%2Fows&hs-wms-layers=public%3ALV_admin_vienibas
2. Click on Add data sidebar button
3. Other panel opens

**Expected behavior**
GET param should be cleared from the url or ignored subsequently

**Additional context**

Theres also an a little bit related error 
![image](https://user-images.githubusercontent.com/395514/149327233-f6822776-6bf9-4572-9efb-b86dcd7c77d9.png)

**Comment by DailisLangovskis** [comment]
Reopened due to DOM error
