### ISSUE TITLE
Raster layers loaded from layman, should not be visible in draw layer list

### ISSUE THREAD

**Issue by DailisLangovskis** [hslayers/hslayers-ng#2609]
# Bug

**Describe the bug**
When the user has some raster type layers loaded from Layman, they are visible in draw layer list, which is not a expected behavior.

**To Reproduce**
1. Login to Layman catalogue.
2. Go to Draw toolbar.
3. Click on layer dropdown list
4. All the layers are visible, even raster

**Expected behavior**
Raster layers are filtered out of the list

**Comment by FilipLeitner** [comment]
Should they? Isnt that supposed to be for vectors only?

**Comment by DailisLangovskis** [comment]
@FilipLeitner Well The problem is, that we don't specify the type of the layer

**Comment by fzadrazil** [comment]
> Should they? Isnt that supposed to be for vectors only?

There was a typo in the issue title (now / not) :-)

**Comment by FilipLeitner** [comment]
@DailisLangovskis  I havent read the description  and the original title read 'should now be visible' so tought you want them there

**Comment by DailisLangovskis** [comment]
@FilipLeitner Aww, sorry about the typo... :/

**Comment by DailisLangovskis** [comment]
So we get all the layers from Layman as a list, but we don't know what kind of layers are they, because the file_type property is only available, when the layer metadata is requested. So we would have to request each of the layers metadata, to make sure it a vector layer. Also, i don't know the best way to do this right now.

**Comment by fzadrazil** [comment]
> file_type property is only available, when the layer metadata is requested

I will ask how difficult would it be to add it to GET (Workspace) Layers and if possible, add it to the next Layman release.
