### ISSUE TITLE
Upgrade RxJS to version 7

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2618]
# Feature Request

**Is your feature request related to a problem? Please describe.**
This is both feature request and a bug. As @DailisLangovskis is already looking forward to changes in rxjs@8, we still officially require rxjs@6. As per https://blog.nrwl.io/whats-new-in-angular-v13-77246aca231f

> New projects are now created using RxJS 7. Existing projects are remaining on RxJS 6 when migrating.

That's probably why we didn't receive upgrade automatically via @dependabot

Now when you try to install develop version of hslayers-ng from fresh, you get many ugly errors like these

![obrazek](https://user-images.githubusercontent.com/5598693/152051733-5d15c90b-385d-41fc-b464-e5ec70b1d493.png)

**Describe the solution you'd like**
Upgrade deps to rxjs@7

**Describe alternatives you've considered**
Rollback Dailis' upgrades (but I don't think it's the right way to go).

**Additional context**
Screenshot above.

**Comment by raitisbe** [comment]
Yes, indeed we should fixate the required version ranges. I usually leave it to the last step before publishing the release since it requires rewriting of wiki and README. Sometimes even forget one or two of the deps and then patch is in order :)

**Comment by raitisbe** [comment]
Done in https://github.com/hslayers/hslayers-ng/commit/dd020c2b9b147eafc7a6f3f231303c2428cecf4b
