### ISSUE TITLE
Copied WMS layer ignores sublayers property

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2631]
# Bug

**Describe the bug**
When a WMS layer which has the `sublayers` property defined is copied, this property is ignored.

**To Reproduce**
1. Set `sublayers` property on some MWS layer (e.g. _Latvian municipalities (1 sub-layer)_ in test-app)
2. Click on 'Copy layer'
4. See how the copy actually has all the sublayers.

**Expected behavior**
The sublayers property shall be reflected during copy.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/5598693/152446406-8355613e-b3ff-42ac-bfc4-834191772ba2.png)
![obrazek](https://user-images.githubusercontent.com/5598693/152446691-7b93745e-7cfa-4c5d-9f46-dadf38b648d6.png)

**Additional context**
As a side-issue, the copied layer is query-able, while the original was not. Not sure, if the original should be or the copy shouldn't be 😄

**Comment by raitisbe** [comment]
>As a side-issue, the copied layer is query-able
:)
