### ISSUE TITLE
"Layer not available" never disappears

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2632]
# Bug

**Describe the bug**
When a layer is not temporarily available, a red exclamation mark pops-up in the LayerManager, which never goes off, even though the layer is available again.

**To Reproduce**
1. Somehow manage to loose layer availability (not sure how I have achieved that 😅 )
2. See the error icon on the right
3. Somehow manage to make the layer available again (I lost login to Layman, so I have re-logged in)
4. See the error icon on the right still

**Expected behavior**
The error icon shall vanish when it's no longer relevant (when layer is available)

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/5598693/152446602-9013a47d-9f61-4e45-badb-dcf009bb3e0d.png)

**Comment by raitisbe** [comment]
Maybe you restarted hslayers-server while the layer was loading? Proxy restarting would break some tiles and 1 tile is all it takes.

**Comment by DailisLangovskis** [comment]
@raitisbe Do we have any way of detecting if hslayers server is turned on at some point after the app has loaded already?

**Comment by raitisbe** [comment]
I think the safest way would be just to use the already existing functions for monitoring loading progress. If a successful tile load is encountered, then the error can be cleared.

**Comment by jmacura** [comment]
> Maybe you restarted hslayers-server while the layer was loading? Proxy restarting would break some tiles and 1 tile is all it takes.

It might be rather a brief internet connection interruption. Nothing uncommon here... But the hslayers-server was up and running the whole time.
