### ISSUE TITLE
Improve print panel

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2634]
# Feature Request

**Is your feature request related to a problem? Please describe.**
We can make nice maps but ugly print layout. There is a low hanging fruit which would make the output much nicer.
Improvement ideas:
+ Style the map title
+ Add legend
+ Add optional imprint information
+ Add optional scale (either numeric or graphic, only useful on large scale)

**Describe the solution you'd like**
For now just improve the look and feel of the output.

**Describe alternatives you've considered**
For the future, some extra map-designer tool which would also allow to move and style the individual components of the map design, would be supercool.

**Additional context**
.

**Comment by DailisLangovskis** [comment]
@jmacura Did You mean this scale
![scale](https://user-images.githubusercontent.com/46564459/154470642-406cd500-0e6a-4838-95ad-2349ab9ea2ce.png)
?

**Comment by jmacura** [comment]
@DailisLangovskis Yeah! Bloody awesome!
