### ISSUE TITLE
Search toolbar breaks external service handlers

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2635]
# Bug

**Describe the bug**
After using the search box, the connection between external DOM elements and HSL components stops work.

**To Reproduce**
1. Use search to find some place
2. Trigger some external DOM event (in the test-app, hover over "Polygon1" or "Polygon2" text on top)
4. See nothing happening

**Expected behavior**
The action shall be executed as defined in HsConfig.

**Screenshots**
.

**Additional context**
.

**Comment by raitisbe** [comment]
How ro you find these :o

**Comment by jmacura** [comment]
> 

I play a very undisciplined user when testing. Switching between panels, tools, layers, zooms, ... 🙂
