### ISSUE TITLE
Pop-up is displayed also for layer which has no "popUp" property

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2672]
# Bug

**Describe the bug**
When two or more vector layers are overlapping and one of them has "popUp" property defined, the pop-up displayes also values for the other layers.

**To Reproduce**
1. Add some vector layers which mutually overlap
2. Set popUp for some of them
3. Hover/click at the layer which has popUp property defined in an area where it overlaps with some of the other layers
4. See properties of all the layers beneath the mouse

**Expected behavior**
Only the layer which has "popUp" property defined shall be queried and its properties displayed.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/5598693/153419642-2858c0d4-a897-4657-9b8f-1fdcaa8113e0.png)
Only this pop-up below shall be displayed nevertheless the overlap with the "Sieusoil" layer, which does not have "popUp" property defined.
![obrazek](https://user-images.githubusercontent.com/5598693/153420184-fb3b6856-bf08-4f62-80b2-0c645706472d.png)

**Additional context**
.

**Comment by raitisbe** [comment]
I was operating on the assumption that popup is visible for all layers by default.

**Comment by jmacura** [comment]
> I was operating on the assumption that popup is visible for all layers by default.

It does not reflect the status quo. If the popup would be visible by default for all layers, then we would need to display it everywhere, not only in places where the layers overlap. This does not happen at the moment.
