### ISSUE TITLE
Save-map simple form

### ISSUE THREAD

**Issue by FilipLeitner** [hslayers/hslayers-ng#2676]
# Bug

**Describe the bug**
Config parameter advancedForm: false toggles 'simple form' for saving compositon. However this component is not working, UI bugged also:
- advanced options menu not opening
- auth warning visible when logged in
- thumbnail not working
- save button always disabled

**To Reproduce**
1. Set advancedForm config option to 'true'
2. Run app
3. Open 'Save map' panel

**Expected behavior**
Its possible to save current map state to composition

**Screenshots**
![image](https://user-images.githubusercontent.com/44566616/153563687-c582e6af-515e-4f67-b120-925192f6d024.png)

**Additional context**
Simple form should be fixed or removed

**Comment by DailisLangovskis** [comment]
@raitisbe So we decided to remove simple form?

**Comment by fzadrazil** [comment]
Hm, I would keep it and make it default option :-) I haven't seen anyone filling in the metadata in advanced form.

**Comment by DailisLangovskis** [comment]
I would merge them both together, because they both have some flaws and author details could go under hidden panel, like advanced options

**Comment by fzadrazil** [comment]
> author details could go under hidden panel, like advanced options

Exactly, agree on that.

**Comment by DailisLangovskis** [comment]
ok, I will do it be the week then! :)
