### ISSUE TITLE
Allow having more than one map on one page

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#2719]
# Feature Request

**Is your feature request related to a problem? Please describe.**
When adding HSLayers map in the form of HTML widget eg. in some kind of CMS, there is a need to have multiple root angular components in one page.

```
<hslayers-app id="map1"></hslayers-app>
<hslayers-app id="map2"></hslayers-app>
```

**Describe the solution you'd like**
I understand from many sources that the problem is in bootstraping mechanism of angular which renders only one instance of the main component. Solution should be to bootstrap it manually like

```
@NgModule({
  declarations: [HslayersAppComponent],
  imports: [BrowserModule, HslayersModule],
  providers: [],
//  bootstrap: [HslayersAppComponent],
})
export class AppModule implements DoBootstrap {
  ngDoBootstrap(appRef: ApplicationRef) {
    appRef.bootstrap(HslayersAppComponent, "#map1");
    appRef.bootstrap(HslayersAppComponent, "#map2");
  }
}
```

It works this way with a minor setback. All of the components gets rendered twice in each of the instances :-)
![image](https://user-images.githubusercontent.com/48727502/154954583-76bcdd8b-091e-47e9-b29b-5f490e92187b.png)

**Comment by FilipLeitner** [comment]
Hmm seems like panelContainer.service observable being triggered multiple times (twice?) per createPanel call? What about map is it working for both instances?

**Comment by FilipLeitner** [comment]
Tried setting up 2 instances of hslayers in same app and the problem is that we are creating only one instance of a services (they are provided in root). It is possible to scope services by injecting them in component `providers` array but we would have to do that for all and I am not even sure that would work.
To showcase  I was able to fix the layout components in [this branch](https://github.com/hslayers/hslayers-ng/tree/multiple-maps).

**Comment by raitisbe** [comment]
I think having singleton services is still the way to go. Me might have separate storage for each app instance inside the common service, such as
<hslayers-app app="map1"></hslayers-app>
<hslayers-app app="map2"></hslayers-app>

(don't like to use id)

Inside the service we could have a 
```
export class HsDrawService {
  app: [key: string]: {
    drawableLayers: Array<any> = [];
    drawableLaymanLayers: Array<any> = [];
    hasSomeDrawables = false;
    moreThenOneDrawable = false;
    draw: Draw;
    modify: Modify;
    ...
  }
```
The rewrite would be huge line-number-wise, but rather straightforward.

**Comment by FilipLeitner** [comment]
> I think having singleton services is still the way to go. We might have separate storage for each app instance inside the common service, such as
> 
> ```
> <hslayers-app id="map1"></hslayers-app>
> <hslayers-app id="map2"></hslayers-app>
> 
> AND
> 
> <hslayers id="map1"></hslayers-app>
> <hslayers id="map2"></hslayers-app>
> ```
> 
> Inside the service we could have a
> 
> ```
> export class HsDrawService {
>   app: [id: string] = {default: {
>     drawableLayers: Array<any> = [];
>     drawableLaymanLayers: Array<any> = [];
>     hasSomeDrawables = false;
>     moreThenOneDrawable = false;
>     draw: Draw;
>     modify: Modify;
>     ...
>   }}
> ```
> 
> Where the id would be `map1` The rewrite would be huge line-number-wise, but rather straightforward.
> 
> Calling HsConfig update function would also have to be done using some `id` parameter or through [config] attribute on `<hslayers>` element.

Seems complicated :D still.
- So every service reference would have to be rewriten  from eg. `hsLayoutService.setMainPanel()`  to `hsLayoutService[mapId].setMainPanel()`?? 
- And inside every service on init we would have to clone the default app object multiple times (number of apps per page)?
- also templates would have to be prepended with the id,
Something like that?

**Comment by raitisbe** [comment]
Yes, pretty much, but only for data and not functions.

Could use `hsLayoutService.setMainPanel(mapId, ..`

Now I remember the that due to this complexity I created the duplicate app functionality using iframes before :)

**Comment by raitisbe** [comment]
>Seems complicated :D still.
Yes, very

**Comment by jmacura** [comment]
As per https://medium.com/swlh/multiple-angular-apps-on-a-single-page-9f49bc863177 I would investigate the other options first. The ngx-build-plus option seems especially promising, as we use it already for module federation.

**Comment by raitisbe** [comment]
>also templates would have to be prepended with the id

`HsDrawService[app].drawableLayers`

`app` would be passed down from HslayersNgComponent down to all child components.

**Comment by jmacura** [comment]
> > ngx-build-plus
> 
> If I understood correctly in the article they compile the app twice with some sepearate namespaceName provided and then add both of those bundles to the page. Its not an option for us since we have a single hslayers-app bundle. Will investigate webcomponents.

Aye, I have realised that only afterwards. That would require us to build the hslayers-app multiple times with different element-names which is not really what we are up to.

So investigating further, this tiny change of ngDoBootstrap seems ridiculously simple: https://stackoverflow.com/a/45897001/3019419

**Comment by raitisbe** [comment]
> So investigating further, this tiny change of ngDoBootstrap seems ridiculously simple: https://stackoverflow.com/a/45897001/3019419

That doesnt solve the shared service problem

**Comment by fzadrazil** [comment]
> > So investigating further, this tiny change of ngDoBootstrap seems ridiculously simple: https://stackoverflow.com/a/45897001/3019419

That is actually only more general form of ngDoBootstrap that I used in the original post for more clarity. This should definitelly be used in the end though.

I have also been trying to use angular elements, but haven't been successfull so far and abandoned it for the time being. Have it stashed locally, I will try to resurect it.

**Comment by raitisbe** [comment]
For me the customeElements approach only yielded `[NullInjectorError: No provider for o`. 
I also tried changing providedIn to  'any' in all of our services, but still they are shared.

**Comment by fzadrazil** [comment]
My experiments with angular elements and reading config param can be found here https://github.com/hslayers/hslayers-ng/tree/variable-config. The result is somehow even worse, the components are rendered four times :-D

```
<hslayers-app-el config="hslayersNgConfig"></hslayers-app-el>
<hslayers-app-el config="hslayersNgConfig"></hslayers-app-el>

```

**Comment by raitisbe** [comment]
Im gonna try the refactoring approach `app: [id: string] = {default: {`..

**Comment by raitisbe** [comment]
> My experiments with angular elements and reading config param can be found here https://github.com/hslayers/hslayers-ng/tree/variable-config. The result is somehow even worse, the components are rendered four times :-D
> 
> ```
> <hslayers-app-el config="hslayersNgConfig"></hslayers-app-el>
> <hslayers-app-el config="hslayersNgConfig"></hslayers-app-el>
> ```

Do they share the services?

**Comment by fzadrazil** [comment]
> > My experiments with angular elements and reading config param can be found here https://github.com/hslayers/hslayers-ng/tree/variable-config. The result is somehow even worse, the components are rendered four times :-D
> > ```
> > <hslayers-app-el config="hslayersNgConfig"></hslayers-app-el>
> > <hslayers-app-el config="hslayersNgConfig"></hslayers-app-el>
> > ```
> 
> Do they share the services?

Yes, I guess they do.

**Comment by raitisbe** [comment]
I did the rewrite in https://github.com/hslayers/hslayers-ng/tree/multiple-maps-hardcore
Currently its pretty much broken, would appreciate help
