### ISSUE TITLE
Map size ignored when window too small on startup

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2797]
# Bug

**Describe the bug**
When the test-app is loaded with a small (in height) window, it does not split the window in half for each app, but instead the first app is loaded in full-screen mode and the other is placed below it.

**To Reproduce**
1. Start test-app with a tiny browser window
2. See only one app in the view

**Expected behavior**
Not sure, really, but the behaviour described above is not consistent. The size of the window when a page is loaded should not matter.

**Screenshots**
When the window is large on load time and shrink only later, the behaviour is expectable.
![image](https://user-images.githubusercontent.com/5598693/159364748-fc9e1706-e970-493d-a0a9-d6123c14ddc4.png)
When the window is too small in height on startup, the first app goes full-screen while the second is below it.
![image](https://user-images.githubusercontent.com/5598693/159364890-a6434dbf-9781-4ace-b09d-f1a0e0396d25.png)
When resizing the window, the other app reveals itself just briefly
![image](https://user-images.githubusercontent.com/5598693/159364951-4286bba3-c56f-49d1-a8ca-61504076367e.png)
...then it also hides, leaving a part of the map blank
![image](https://user-images.githubusercontent.com/5598693/159364975-b44fdbf3-f301-4fad-9ae2-80cd48474d13.png)

**Additional context**
It might be as well only a problem in the test-app itself and not affecting the hslayers library. In that case, this is rather a non-issue and it can be safely ignored 🙂

**Comment by FilipLeitner** [comment]
Good find. Its because of the failed asumption that app should be in 'full-screen' mode when height is less than 350px. Forced the defined height no matter the value so the behavior is more predictable. bebd6650122733506c6bdad99ff4237b52b33557

**Comment by raitisbe** [comment]
Gonna cherry pick this 37170b4738fce1ea9331b420b505ede381b6f931 commit too

**Comment by raitisbe** [comment]
Seems to be solved
