### ISSUE TITLE
Multiapp share

### ISSUE THREAD

**Issue by FilipLeitner** [hslayers/hslayers-ng#2821]
Behavior of share panel or rather pure/full app permalinks for multiple apps is not really in sync with the multi-app behavior of the rest of the app right now.  It will always share whole container application not individual instances of hslayers. 
I imagine this could be kinda resolved by redirecting to some single app instance prepared for this. We would probably need to parse app config params into share composition .

How should we tackle this aspect, what do you think?

**Comment by raitisbe** [comment]
I think it is fine that it shares the container application. I suppose in case when we have multiple apps on a page scattered between blocks of text etc. the apps would not make much sense individually.

**Comment by fzadrazil** [comment]
I agree with Raitis. I was even thinking whether the share tool has any meaning for multiple apps and shouldn't be disabled in that case.

**Comment by raitisbe** [comment]
Scrolling to the app where the share panel is active could be made with an extra param in the url.
