### ISSUE TITLE
Support CSW type of map composition

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#2836]
# Feature Request

**Is your feature request related to a problem? Please describe.**
There is a type of map composition in Micka, which does not have other definition than CSW metadata record itself. We need to load and display such compositions in the Compositions panel.

**Describe the solution you'd like**
There is a new JSON format Micka can return the records in. The only difference compared to the currently used request is the added url parameter `template=report-layman`. The request returns identical JSON data as up until now, but there is a new element operatesOn, which contains links to the referenced map services. Those services should be loaded in the map.
The CSW composition type can be distinguished by the parameter serviceType=CSW in the json response.

**Additional context**
Sample request (there is one CSW composition in the response):
https://hub.lesprojekt.cz/micka/csw/?request=GetRecords&query=type%3D%27application%27%20AND%20AnyText%20like%20%27*pozemko*%27&format=text/json&MaxRecords=10&StartPosition=&sortby=&language=eng&template=report-layman

**Comment by DailisLangovskis** [comment]
I tried adding -> `&template=report-layman` to Micka request url in https://github.com/hslayers/hslayers-ng/blob/develop/projects/hslayers/src/components/compositions/endpoints/compositions-micka.service.ts#L84, and I got this response ->
Records + 
```

<meta charset="utf-8">
<meta name="robots" content="noindex">
<title>Server Error</title>

<style>
	#error-body { background: white; width: 500px; margin: 70px auto; padding: 10px 20px }
	#error-body h1 { font: bold 47px/1.5 sans-serif; background: none; color: #333; margin: .6em 0 }
	#error-body p { font: 21px/1.5 Georgia,serif; background: none; color: #333; margin: 1.5em 0 }
	#error-body small { font-size: 70%; color: gray }
</style>

<div id="error-body">
    <h1>Server Error</h1>
    <p>We're sorry! The server encountered an internal error and
    was unable to complete your request. Please try again later.</p>
    <p><small>error 500</small></p>
</div>
```

**Comment by FilipLeitner** [comment]
Yup, a bit more need to be changed. 
![image](https://user-images.githubusercontent.com/44566616/161528575-16daffba-c358-4b67-9227-e2e00d15f8b6.png)
