### ISSUE TITLE
VectorLayers should be displayed in Legend too

### ISSUE THREAD

**Issue by DailisLangovskis** [hslayers/hslayers-ng#284]
Legend should dynamically generate image from layers style using layer.getStyle()

**Comment by raitisbe** [comment]
If layer style contains fill, then draw a box (div) filled with that color. If it contains also stroke style, then draw a box around that div. If just stroke is provided, but not fill, then draw a line (just one border of div element). Also icon (point styles) needs to be displayed in legend.

**Comment by raitisbe** [comment]
Time: 2.5h

**Comment by raitisbe** [comment]
Refs https://github.com/hslayers/hslayers-ng/pull/303
