### ISSUE TITLE
Enhanced CSW composition loading

### ISSUE THREAD

**Issue by FilipLeitner** [hslayers/hslayers-ng#2873]
# Feature Request

**Is your feature request related to a problem? Please describe.**

Basic loading of CSW type compositions  done in #2836 is not suitable for all services.
Problem lies within the form of how such a composition define its content - operatesOn parameter often comprise of service endpoint only e.g. wihtout specific layers. This in some cases results in hundreds of layers being added at once (even though we are requesting only the first queriable level of layers)

**Describe the solution you'd like**

Simillarly to arcgis, before loading the content we shall open a modal window where user would be able to select layers he wants to add from the service(s). In case no layers are checked we would create layer with sublayers.

**Comment by fzadrazil** [comment]
I have tried to create a Micka composition with WMS, ArcGIS and Layman layer/services in the Coupled resources
https://hub.lesprojekt.cz/micka/record/basic/m-c3a30296-3d62-4af4-8a2a-97e3837d590b

Let me know if it works or there are another issues with that.

**Comment by DailisLangovskis** [comment]
@FilipLeitner I suppose this issue is now resolved, am I correct?

**Comment by FilipLeitner** [comment]
Still need to do some tests/work on ArcGIS Server layers so Id keep this open
