### ISSUE TITLE
Remove map content when loading composition

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#2875]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, when a composition is loaded the map content defined in the app config still remains in the map no matter what option do I choose in the "Overwrite existing map" dialog (merge composition, continue). In case "Continue" is selected, one would expect to get clean map with just the composition content, maybe only the basemap could remain.

**Describe the solution you'd like**
Clean the map content when loading map composition and "Continue" is selected in the "Overwrite existing map" dialog.

**Comment by raitisbe** [comment]
Basemap should be deleted too if it came from previous composition, otherwise they will start to pile up.
