### ISSUE TITLE
Querying with map swipe

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#2902]
# Bug

**Describe the bug**
When map swipe is active, the info tool is querying layers no matter in which panel they are.

**To Reproduce**
1. Open map and activate map swipe
2. Move some queryable layer to the right swipe panel
3. Identify in the left panel
4. Layer from the right panel is queried

**Expected behavior**
Only layers assigned to the specific map swipe panel should be queried.

**Comment by DailisLangovskis** [comment]
The reason behind this is that swipe control does not remove layer from one panel to other. It is not rendered on the map, but the layer is still there, which is causing this issue. This means, that drawing won't work correctly. Currently I haven't discovered a good solution for this.

We could use the layer swipeSide property to distinguish on which panel it is located and somehow track the Ol map clicked point panel side, by calculating pixels or smth. But this sounds more like a workaround, not a good solution, and would only resolve querying not drawing.

Open to ideas now.

**Comment by fzadrazil** [comment]
I don't think there is a better solution than to detect in which panel the pointer is and then setting the specific layer/s as an input for the query operation.
