### ISSUE TITLE
Wagtail: LayerManager extra button inactive

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2922]
# Bug

**Describe the bug**
In Wagtail integrated apps, the extra hamburger menu in LayerManager won't show.

**To Reproduce**
1. Go to https://hub4everybody.lesprojekt.cz/map-demo/
2. In LayerManager, click on the hamburger extra menu
3. See nothing happening

**Expected behavior**
The menu shows as usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/5598693/164241616-4b02cf64-b71f-44a5-a9bb-f5779f7e2ee8.png)
![image](https://user-images.githubusercontent.com/5598693/164242245-f1059555-8e92-4dae-adc0-615212bae25d.png)

**Additional context**
From the inspector, it looks like the code is present, but the dropdown-menu is still invisible. I suspect a conflicting CSS styling.

**Comment by fzadrazil** [comment]
The issue is caused by missing Popper. I just don't know why it is missing.

![image](https://user-images.githubusercontent.com/48727502/164459157-48408294-67a6-422a-94f1-e2959b0a5bf9.png)

**Comment by raitisbe** [comment]
The global jQuery from the cms takes over the operating dropdownmenus and the popper is missing there. Seems that execution doesn't even get to the ngBootstrap where poper should be present. 
The result should be that "show"  class gets added tbesides "dropdown-menu"  class

**Comment by fzadrazil** [comment]
We could remove jQuery included from the CodeRed by adding this code to /website/coderedcms/pages/base.html

```
{% block required_scripts %}
{% endblock %}
```

That will override the default block which does the actual import. The issue is it breaks dropdowns in CodeRed then :-)

**Comment by raitisbe** [comment]
https://github.com/hslayers/hslayers-ng/pull/2945/commits/7ef4991c18c55939a25de18b93e308c720b00edc Solves it
