### ISSUE TITLE
Wagtail: Translations not loaded in STYLER panel

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2924]
# Bug

**Describe the bug**
In a Wagtail-integrated app, the translations won't load in some parts of the Styler panel, although they are loaded properly in other parts of the app.

**To Reproduce**
1. Go to https://hub4everybody.lesprojekt.cz/map-demo/
2. Add some vector layer
3. In LayerManager, click on 'Style layer'
4. Add some rule and some symbolizer
5. See the source strings instead of the i18n ones

**Expected behavior**
The strings shall be translated as in the other parts of the app

**Screenshots**
![image](https://user-images.githubusercontent.com/5598693/164244051-868f833c-a893-44b4-99a0-c970b9ca28dd.png)

**Additional context**
none

**Comment by jmacura** [comment]
P.S. There are more places where translations are not loaded properly. I suspect the recent changes related to multiple-maps are to blame.
![image](https://user-images.githubusercontent.com/5598693/164314785-928599e7-51d9-46db-87f4-8ad8420a3743.png)
![image](https://user-images.githubusercontent.com/5598693/164314828-45d8b2c4-b36d-43e1-bd65-9041ec5c0634.png)

**Comment by jmacura** [comment]
But it loads fine on localhost, so Wagtail must play some role in this bug.
![image](https://user-images.githubusercontent.com/5598693/164318679-897e7dfc-6e16-4073-8443-5697554f22d1.png)

**Comment by DailisLangovskis** [comment]
@jmacura Well I did notice that styler symbolizers are the few components that does not provide @Input() app = 'default';
That would mean, app is undefined for the translateHs. Just a thought!

**Comment by DailisLangovskis** [comment]
If this brach helps -> [fixBrach](https://github.com/hslayers/hslayers-ng/tree/test-fix-translations), we can merge it.

**Comment by jmacura** [comment]
Another place
![image](https://user-images.githubusercontent.com/5598693/164699509-548400e4-b640-45df-8b4a-94c09e500b32.png)

**Comment by jmacura** [comment]
And "share map"
![image](https://user-images.githubusercontent.com/5598693/164700142-b0ccea1e-aa69-4d5d-ab85-451699bce1b1.png)
