### ISSUE TITLE
Broken translation in add-data panel

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2931]
# Bug

**Describe the bug**
The string 'addSld' won't load its translation form

**To Reproduce**
1. Go to 'Datasources'
2. Add some data from file, like SHP
4. See 'addSld' instead of i18n string

**Expected behavior**
Shall be displayed as translated

**Screenshots**
![image](https://user-images.githubusercontent.com/5598693/164339549-46568170-c42c-48da-9c74-5fe8b70de0c0.png)

**Additional context**
none

**Comment by DailisLangovskis** [comment]
@jmacura I presume this is also only happening for Wagtail?

**Comment by jmacura** [comment]
@DailisLangovskis true, it is only in Wagtail too.
