### ISSUE TITLE
mapExtentChanges subject returns undefined

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2951]
# Bug

**Describe the bug**
In the HsEventBusService, the mapExtentChanges subject is defined as
`mapExtentChanges: Subject<{e; app: string}> = new Subject();`
while the documentation says
_Fires with two parameters: map element and new calculated extent_
and in reality, when subscribed, this is what I receive instead
![image](https://user-images.githubusercontent.com/5598693/165266034-500a94da-3719-43ce-b283-95f9d764d96a.png)

**To Reproduce**
1. Subscribe to HsEventBusService.mapExtentChanges subject

**Expected behavior**
Concise behaviour. Definitely not `undefined` as an observable value

**Screenshots**
see above

**Additional context**
none

**Comment by raitisbe** [comment]
yes, tsDocs will have to be changed
