### ISSUE TITLE
Additional panels break panel order

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#2986]
# Bug

**Describe the bug**
After some recent update, the most important (first in the list) panels are hidden under the "Additional panels" button, instead of the least important (last in the list).

**To Reproduce**
1. Go to localhost:4200
2. Reduce the map window
3. See LayerManager and other important panels hidden under the "Additional panels" option

**Expected behavior**
The last panels hidden under the "Additional panels" option

**Screenshots**
![image](https://user-images.githubusercontent.com/5598693/167039429-da366d99-b385-4025-a986-1830ba5f9a76.png)

**Additional context**
At first I thought it relates only to Firefox, but tested both in latest Firefox and Edge.

**Comment by jmacura** [comment]
Might be solved by  #2983 ?

**Comment by raitisbe** [comment]
Yes
