### ISSUE TITLE
Identify behavior

### ISSUE THREAD

**Issue by wohnout** [hslayers/hslayers-ng#30]
At http://otn-dev.intrasoft-intl.com/explore-maps?hs_x=1606238.490305179&hs_y=6460289.967589872&hs_z=16&hs_panel=info&visible_layers=Base%20layer%3BAutomaty%3BCyklisticke%20trasy

When I click somewhere at the map where is no feature to identify, nothing happens. Expected behavior: Show Info panel with coordinates.
When I click on the feature, Info panel is shown with desired information. OK
When I click somewhere at the map again, the coordinates are redrawn, but information from last identified feature is still shown. It should be erased.

**Comment by raitisbe** [comment]
The info panel will be shown only if certain panels are open if (['layermanager', '', 'permalink'].indexOf(Core.mainpanel) >= 0) Core.setMainPanel("info");
 (defined in list at the bottom of query.js)
