### ISSUE TITLE
Don't use native prompt message in colormap styler

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#3025]
# Feature Request

**Is your feature request related to a problem? Please describe.**
In the new colorMap styler option, some values are required from user via a "prompt" interface. It is ugly, unsafe and user-unfriendly. User has to enter three values one by one. The input can not be checked on-the-fly and can be even cancelled unsafely, creating an invalid colorMap, see screenshot.
![image](https://user-images.githubusercontent.com/5598693/168626604-6870cdfb-cbfd-42aa-ac3d-e88cd694f189.png)

**Describe the solution you'd like**
A modal dialog window with an option to fill in the three required values in the three rows. Also an input check can be performed, in contrary to the unsafe prompt input.

**Describe alternatives you've considered**
none

**Additional context**
![image](https://user-images.githubusercontent.com/5598693/168625836-a521d6f4-a572-4e7c-bcc2-8f73da0946dd.png)
![image](https://user-images.githubusercontent.com/5598693/168625871-a497c8df-ae3d-4c38-afea-cc28bf16cd8a.png)
![image](https://user-images.githubusercontent.com/5598693/168625958-51cbf8d6-cf47-4d9d-ab38-b49e684bcd2e.png)

**Comment by jmacura** [comment]
Another useful enhancement to this dialog would be a selection from attributes in a dropdown, instead of writing it down manually. The same goes for min and max values, which can be pre-filled.

**Comment by raitisbe** [comment]
I think for minor not often done tasks it is ok to have native prompt. Also the min max should have been prefilled. Maybe the attribute name was invalid or no features existed.

**Comment by jmacura** [comment]
> I think for minor not often done tasks it is ok to have native prompt. Also the min max should have been prefilled. Maybe the attribute name was invalid or no features existed.

The designer inside me disagrees. But of course, it's a matter of efforts one really wants to invest into it...

**Comment by raitisbe** [comment]
I will make something nicer
