### ISSUE TITLE
Hide Name field when saving map or layer to Layman

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#3028]
# Feature Request

We are currently displaying title and name fields for maps and layers when saving to Layman. That is strange for users who are often wondering what is the difference. I would keep only "title" and use it also as "name". Layman should make a valid layer/map name from it when posted.

**Comment by jmacura** [comment]
Or the "name" param could be moved under the "advanced settings".

**Comment by fzadrazil** [comment]
It could be that way, but the name is actually not important for the user at all. It only shows in the url of the published layer or map.
