### ISSUE TITLE
Set permissions on existing maps and layers

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#3091]
# Feature Request

**Is your feature request related to a problem? Please describe.**
It is currently only possible to set layer or map permissions when creating it. Should be allowed to do so also on existing layers and maps.

**Describe the solution you'd like**
New button "Set permissions" should be added to the layer/map panel if the current user has the right to do so (similar to the Delete button). The same permissions panel could then be used as we have when creating new one.

![image](https://user-images.githubusercontent.com/48727502/171859933-ed2a6be2-57d4-4b3c-8fc7-dc506b870849.png)

**Comment by DailisLangovskis** [comment]
Just wanted to give an update, that this feature is almost ready for PR, just some issue resolving and refactoring for better readability. :)
