### ISSUE TITLE
Saving to status manager - Failed

### ISSUE THREAD

**Issue by PavelHajek** [hslayers/hslayers-ng#31]
I visualized 3 datasets - type of point, line and polygon, changed its cartographioc representation and I wanted to save the map as a composition, which failed (see the enclosed figure for the description)

The data has around 1MB of the size.

![image](https://cloud.githubusercontent.com/assets/17336075/13176491/09e40ad6-d713-11e5-8552-fafdbb50e404.png)

**Comment by PavelHajek** [comment]
After not saving the largest file, the saving went well. But anyway, my composition called Prague Thematic Map (eventhough i checked Make Public possibility) is not available neither within the list of composition defined by the extend nor within Only mine ones.

**Comment by wohnout** [comment]
Fixed in new version
