### ISSUE TITLE
Switching from 2D to 3D generates an error.

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#313]
When switching from 3D to 2D and back again, Cesium generates an error

An error occurred while rendering. Rendering has stopped.
RangeError: Invalid array length
RangeError: Invalid array length
    at w (https://ng.hslayers.org/examples/3d-lbc/node_modules/cesium/Build/Cesium/Cesium.js:519:30797)

**Comment by kcharvat** [comment]
Raitis, will be good to solve this before 15th of October, we need this demonstrate on action organized by Liberec
