### ISSUE TITLE
Absolute referencing of catalogues in app.js

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#314]
Local server name is automatically added to the URLs of external catalogues (Compositions catalogue, Status Manager), see https://github.com/hslayers/hslayers-ng/blob/7a85f6764522378c76aea64e4a350dc8f15ae19e/app.js.template#L127-L128

These catalogues can be located on another server. The local host name should not be added when the absolute URL is specified.

**Comment by raitisbe** [comment]
If you specify absolute url with http://.... in front then it should work. Url prefixing for ajax is done by browser and is out of our hands. Didnt want to included hardcoded server hostnames in template.

**Comment by bvj** [comment]
![image](https://user-images.githubusercontent.com/8994271/65863508-880e6d80-e370-11e9-8a3f-5ee0af62159e.png)

![image](https://user-images.githubusercontent.com/8994271/65863556-9bb9d400-e370-11e9-9151-d99a58536f8f.png)

**Comment by bvj** [comment]
in app.js is:
```
'catalogue_url': "https://atlas.kraj-lbc.cz/php/metadata/csw/",
    'compositions_catalogue_url': "https://atlas.kraj-lbc.cz/php/metadata/csw",
    status_manager_url: 'https://atlas.kraj-lbc.cz/wwwlibs/statusmanager/index.php',
```

**Comment by raitisbe** [comment]
Actually 'catalogue_url',  'compositions_catalogue_url' both are ignored now. You have to do this through "datasources" config option. It can for example
```
{
        title: "Layman",
        url: `${window.location.protocol}//${window.location.hostname}/layman`,
        user: 'browser',
        type: "layman"
    },
    {
        title: "OTN Hub",
        url: "http://opentnet.eu/php/metadata/csw/",
        language: 'eng',
        type: "micka",
        code_list_url: 'http://opentnet.eu/php/metadata/util/codelists.php?_dc=1440156028103&language=eng&page=1&start=0&limit=25&filter=%5B%7B%22property%22%3A%22label%22%7D%5D'
    }, 
    {
        title: "SuperCAT",
        url: "http://cat.ccss.cz/csw/",
        language: 'eng',
        type: "micka",
        code_list_url: 'http://www.whatstheplan.eu/php/metadata/util/codelists.php?_dc=1440156028103&language=eng&page=1&start=0&limit=25&filter=%5B%7B%22property%22%3A%22label%22%7D%5D'
    }
```
The status manager is still used to save and generate permalink and is broken indeed with absolute urls. I'll fix it
