### ISSUE TITLE
Wrong file size check for uploaded SHP

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#3181]
# Bug

**Describe the bug**
There is a wrong file size check when uploading SHP to Layman. When I select zip file that has around 16 MB, I get the error toast message saying it exceeds the maximum of 20 MB. The same error pops up when a much smaller zip is selected with a slightly different error message, see the screen for details.

**To Reproduce**
1. Go to https://hub.lesprojekt.cz/cs/map3
2. Try to add [AFRICA_countries_borders.zip](https://github.com/hslayers/hslayers-ng/files/9149842/AFRICA_countries_borders.zip)
3. Select SRS

**Expected behavior**
SHP should be uploaded to Layman without any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/48727502/179984393-29f59d74-b98a-4641-b672-169fd2347930.png)

**Comment by FilipLeitner** [comment]
Fixed the code here: 1c4351b1d9bdac00bda81b118932c3d3e92dfd67. 
However, there are things that confuses me a bit. `FILE_UPLOAD_SIZE_LIMIT` was 10mb in code but 20mb in toast message and does it even matter when we can upload in chunks?

**Comment by fzadrazil** [comment]
Thanks for the fix, it works now 👍 

> does it even matter when we can upload in chunks

I think we have agreed on the limit with Dailis as the upload can take some time for large files and there is only the animated gif as a progress indicator. I would vote for canceling the limit, but only if we can show how much is actually uploaded to the user.
