### ISSUE TITLE
svg+xml layers wrong positioning

### ISSUE THREAD

**Issue by bvj** [hslayers/hslayers-ng#319]
Take look on https://ng.hslayers.org/examples/3d-lbc/?hs_panel=layermanager&hs_x=1653451.6089086053&hs_y=6570462.187865352&hs_z=9&lang=cs&visible_layers=Jednoduch%C3%A1%20podkladov%C3%A1%20mapa;Administrativn%C3%AD%20%C4%8Dlen%C4%9Bn%C3%AD;S%C3%ADdla&view=2d

Sídla and Administrativní členění are svg layers - they are wrong positioned on map and when zooming or moving map they are changing position.

**Comment by raitisbe** [comment]
Doean't look to me. Can you post a screenshot?

**Comment by jmacura** [comment]
When I compare "Sídla" or "Administrativní členění" with OSM, it seems OK to me as well. Maybe specific OS/browser issue? I have Firefox 69 @ Win10.

**Comment by bvj** [comment]
sorry, switched layers to png
now is "Sídla" layer in svg and you can see the bug

**Comment by jmacura** [comment]
You are right, I can see the bug clearly now..
Strange fact: while you zoom-in, the layer tend to converge into its correct position... 😕

**Comment by raitisbe** [comment]
Its seems to be a openlayers bug or something in svg file. I tested also with OL6 and still the same result. Would be good to find some working example with wms and svg on the net, but wasnt able to do that too.

**Comment by bvj** [comment]
The Layer seems OK. I tested it in QGis.

**Comment by raitisbe** [comment]
The question is if OL can support it correctly

**Comment by raitisbe** [comment]
Ref https://github.com/openlayers/openlayers/issues/9226
