### ISSUE TITLE
Set HS version in impressum manually

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#3198]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Its not right to include package.json inside src. 

**Describe the solution you'd like**
Version number can be filled manually using the build script https://github.com/hslayers/hslayers-ng/blob/develop/scripts/bump-version.sh

**Additional context**
This problem stems from ng update automatically deleting package.json from src

**Comment by jmacura** [comment]
It also breaks when the tag in git is named "9.3" whereas the code expects "9.3.0" as in the package.json. This creates broken link in the impressum: https://github.com/hslayers/hslayers-ng/releases/tag/9.3.0

**Comment by raitisbe** [comment]
> It also breaks when the tag in git is named "9.3" whereas the code expects "9.3.0" as in the package.json. This creates broken link in the impressum: https://github.com/hslayers/hslayers-ng/releases/tag/9.3.0

In this case I have to be more carefull how Im naming the tags.
