### ISSUE TITLE
panelWidths config breaks panel widths css classes

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#3309]
# Bug

**Describe the bug**
When `panelWidths` app config is specified, it replaces defaults and breaks panel widths CSS classes

**To Reproduce**
1. In HsConfig, define panelWidths object
2. Set only some panel names, omit "default"
3. See what gets rendered

**Expected behavior**
1. Only a subset of panels can be specified in the `panelWidths` config.
2. Invalid panel name does not break the logic.

**Screenshots**
```
panelWidths: {
            datasource_selector: 481,
          },
```
![image](https://user-images.githubusercontent.com/5598693/187555841-0e2efc46-daad-41dc-9127-82cb37d0d46a.png)
![image](https://user-images.githubusercontent.com/5598693/187555876-953d8eca-b6ee-4c22-bc17-95aa00ae289c.png)
![image](https://user-images.githubusercontent.com/5598693/187556006-702a0463-f4e6-4939-bc2b-00fbaa5cdc02.png)

**Additional context**
none

**Comment by raitisbe** [comment]
Thanks for fix, works fine now
