### ISSUE TITLE
Broken i18n strings in Save-map panel

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#3323]
# Bug

**Describe the bug**
Translation strings are not loaded for save-map panel.

**To Reproduce**
1. Go to 'Save current map panel'
2. Click inside 'Name' field (or 'Abstract' or 'Keywords')
3. See the `translateHs` plain interpolation string

**Expected behavior**
Translation shall appear there.

**Screenshots**
![image](https://user-images.githubusercontent.com/5598693/188518170-3977fc47-0063-4a29-8694-615334bdd61f.png)

**Additional context**
Found at https://hub4everybody.lesprojekt.cz/map/
Observed in Firefox 104, not observed in Edge 105

**Comment by DailisLangovskis** [comment]
@jmacura Hey, I just went to H4E to the same panel also logged in, and didn't notice this bug. Could there be something else causing this? Also does the map has ID set, maybe the {app} is undefined at some point and the translation breaks?!?

**Comment by jmacura** [comment]
@DailisLangovskis Good point. Only relevant to Firefox browser. There is literally nothing when I open the form in Edge.
![image](https://user-images.githubusercontent.com/5598693/188722743-0777d09d-3f01-41d1-83de-db36afd8e57b.png)

**Comment by jmacura** [comment]
And I have checked that the map has an ID 'map1' set, so it is neither 'default' nor undefined.

**Comment by raitisbe** [comment]
Missing {{ }} in line `placeholder="'COMMON.name' | translateHs...

**Comment by DailisLangovskis** [comment]
I'd say, that placeholder should be wrapped in [] brackets.

**Comment by raitisbe** [comment]
Than pipe | wouldnt be evalued imho but can try

**Comment by DailisLangovskis** [comment]
@jmacura Can You test if this fixes it now?

**Comment by jmacura** [comment]
@DailisLangovskis It does fix it, indeed. Thanks!

Though I am curious why all these placeholders are empty.. Or is it only me again?
![image](https://user-images.githubusercontent.com/5598693/188731218-83d983e8-5440-4dc4-8dad-c92343847c54.png)

**Comment by DailisLangovskis** [comment]
> @DailisLangovskis It does fix it, indeed. Thanks!
> 
> Though I am curious why all these placeholders are empty.. Or is it only me again? ![image](https://user-images.githubusercontent.com/5598693/188731218-83d983e8-5440-4dc4-8dad-c92343847c54.png)

I guess here is why -> [Issue](https://github.com/twbs/bootstrap/issues/33999)
