### ISSUE TITLE
Initial layer loading

### ISSUE THREAD

**Issue by FilipLeitner** [hslayers/hslayers-ng#3335]
At the initiation of an app, we try to load a layer from 3/4 different sources:

1. box_layers and  default_layers from app config 
https://github.com/hslayers/hslayers-ng/blob/3e9aabb47d428b8d6d6526fd2ddf038c7dcc2958/projects/hslayers/src/components/map/map.service.ts#L517

2.  hs-composition URL parameter or defaultComposition config param
https://github.com/hslayers/hslayers-ng/blob/6a819463c0f17a72ad6937c4f84b8ae2abc782a8/projects/hslayers/src/components/compositions/compositions.service.ts#L87

3. Permalink layers
https://github.com/hslayers/hslayers-ng/blob/6a819463c0f17a72ad6937c4f84b8ae2abc782a8/projects/hslayers/src/components/compositions/compositions.service.ts#L88

Both `tryParseCompositionFromUrlParam `and `parsePermalinkLayers `remove all the layers satisfying this condition
https://github.com/hslayers/hslayers-ng/blob/3e9aabb47d428b8d6d6526fd2ddf038c7dcc2958/projects/hslayers/src/components/map/map.service.ts#L1173-L1177

Many times it might not be necessary to try loading all the layers from 1....at the same time layers from 2. should not be loaded in case permalink is being opened at all.
It would be really beneficial to  clean this up a little bit, imo.

We could probably filter box and default layers by removable param in case permalink or composition is supposed to be loaded.

Feels like a refactor which could have some unexpected results or culprits I am not aware of atm . What do you think?

**Comment by DailisLangovskis** [comment]
@FilipLeitner Well we are only requesting to load layers from param if compositions component gets initialised. I agree that box_layers could be deprecated, if there is no real use case for it, which we already metioned in the tellco, but still was not 100% decided.  As far as the layer removal goes, it was probably intented for the cases when layers got loaded also from local storage, imo.

**Comment by FilipLeitner** [comment]
> Well we are only requesting to load layers from param if compositions component gets initialised, so that seems ok to me.

Sure but still. What I am trying to say is there's no point in loading default_layers  in case you're opening a permalink or defaultComposition param is set. In case you share an app with `defaultComposition` param what happens basically is that 
a) Default layers are added and removed
b) defaultComposition is fetched, parsed, its layers loaded and then removed
c) permalink composition is loaded

>mapService initialises first and we cannot know yet if there will be layers loaded from permalink or not.

Permalink composition is provided via URL, same is true for compositions using hs-composition param. Default composition is a config param so it should be available as well

**Comment by DailisLangovskis** [comment]
> > Well we are only requesting to load layers from param if compositions component gets initialised, so that seems ok to me.
> 
> Sure but still. What I am trying to say is there's no point in loading default_layers in case you're opening a permalink or defaultComposition param is set. In case you share an app with `defaultComposition` param what happens basically is that a) Default layers are added and removed b) defaultComposition is fetched, parsed, its layers loaded and then removed c) permalink composition is loaded
> 
> > mapService initialises first and we cannot know yet if there will be layers loaded from permalink or not.
> 
> Permalink composition is provided via URL, same is true for compositions using hs-composition param. Default composition is a config param so it should be available as well

Thank You for clearing it for me.
