### ISSUE TITLE
Map swipe button is blank (style-less)

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#3395]
# Bug

**Describe the bug**
The map swipe button/rod is displayed as a blank white rectangle instead of its styling. It happens only accidentally. e.g. When clicked, it is fine.

**To Reproduce**
1. Go to map with swipe enabled
2. See error

**Expected behavior**
Swipe button shall always be styled.

**Screenshots**
![image](https://user-images.githubusercontent.com/5598693/192385559-b131f551-76ad-4256-a1cf-cd31e61cb917.png)
![image](https://user-images.githubusercontent.com/5598693/192385698-67e14d0f-9308-4bfa-81f2-8be6e57fbe27.png)

**Additional context**
Tested in Firefox and Edge.

**Comment by DailisLangovskis** [comment]
@jmacura Does this happen in test environment or in wagtail?

**Comment by FilipLeitner** [comment]
Fixed swipe button here #3396. 

Another thing to consider introduced by changes in OL here https://github.com/openlayers/openlayers/pull/13908 is style of the rest of the `ol-control` buttons.

**Comment by jmacura** [comment]
> @jmacura Does this happen in test environment or in wagtail?

The screenshot is from test environment.

**Comment by fzadrazil** [comment]
> Do we want to 'revert' the OL changes and go back to that blueish color for control or adjust our controls?

I am ok with the new color scheme from OL.

**Comment by raitisbe** [comment]
I am too, but in that case we need to align the styles everywhere. Css variables are a good solution in this case. Could you please change the blueish to white @FilipLeitner ?

**Comment by FilipLeitner** [comment]
> I am too, but in that case we need to align the styles everywhere. Css variables are a good solution in this case. Could you please change the blueish to white @FilipLeitner ?

Sure, will do

**Comment by FilipLeitner** [comment]
![image](https://user-images.githubusercontent.com/44566616/192970046-c022b74d-fdec-4fa6-a583-5083c7b0b629.png)

On hover/active background ofcontrols is bootstrap secondary and color white.

![image](https://user-images.githubusercontent.com/44566616/192970299-0b383b14-d3a1-4cbf-b5a7-dc09a98ec5f7.png)


Was also thinking wether we would like map-swipe 'line' to be dark on hover only like this:
![image](https://user-images.githubusercontent.com/44566616/192971018-9619f9b9-de85-416e-ada6-8586ef83f25c.png)

**Comment by DailisLangovskis** [comment]
@FilipLeitner I am not a big fan of the secondary color, I would prefer blue-ish color instead, just my thoughts.

**Comment by fzadrazil** [comment]
> Was also thinking wether we would like map-swipe 'line' to be dark on hover only like this

I would not change the swipe line color on hover.

**Comment by FilipLeitner** [comment]
> I am not a big fan of the secondary color, I would prefer blue-ish color instead, just my thoughts.
Chose secondary because of toolbar, to be consistent.
We can discuss this tomorrow, will be much easier to make an agreement

**Comment by FilipLeitner** [comment]
#3412

**Comment by FilipLeitner** [comment]
#3414
