### ISSUE TITLE
Select type of service when uploading new layer

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#3440]
# Feature Request

**Is your feature request related to a problem? Please describe.**
When I want to upload a new layer to Layman, it gets automatically added to the current map, but without a change to select, whether it will be added as WMS or WFS. It is always added as WFS.

**Describe the solution you'd like**
Add a WMS/WFS selector to the layer upload form in the same manner as if I add existing layer to the map.

**Comment by DailisLangovskis** [comment]
@fzadrazil This is in save-map component? But how would that work exactly? For example, WFS layer is currently loaded on HSLayers and when saving to Layman we specify WMS and it gets converted before uploading
?

**Comment by DailisLangovskis** [comment]
I am probably the only one, but I don't know from where exatcly we upload a new layer to Layman. Is it when creating a new drawing layer?

**Comment by fzadrazil** [comment]
Nope, it is in Datasources panel, File tab. When you select SHP or GeoJSON, there is "Save to database" flag, which means "publish it to Layman". I think @FilipLeitner has implemented that.

**Comment by DailisLangovskis** [comment]
Oh yes, that's right!

František Zadražil ***@***.***> (šajā datumā: trešd., 2022.
g. 12. okt. 11:14) rakstīja:

**Comment by FilipLeitner** [comment]
>It is always added as WFS.
I think SHP is added as WMS while other sources such as GeoJSON result in WFS layer.

**Comment by fzadrazil** [comment]
Well, the main issue is that WFS is added without styling.

**Comment by jmacura** [comment]
Proposed UI mock-up of this feature
![image](https://user-images.githubusercontent.com/5598693/199972762-871c1330-6980-4400-85db-523b0ae9348d.png)

For shapefile, the WMS option will be pre-selected. For other vector files, the WFS option will be pre-selected. Keeping the status quo. Any comments @fzadrazil or anyone?

**Comment by DailisLangovskis** [comment]
Looks good to me!

jmacura ***@***.***> (šajā datumā: piektd., 2022. g. 4. nov.
14:30) rakstīja:

**Comment by fzadrazil** [comment]
> For shapefile, the WMS option will be pre-selected. For other vector files, the WFS option will be pre-selected. Keeping the status quo. Any comments @fzadrazil or anyone?

Agreed. And the proposed GUI looks fine.
