### ISSUE TITLE
Fill symbolizer with graphic fill ignores fill color

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#3444]
# Bug

**Describe the bug**
In Styler, Fill symbolizer allows to specify a graphic fill (markers or icons, as seen on the screenshot) and a fill color at the same time. When I tried that, it seems that the symbolizer ignores the fill color completely and uses some default fill value instead.

**To Reproduce**
1. Go to 'Styler'
2. Click on 'Fill Symbolizer'
3. Click on '+' near the "Graphic Fill"
4. See the fill color change

**Expected behavior**
The fill color is preserved.

**Screenshots**
![image](https://user-images.githubusercontent.com/5598693/195355535-c02c7e62-f790-4798-8c28-dbfb65987541.png)

**Additional context**
none

**Comment by DailisLangovskis** [comment]
I suppose it is not implemented to even do so, but I am not sure. Will investigate till friday!

**Comment by DailisLangovskis** [comment]
@jmacura You have to change the fill and stroke color for graphical fill underneath. Should add mby some borders to distinguish the difference. What do You think?

**Comment by jmacura** [comment]
I am adding two more screenshots to clarify the issue.

![image](https://user-images.githubusercontent.com/5598693/195422978-8c1bdd4e-473e-4ada-9aa9-5d2a3f34d7f5.png)

![image](https://user-images.githubusercontent.com/5598693/195422037-a031d155-9c93-40dd-8a7d-aeaee88a9d6a.png)

**Comment by jmacura** [comment]
Recategorizing this issue as an enhancement per @DailisLangovskis 's point that the Graphic Fill is clearly marked in the GUI with an exclamation mark saying _"Attribute stored in SLD, but currently not visualized correctly"_. So I shall have never expected that it will work out of the box 🙂

**Comment by raitisbe** [comment]
You need to combine two fill symbolizers to have the desired effect:
![image](https://user-images.githubusercontent.com/395514/208119056-22ee91aa-f4d5-4b99-810a-884ba5464dd4.png)
