### ISSUE TITLE
Some ArcGIS services won't load

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#3515]
# Bug

**Describe the bug**
Trying to add this ArcGIS Service by its URL to the map doesn't work. No layers are loaded
https://ags.plzen.eu/arcgis/rest/services/GIS_Historicke/GIS_HIS_Cisarske_otisky/MapServer

**To Reproduce**
1. Go to the Add data panel
2. Select URL > ArcGIS Map Service
3. Insert the mentioned URL and connect to it
4. No layers are loaded and adding to the map is not possible

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by DailisLangovskis** [comment]
@fzadrazil I will look into it in the middle of this week at some point!
