### ISSUE TITLE
Add support to load Shape files

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#354]
Issue #209 is only about a button, so I am opening a new issue. GeoJSON and KML formats are supported out of the box by OpenLayers, but we eventually need to support adding of Shapefiles (SHP) into a map as well.

**Comment by raitisbe** [comment]
https://github.com/calvinmetcalf/shapefile-js This looked like a good option

I have also working code outside hslayers which uses https://github.com/gipong/shp2geojson.js?files=1 but maybe its not the best option. Had some problems loading with attributes and 4 years old.

**Comment by raitisbe** [comment]
Will do it using Layman and not shape file parser on client side.
