### ISSUE TITLE
Add support to load images with world file reference

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#356]
Currently, local raster images can only be loaded by hard-typing their geographical extend. But that can be calculated from the associated world file (like .pgw, etc.) if provided.

**Comment by raitisbe** [comment]
Can you can split this work among yourselves?

**Comment by jmacura** [comment]
TODO:

1. Check if non-linear transformations are supported by @openlayers
2. Check which raster formats are supported by @openlayers
3. Eventually improve the image handling on the @openlayers side
