### ISSUE TITLE
Add support to load GeoTIFF images

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#357]
Along with #356 we also need to support true GeoTIFF files which have georeferencing stored inside the .tif file itself.

**Comment by jmacura** [comment]
Worth the reuse: https://github.com/geotiffjs/geotiff.js
It's license-compatible :-)

**Comment by raitisbe** [comment]
Can you do it?

**Comment by jmacura** [comment]
Will look at it.
