### ISSUE TITLE
Check if geostyler workarounds still needed

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#3677]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Some long standing bugs were fixed in geostyler:

Version 4.1.0
What's Changed
Updates openlayers to v7 and geostyler-style to v7 by [@​KaiVolland](https://github.com/KaiVolland) in [geostyler/geostyler-openlayers-parser#595](https://github-redirect.dependabot.com/geostyler/geostyler-openlayers-parser/pull/595)
fontWeight and fontStyle from textSymbolizer by [@​pragmaeuge](https://github.com/pragmaeuge) in [geostyler/geostyler-openlayers-parser#615](https://github-redirect.dependabot.com/geostyler/geostyler-openlayers-parser/pull/615)
Update geostyler-style by [@​hwbllmnn](https://github.com/hwbllmnn) in [geostyler/geostyler-openlayers-parser#647](https://github-redirect.dependabot.com/geostyler/geostyler-openlayers-parser/pull/647)
fillOpacity support for the markSymbolizer geostyler object by [@​pragmaeuge](https://github.com/pragmaeuge) in [geostyler/geostyler-openlayers-parser#621](https://github-redirect.dependabot.com/geostyler/geostyler-openlayers-parser/pull/621)
Drop support for IconSymbolizer.size by [@​KaiVolland](https://github.com/KaiVolland) in [geostyler/geostyler-openlayers-parser#648](https://github-redirect.dependabot.com/geostyler/geostyler-openlayers-parser/pull/648)
Remove graphicFill from unsupportedProperties by [@​KaiVolland](https://github.com/KaiVolland) in [geostyler/geostyler-openlayers-parser#656](https://github-redirect.dependabot.com/geostyler/geostyler-openlayers-parser/pull/656)
Updates dependencies (ol to v7.2) and readd size parsing by [@​KaiVolland](https://github.com/KaiVolland) in [geostyler/geostyler-openlayers-parser#657](https://github-redirect.dependabot.com/geostyler/geostyler-openlayers-parser/pull/657)

**Describe the solution you'd like**

Check if our workarounds are still needed. Some which come to mind are fillOpacity for MarkSymbolizer and tooltips about attributes not suported

**Comment by FilipLeitner** [comment]
Drop support for IconSymbolizer.size 
- ``The upcoming ol release will include width and height for the ol/style/Icon `` . <-- already released... ``so we will be able to implement it correctly with the next ol version:`` <--not yet

**Comment by FilipLeitner** [comment]
> Drop support for IconSymbolizer.size
> 
> * `The upcoming ol release will include width and height for the ol/style/Icon ` . <-- already released... `so we will be able to implement it correctly with the next ol version:` <--not yet

Size still used in geostyler-sld-parser v 5.2.0 https://github.com/geostyler/geostyler-sld-parser/blob/794ac90502be5696a7c2f44ad8da93080a51230d/src/SldStyleParser.ts#L998
