### ISSUE TITLE
Attributes in hover cards

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#375]
When hovering over a feature in the map, a hover card should pop-up with the (possibly trimmed) attribute table.

Configurable:
- if the pop-up card should appear on hover or on click (substituting the attribute table in the side panel).
- if all the attributes should appear in the card or just some subset of them (array of attr names)

Needed for project-enabling and P4A website.

**Comment by raitisbe** [comment]
Time: 2h
