### ISSUE TITLE
Remove overwritten layer from Layer manager

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#3756]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Steps to reproduce
* Add layer from Layman or publish a new one
* Publish the same layer once more (eg. with different symbology) and overwrite the original
* The layer gets added to the layer manager automatically
* We now have two different versions of the same layer in the map

**Describe the solution you'd like**
Once a layer is in the map and is overwritten, replace the original layer with the new published one.

**Comment by FilipLeitner** [comment]
Created a PR. Changed the default behaviour of adding a layer so we always check whether the layer already exists or not. 

Not 100% sure we want it that way so I rather pointing that out.
