### ISSUE TITLE
Zoom to extent doesn't work for geojsons loaded from file

### ISSUE THREAD

**Issue by FilipLeitner** [hslayers/hslayers-ng#3764]
# Bug

**Describe the bug**
Zoom to extent doesn't work for geojsons loaded from file

EDIT: geoJSONs uploaded to Layman and then synced

**Expected behavior**
Should zoom to extent

**Comment by FilipLeitner** [comment]
@fzadrazil  could you please provide the geojson you encountered the issue with? Tested few times and could not replicate

**Comment by fzadrazil** [comment]
Sure, it is this one [Senegal.zip](https://github.com/hslayers/hslayers-ng/files/10613884/Senegal.zip)

**Comment by FilipLeitner** [comment]
Strange, It works. On both locale and hub4everybody. Can you please give it a try?

**Comment by fzadrazil** [comment]
Doesn't work only when logged in and uploading to Layman.
