### ISSUE TITLE
Convert hslayers-server from CommonJS to ES module

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#3816]
# Feature Request

**Is your feature request related to a problem? Please describe.**
hslayers-server uses CommonJS syntax, some packages like "got" already moved to a "pure" ES modules standard.

**Describe the solution you'd like**
Refactor files from CJS to ESM

**Describe alternatives you've considered**
Leave it be until it breaks on some future Node version.

**Additional context**
Mixing CJS and ESM modules requires hacks like dynamic imports (see e.g. #3815 )

**Comment by fzadrazil** [comment]
Solve #3858 while refactoring the server.
