### ISSUE TITLE
Broken share composition option

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#3854]
# Bug

**Describe the bug**
There is a share option at each composition in the compositions list. This feature generates a URL and then shortens it via TinyURL service. This service, however, seem to be blocking our URLs due to the way they are formed.

```
URL listed in blocklist

The TinyURL (2lldjdsf) you visited is listed in one or more of several URI reputation databases we use ( [SURBL](http://www.surbl.org/), [SpamHaus DBL](https://www.spamhaus.org/dbl/), [URIBL](https://uribl.com/), [Google Safe Browsing](https://safebrowsing.google.com/), our internal blacklist, and others). The reason code given by the blocklist is:

    Quad9 listed as Malware

This TinyURL went to: https://hub4everybody.com/share/?request=socialshare&id=5dbfc8cc-07bb-49cf-ab2c-deb63a0b26b6

TinyURL has a strict no abuse policy and we apologize for the intrusion this user has caused you. Such violations of our terms of use include:

    Spam - Unsolicited Bulk E-mail
    Fraud or Money Making scams
    Malware
    or any other use that is illegal.

If you received spam, please note that TinyURL did not send this spam and we do not operate any email lists. We can not remove you from spammer's database as we have no association with spammers, but instead we recommend you use spam filtering software.

About TinyURL

TinyURL.com is a free URL redirection service that allows you to make a long URL into a more manageable tiny URL. To learn more about TinyURL, please visit our homepage: https://tinyurl.com/
```

**To Reproduce**
1. Go to 'Compositions' panel
2. Click on any composition record
3. Click on 'Share'
4. Copy the URL from the dialog
5. Try to open the URL
6. See error

**Expected behavior**
The URL shall open something meaningful.

**Screenshots**
![image](https://user-images.githubusercontent.com/5598693/221031202-38d9339f-0465-4bd4-9858-f64b37dcd812.png)
![image](https://user-images.githubusercontent.com/5598693/221031511-e0d4c32e-8758-44fa-8727-9f2cf8144f64.png)

**Additional context**
none

**Comment by fzadrazil** [comment]
I don't have this kind of issue. The link opens in a normal way with the selected composition. Tried in Chrome and Firefox.

**Comment by FilipLeitner** [comment]
Tried hub4everybody and local build works on both

**Comment by jmacura** [comment]
Cannot replicate now...
