### ISSUE TITLE
Fix deprecation warnings with RxJS library

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#3894]
# Bug

**Describe the bug**
Some methods and usage patterns are deprecated in RxJS 7 and will be dropped in RxJS 8. So let's get ready for a future.

**Additional context**
RxJS 8 is nowhere near yet, but better keep this in mind.

**Comment by FilipLeitner** [comment]
This seems to be resolved as all forkJoins are refactored. Other than that we use just basic operators or types which are not being deprecated or changed

**Comment by jmacura** [comment]
> This seems to be resolved as all forkJoins are refactored. Other than that we use just basic operators or types which are not being deprecated or changed

Right. This issue was related to `forkJoin()` and `toPromise()` patterns. I can't find any deprecated usage any more so closing this issue 👍 

btw, there are some first alpha releases of rxjs 8 but still a long road ahead: https://github.com/ReactiveX/rxjs/issues/6367
