### ISSUE TITLE
Composition loading fails with silent error on server error

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#3934]
# Bug

**Describe the bug**
When Layman server returns error, the composition loading fails with a silent error in the console.

**To Reproduce**
1. Go to 'Compositions' panel and do not log in to catalogue.
2. Click on any composition
3. Select 'Open' and 'Continue'
5. See error in console

**Expected behavior**
Loading error displayed to the end-user.
Meaningful error message for non-authorized access.

**Screenshots**
![image](https://user-images.githubusercontent.com/5598693/227189701-e09fd477-115c-471b-9193-0fc4e478fa38.png)

**Additional context**
Actual error in this case was with user not logged in.
```
{
  "code": 32,
  "detail": "Introspection endpoint claims that access token is not active or it's not Bearer token.",
  "message": "Unsuccessful OAuth2 authentication.",
  "sub_code": 9
}
```

**Comment by jmacura** [comment]
Check the conditions when the error happens. Can it be related to the login time-out?

**Comment by jmacura** [comment]
Encountered a very similar error today, but this time with a dataset.

# Bug

**Describe the bug**
Can't add layer from data catalogue (Layman) when not logged in (first time opened localhost today). Seems like Layman is incorrectly getting a login token but it is invalid.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Datasources'
2. Do *NOT* log in
3. Try to add some layer
4. See error

**Expected behavior**
No matter the login state, this error shall not happen.

**Screenshots**
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/5ad27680-d210-45a5-a412-523f6cc74aac)


**Additional context**
The request says "403 FORBIDDEN"
Again, the actual problem seems to be the fact that
`"Introspection endpoint claims that access token is not active or it's not Bearer token."`

**Comment by fzadrazil** [comment]
In case we need Layman there will always be layman-proxy used. That will eliminate the above error.
