### ISSUE TITLE
WMS query broken in Firefox

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#4036]
# Bug

**Describe the bug**
Query point via WMS layer does not work in Firefox.
The request to WMS server is send correctly:
```https://hub4everybody.com/geoserver/franta_wms/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=spoi_italy&LAYERS=spoi_italy&INFO_FORMAT=application%2Fvnd.ogc.gml&feature_count=1&I=79&J=173&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=1023644.6827950813%2C5693029.866679927%2C1024867.6752476441%2C5694252.85913249``` (Edge)
```https://hub4everybody.com/geoserver/franta_wms/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image/png&TRANSPARENT=true&QUERY_LAYERS=spoi_italy&LAYERS=spoi_italy&INFO_FORMAT=application/vnd.ogc.gml&feature_count=1&I=6&J=144&WIDTH=256&HEIGHT=256&CRS=EPSG:3857&STYLES=&BBOX=1023950.4309082218,5695017.229415342,1024103.3049647921,5695170.103471912``` (Firefox)

While Edge correctly receives a XML document:
```
<?xml version="1.0" encoding="UTF-8"?><wfs:FeatureCollection xmlns="http://www.opengis.net/wfs" xmlns:wfs="http://www.opengis.net/wfs" xmlns:franta_wms="http://franta_wms" xmlns:gml="http://www.opengis.net/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs https://hub4everybody.com/geoserver/schemas/wfs/1.0.0/WFS-basic.xsd http://franta_wms https://hub4everybody.com/geoserver/franta_wms/wfs?service=WFS&amp;version=1.0.0&amp;request=DescribeFeatureType&amp;typeName=franta_wms%3Aspoi_italy">
  <gml:boundedBy>
    <gml:Box srsName="http://www.opengis.net/gml/srs/epsg.xml#3857">
      <gml:coordinates xmlns:gml="http://www.opengis.net/gml" decimal="." cs="," ts=" ">1024018.8676,5693426.8733 1024018.8676,5693426.8733</gml:coordinates>
    </gml:Box>
  </gml:boundedBy>
  <gml:featureMember>
    <franta_wms:spoi_italy fid="spoi_italy.16816">
      <gml:boundedBy>
        <gml:Box srsName="http://www.opengis.net/gml/srs/epsg.xml#3857">
          <gml:coordinates xmlns:gml="http://www.opengis.net/gml" decimal="." cs="," ts=" ">1024018.8676,5693426.8733 1024018.8676,5693426.8733</gml:coordinates>
        </gml:Box>
      </gml:boundedBy>
      <franta_wms:id>http://www.sdi4apps.eu/poi/#OSM_2516079384</franta_wms:id>
      <franta_wms:http://www.w3.org/1999/02/22_rdf_syntax_ns_type>http://gis.zcu.cz/SPOI/Ontology#restaurant</franta_wms:http://www.w3.org/1999/02/22_rdf_syntax_ns_type>
      <franta_wms:wkb_geometry>
        <gml:Point srsName="http://www.opengis.net/gml/srs/epsg.xml#3857">
          <gml:coordinates xmlns:gml="http://www.opengis.net/gml" decimal="." cs="," ts=" ">1024018.8676,5693426.8733</gml:coordinates>
        </gml:Point>
      </franta_wms:wkb_geometry>
    </franta_wms:spoi_italy>
  </gml:featureMember>
</wfs:FeatureCollection>
```
Firefox receives base64 encoded string of the same:
`PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48d2ZzOkZlYXR1cmVDb2xsZWN0aW9uIHhtbG5zPSJodHRwOi8vd3d3Lm9wZW5naXMubmV0L3dmcyIgeG1sbnM6d2ZzPSJodHRwOi8vd3d3Lm9wZW5naXMubmV0L3dmcyIgeG1sbnM6ZnJhbnRhX3dtcz0iaHR0cDovL2ZyYW50YV93bXMiIHhtbG5zOmdtbD0iaHR0cDovL3d3dy5vcGVuZ2lzLm5ldC9nbWwiIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhzaTpzY2hlbWFMb2NhdGlvbj0iaHR0cDovL3d3dy5vcGVuZ2lzLm5ldC93ZnMgaHR0cHM6Ly9odWI0ZXZlcnlib2R5LmNvbS9nZW9zZXJ2ZXIvc2NoZW1hcy93ZnMvMS4wLjAvV0ZTLWJhc2ljLnhzZCBodHRwOi8vZnJhbnRhX3dtcyBodHRwczovL2h1YjRldmVyeWJvZHkuY29tL2dlb3NlcnZlci9mcmFudGFfd21zL3dmcz9zZXJ2aWNlPVdGUyZhbXA7dmVyc2lvbj0xLjAuMCZhbXA7cmVxdWVzdD1EZXNjcmliZUZlYXR1cmVUeXBlJmFtcDt0eXBlTmFtZT1mcmFudGFfd21zJTNBc3BvaV9pdGFseSI+CiAgPGdtbDpib3VuZGVkQnk+CiAgICA8Z21sOkJveCBzcnNOYW1lPSJodHRwOi8vd3d3Lm9wZW5naXMubmV0L2dtbC9zcnMvZXBzZy54bWwjMzg1NyI+CiAgICAgIDxnbWw6Y29vcmRpbmF0ZXMgeG1sbnM6Z21sPSJodHRwOi8vd3d3Lm9wZW5naXMubmV0L2dtbCIgZGVjaW1hbD0iLiIgY3M9IiwiIHRzPSIgIj4xMDIzOTU0Ljk3MDIsNTY5NTA4NC43NTAyIDEwMjM5NTQuOTcwMiw1Njk1MDg0Ljc1MDI8L2dtbDpjb29yZGluYXRlcz4KICAgIDwvZ21sOkJveD4KICA8L2dtbDpib3VuZGVkQnk+CiAgPGdtbDpmZWF0dXJlTWVtYmVyPgogICAgPGZyYW50YV93bXM6c3BvaV9pdGFseSBmaWQ9InNwb2lfaXRhbHkuMTg2ODYiPgogICAgICA8Z21sOmJvdW5kZWRCeT4KICAgICAgICA8Z21sOkJveCBzcnNOYW1lPSJodHRwOi8vd3d3Lm9wZW5naXMubmV0L2dtbC9zcnMvZXBzZy54bWwjMzg1NyI+CiAgICAgICAgICA8Z21sOmNvb3JkaW5hdGVzIHhtbG5zOmdtbD0iaHR0cDovL3d3dy5vcGVuZ2lzLm5ldC9nbWwiIGRlY2ltYWw9Ii4iIGNzPSIsIiB0cz0iICI+MTAyMzk1NC45NzAyLDU2OTUwODQuNzUwMiAxMDIzOTU0Ljk3MDIsNTY5NTA4NC43NTAyPC9nbWw6Y29vcmRpbmF0ZXM+CiAgICAgICAgPC9nbWw6Qm94PgogICAgICA8L2dtbDpib3VuZGVkQnk+CiAgICAgIDxmcmFudGFfd21zOmlkPmh0dHA6Ly93d3cuc2RpNGFwcHMuZXUvcG9pLyNPU01fMzAxNzY1Mzc4NTwvZnJhbnRhX3dtczppZD4KICAgICAgPGZyYW50YV93bXM6aHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMl9yZGZfc3ludGF4X25zX3R5cGU+aHR0cDovL2dpcy56Y3UuY3ovU1BPSS9PbnRvbG9neSNyZXN0YXVyYW50PC9mcmFudGFfd21zOmh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjJfcmRmX3N5bnRheF9uc190eXBlPgogICAgICA8ZnJhbnRhX3dtczp3a2JfZ2VvbWV0cnk+CiAgICAgICAgPGdtbDpQb2ludCBzcnNOYW1lPSJodHRwOi8vd3d3Lm9wZW5naXMubmV0L2dtbC9zcnMvZXBzZy54bWwjMzg1NyI+CiAgICAgICAgICA8Z21sOmNvb3JkaW5hdGVzIHhtbG5zOmdtbD0iaHR0cDovL3d3dy5vcGVuZ2lzLm5ldC9nbWwiIGRlY2ltYWw9Ii4iIGNzPSIsIiB0cz0iICI+MTAyMzk1NC45NzAyLDU2OTUwODQuNzUwMjwvZ21sOmNvb3JkaW5hdGVzPgogICAgICAgIDwvZ21sOlBvaW50PgogICAgICA8L2ZyYW50YV93bXM6d2tiX2dlb21ldHJ5PgogICAgPC9mcmFudGFfd21zOnNwb2lfaXRhbHk+CiAgPC9nbWw6ZmVhdHVyZU1lbWJlcj4KPC93ZnM6RmVhdHVyZUNvbGxlY3Rpb24+Cg==`
When decoded it is:
```
<?xml version="1.0" encoding="UTF-8"?><wfs:FeatureCollection xmlns="http://www.opengis.net/wfs" xmlns:wfs="http://www.opengis.net/wfs" xmlns:franta_wms="http://franta_wms" xmlns:gml="http://www.opengis.net/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs https://hub4everybody.com/geoserver/schemas/wfs/1.0.0/WFS-basic.xsd http://franta_wms https://hub4everybody.com/geoserver/franta_wms/wfs?service=WFS&amp;version=1.0.0&amp;request=DescribeFeatureType&amp;typeName=franta_wms%3Aspoi_italy">
  <gml:boundedBy>
    <gml:Box srsName="http://www.opengis.net/gml/srs/epsg.xml#3857">
      <gml:coordinates xmlns:gml="http://www.opengis.net/gml" decimal="." cs="," ts=" ">1023954.9702,5695084.7502 1023954.9702,5695084.7502</gml:coordinates>
    </gml:Box>
  </gml:boundedBy>
  <gml:featureMember>
    <franta_wms:spoi_italy fid="spoi_italy.18686">
      <gml:boundedBy>
        <gml:Box srsName="http://www.opengis.net/gml/srs/epsg.xml#3857">
          <gml:coordinates xmlns:gml="http://www.opengis.net/gml" decimal="." cs="," ts=" ">1023954.9702,5695084.7502 1023954.9702,5695084.7502</gml:coordinates>
        </gml:Box>
      </gml:boundedBy>
      <franta_wms:id>http://www.sdi4apps.eu/poi/#OSM_3017653785</franta_wms:id>
      <franta_wms:http://www.w3.org/1999/02/22_rdf_syntax_ns_type>http://gis.zcu.cz/SPOI/Ontology#restaurant</franta_wms:http://www.w3.org/1999/02/22_rdf_syntax_ns_type>
      <franta_wms:wkb_geometry>
        <gml:Point srsName="http://www.opengis.net/gml/srs/epsg.xml#3857">
          <gml:coordinates xmlns:gml="http://www.opengis.net/gml" decimal="." cs="," ts=" ">1023954.9702,5695084.7502</gml:coordinates>
        </gml:Point>
      </franta_wms:wkb_geometry>
    </franta_wms:spoi_italy>
  </gml:featureMember>
</wfs:FeatureCollection>
```
But the Firefox browser doesn't even know that the XML is encoded and fails with following error
```
XML Parsing Error: not well-formed
Location: https://hub4everybody.com/maps/euhubs/?hs-x=1023925.9124262823&hs-y=5695184.2046669535&hs-z=18
Line Number 15, Column 23:
```
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/96760b7a-7c73-4054-bb29-d97e4278f191)

**To Reproduce**
1. Go to 'https://hub4everybody.com/maps/euhubs'
2. Click on any point from layer "Smart points of interest"
3. See empty info panel

**Expected behavior**
List of properties shall appear in the info panel

**Screenshots**
Actual behaviour:
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/aaf96e4c-b6bd-45d4-8276-84a0188dae03)
Expected behaviour:
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/60330ffe-5ee8-4a5a-916e-b5c0ac38eb48)

**Additional context**
none

**Comment by FilipLeitner** [comment]
Really interesting. I tried investigating a bit and found out that when switching  INFO_FORMAT:text/xml.
Resulting XML is indeed malformed because of this line (element)
`<franta_wms:http://www.w3.org/1999/02/22_rdf_syntax_ns_type>http://gis.zcu.cz/SPOI/Ontology#shopping_and_service</franta_wms:http://www.w3.org/1999/02/22_rdf_syntax_ns_type>`

XML elements names seems to accept only :  letters, digits, hyphens, underscores, and periods. So colons and slashes in URL are the problem. You can try replacing the line with for example this modification
`<franta_wms:rdf_syntax_ns_type>http://gis.zcu.cz/SPOI/Ontology#shopping_and_service</franta_wms:rdf_syntax_ns_type>`

Regarding the base64 it seems that's just what Firefox does and it is not causing any problems because when trying query different layer (dnaube_nuts)   from the same server it works as expected. No forbidden characters so it just goes through

**Comment by jmacura** [comment]
Wow, thanks for the thorough investigation, @FilipLeitner !

**Comment by jmacura** [comment]
Attribute of layer with colons is invalid. Shall be fixed on Layman's side.
