### ISSUE TITLE
Datasource paging uses wrong limit

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#4056]
# Bug

**Describe the bug**
After several searches and a few added layers, the `limit` for datasource paging decreases. This doesn't seem as a desired behaviour to me.

**To Reproduce**
1. Go to 'Datasources' panel
2. Click on 'Next records' several times
3. Add some layer to the map
4. Return to 'Datasources'
5. (repeat step 2-4 if nothing changes)
6. See the limit shrinks

**Expected behavior**
Limit remains the same during the time the app is running.

**Screenshots**
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/4287adf4-5849-4f68-8ee2-60a3f9bd459a)
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/670853fe-d3e9-425f-95e9-614a640f09a4)
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/f27af5c5-80fb-43e1-bcda-be329c0a3267)

**Additional context**
Might be relevant for compositions as well.

**Comment by FilipLeitner** [comment]
Tried playing around a bit on https://hub4everybody.com/map/ and found out that reload triggered by extent change lowers the total amount of layers queried by one each time :D. Not sure if it was what you have stumbled upon but will fix this part atleast
