### ISSUE TITLE
Changed layer title not reflected in map swipe

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#4170]
# Bug

**Describe the bug**
Layer list in map swipe panel does not reflect the changes in layer names.

**To Reproduce**
1. Rename layer in layer manager
2. Open map swipe panel
3. Original layer title is displayed in the list instead of the new one

**Expected behavior**
Layer list in map swipe panel should reflect the changes and display the actual layer names.

**Comment by jmacura** [comment]
Is this change crucial to be backported to 11.x branch or is it fine to fix it in develop only @fzadrazil ?
