### ISSUE TITLE
No features loaded from WFS due to loadingstrategy

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#4275]
# Bug

**Describe the bug**
When a layer from WFS is added, it is zoomed out to the whole layer extent. But when there are too many features so the server won't return them, nothing is shown in the map. And when zooming in, no new requests are send due to the [loadingstrategy: bbox](https://openlayers.org/en/latest/apidoc/module-ol_loadingstrategy.html#.bbox), which prevents sending more requests while the view is within the same extent.

**To Reproduce**
1. Go to Datasources -> URL -> WFS
2. Connect to https://services.cuzk.cz/wfs/inspire-CP-wfs.asp? and select any layer
3. Add to map
4. See nothing loads

**Expected behavior**
A warning shown in a toast message telling what has happened and re-sending the request when the user zooms in. This must be handled on our side as no suitable loadingstrategy in OpenLayers is defined for it.

**Screenshots**
![obrazek](https://github.com/hslayers/hslayers-ng/assets/5598693/67d936f2-1c4a-40c7-9cfe-63bc1ae988ca)

**Additional context**
```
<?xml version="1.0" encoding="utf-8"?>
<ExceptionReport xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" xml:lang="en-US" xmlns="http://www.opengis.net/ows/1.1">
  <Exception exceptionCode="OperationProcessingFailed">
    <ExceptionText>Requested area to large!</ExceptionText>
  </Exception>
</ExceptionReport>
```

**Comment by FilipLeitner** [comment]
Seems to be working .

Initialy zoomed on Czech republic.
Then manually zoomed on Brno.

Not saying it is a plesant experience but features load. Its just a lot of data in this particular case


![Image](https://github.com/hslayers/hslayers-ng/assets/44566616/ee97e4f6-1984-40e1-8eb4-ea75b5279b51)

**Comment by FilipLeitner** [comment]
For 13x. - 15008cdb09144dde4a0435e5682178a09672d33a
