### ISSUE TITLE
Use map-composition scheme  as type

### ISSUE THREAD

**Issue by FilipLeitner** [hslayers/hslayers-ng#4290]
# Feature Request

Use [map-composition schem](https://github.com/hslayers/map-compositions)e  as type to ensure type safety and to declare which scheme version is supported

**Comment by jmacura** [comment]
Native implementation blocked by https://github.com/microsoft/TypeScript/issues/32063

Could be overcome with https://github.com/ThomasAribart/json-schema-to-ts (must read the schema from TS file) or https://github.com/bcherny/json-schema-to-typescript (must add pre-compile script).
