### ISSUE TITLE
reading data from Virtuozo

### ISSUE THREAD

**Issue by xarabiburacaramba** [hslayers/hslayers-ng#43]
after saving map composition there is a problem to read data from Virtuozo:
see this
http://www.opentransportnet.eu/web/guest/create-maps?composition=http%3A%2F%2Fwww.opentransportnet.eu%2Fwwwlibs%2Fstatusmanager2%2Findex.php%3Frequest%3Dload%26id%3D6b8a02cf-a932-4e12-ac07-d6aacff35784 
or this
http://www.opentransportnet.eu/web/guest/create-maps?composition=http%3A%2F%2Fopentnet.eu%2Fwwwlibs%2Fstatusmanager2%2Findex.php%3Frequest%3Dload%26id%3Db8728038-a374-4a8c-9616-2ed698d19940

**Comment by raitisbe** [comment]
Must have been a caching issue. No error after server restart.

**Comment by xarabiburacaramba** [comment]
Still while moving the map - sometimes the bus stations are not read. But I assume that it is not issue of HSLayers but an issue with Virtuozo.
