### ISSUE TITLE
Broken style sync with WFS from composition

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#4313]
# Bug

**Describe the bug**
Styles in SLD cannot be parsed from layer only when it is loaded from composition. When it is loaded from catalogue, the SLD is correctly parsed. Additionally, as the styles cannot be parsed, the default styles are applied and *rewrites* the original SLD styles in the layer description. See attachments below.

**To Reproduce**
1. Open some composition with vector/WFS layer which has styles attached to it.
2. See no styles has loaded and the default styles has been applied
3. Open the same composition in QGIS
4. See the default styles has rewritten the original style

**Expected behavior**
Load styles properly as if the layer is loaded directly from the catalogue.
Do not overwrite styles with the default styles automatically.

**Screenshots**
The layer styled in QGIS:
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/9412b138-4f10-4a18-ba2c-16fbcf126e80)
The layer after being opened from composition in hslayers:
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/5dda1617-ac9a-4e94-a1d1-c65cdd9937be)
The layer after being re-opened in QGIS (WMS):
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/fce51994-8289-4418-8af2-bd5908264e34)
The layer after being re-opened in QGIS (WFS):
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/a357c17c-4c2a-48d4-9d3e-aefa1efd4af3)

**Additional context**
* Style as saved by QGIS
* Style as rewritten by HSLayers to default
* Edited style as saved by HSLayers (for comparison)
[styles_hslayers_vs_qgis.zip](https://github.com/hslayers/hslayers-ng/files/12517224/styles_hslayers_vs_qgis.zip)

**Comment by FilipLeitner** [comment]
Replicated for compositions from QGIS only. Is caused by 'client' in style url which is not expected by hslayers-server proxy.

Request made for: https://hub4everybody.com/client/rest/leitnerfilip/layers/new_scratch_layer/style returns 404

Solution is to get rid of the 'client'.  Might be a task for QGIS client rather than HSL. 
@fzadrazil

**Comment by FilipLeitner** [comment]
https://redmine.ccss.cz/issues/9745
