### ISSUE TITLE
Duplicated sidebar entries when navigating (changing routes)

### ISSUE THREAD

**Issue by joaorodr84** [hslayers/hslayers-ng#4336]
# Bug

**Describe the bug**
When using angular/router ang changing routes, the sidebar entries get duplicated/triplicated/etc. It seems that the Observable of buttons never clears up and each time my map is reloaded, the previous sidebar entries are kept and a new batch is loaded on top of them

**To Reproduce**
1. Configure angular routes and put the hslayers map in one of those routes (e.g. /map)
2. Navigate back and forth from /map do one of the other routes.
3. Sidebar entries are never cleared and are loaded on top of each other.

**Expected behavior**
The sidebar entries should remain the same.

**Screenshots**
![2023-09-14_15h44_36](https://github.com/hslayers/hslayers-ng/assets/5513952/11f78c40-3830-42be-9348-5380260b453d)
go to /home
![2023-09-14_15h48_02](https://github.com/hslayers/hslayers-ng/assets/5513952/865396f3-0de2-45f0-aa40-dd3cff93e9d2)
go to  /map
![2023-09-14_15h48_11](https://github.com/hslayers/hslayers-ng/assets/5513952/cd6a93e2-607a-4293-896b-dc4cd51fb143)

**Additional context**
I uploaded my code [here](https://github.com/joaorodr84/hslayers-examples) and a video of this behaviour [here](https://www.youtube.com/watch?v=sRvUw3R9-u0)

**Comment by jmacura** [comment]
Thanks for reporting the issue @joaorodr84 ! We have identified the problem and the fix is on the way in #4340 . It will be OK in release 12.1.
