### ISSUE TITLE
Post workshop suggestions,bugs  ideas

### ISSUE THREAD

**Issue by FilipLeitner** [hslayers/hslayers-ng#4337]
# Post workshop suggestions,bugs  ideas
-  ~~additional options for arcgis rest layers from compositions~~   f2e83a9e1ce0ade5781840d88805c1e6ec7cb856
- ~~make sure user typed layer name is prioritized for ArcGIS Rest~~ #4414
-  duplication in Draw panel UI (Draw panel name, 'action' tab)
![image](https://github.com/hslayers/hslayers-ng/assets/44566616/00b0125b-3e7c-4b84-8b48-191d7326fbaa)
-  ~~hide warning informing about composition being belonging to another user when name changes~~  #4414
- ~~mapSwipe control is present in both componentsEnabled and  panelsEnabled objects in config~~ 
 **panelsEnabled shows/hides the whole panel, componentsEnabled says whather it should be activated by default**
-  ~~Layman x Micka datasoruce options. Should probably be the same just disabled if not avaialble~~  8fcfe0721
![image](https://github.com/hslayers/hslayers-ng/assets/44566616/88585a8e-c703-43d7-a516-857c0924d152)
![image](https://github.com/hslayers/hslayers-ng/assets/44566616/5eaeb011-72ea-46ff-9731-d9a72067f7ae)
- ~~Folder with name 'Other' is being  'hard' transalated. Not just in UI making a separate 'path' for each langauge.~~ 7953ac3769755a5efe588a858e516e1acb0e4cf3
- ~~Disable /HIde basic 'Fill' if 'Graphic fill' is used~~ 571bd4d8e4f03afd4f474011308f8b5e903aa88f
- ~~fillDrawableLayers most likely doesnt have to  poll Layman layers all the time.~~ wontfix
- ~~hslayers sidebar-bottom based on size of hslayers container not page~~ 4223c66f0bc4907e85fd065ddb47470520b418ac
- ~~sidebar openend config setting is overrun after compositon loaded is loaded  if open_lm_after_comp_loaded is true~~ Works as expected

**Comment by fzadrazil** [comment]
* additional options for arcgis rest layers from compositions
* make sure user typed layer name is prioritized for ArcGIS Rest
create new tickets for those

* duplication in Draw panel UI (Draw panel name, 'action' tab)
rename "Draw" tab to "Create"

* hide warning informing about composition being belonging to another user when name changes
create new issue - change warning that "you change the name and new composition will be created"

* mapSwipe control is present in both componentsEnabled and panelsEnabled objects in config
panelsEnabled shows/hides the whole panel, componentsEnabled says whather it should be activated by default
