### ISSUE TITLE
problem with KML layer

### ISSUE THREAD

**Issue by xarabiburacaramba** [hslayers/hslayers-ng#44]
KML layer in the composition:
1) overrides the composition extend
2) messes the order of layers (goes to the bottom of the layer list)

See:
http://www.opentransportnet.eu/web/guest/create-maps?composition=http%3A%2F%2Fwww.opentransportnet.eu%2Fwwwlibs%2Fstatusmanager2%2Findex.php%3Frequest%3Dload%26id%3D6b8a02cf-a932-4e12-ac07-d6aacff35784 

there the extent of the composition set to the center of Liberec and correct layer order is:
1) Open Transport Map
2) KML layer with bus stops
3) virtuozo layer with bus stops

**Comment by raitisbe** [comment]
fix for overriding map extent is in the repo

**Comment by wohnout** [comment]
Cool

**Comment by xarabiburacaramba** [comment]
For me didn't work . see for example: Bus stops in OTN pilot cities according to OpenStreetMap and SPOI . At first it zooms right, then it zooms out on KML layer extent and finally messes the order of layers (puts KML to the back). The composition was created today.

**Comment by wohnout** [comment]
Where were you testing this fix ? It is only in repository and at ng.hslayers.org

**Comment by xarabiburacaramba** [comment]
ok

**Comment by wohnout** [comment]
Fixed in repo
