### ISSUE TITLE
Legend doesn't show feature styles properly with clustered layers

### ISSUE THREAD

**Issue by DailisLangovskis** [hslayers/hslayers-ng#440]

**Comment by raitisbe** [comment]
Doesn't it still @DailisLangovskis ? In case it doesnt, can you create a screenshot and describe how it should look?

**Comment by DailisLangovskis** [comment]
Em, well this is an old issue, but i will look in to it, if it is fixed or not 👍

**Comment by DailisLangovskis** [comment]
Checked if this issue is still relevant and everything seems to be working fine, if there isn't to much points added on the map.

**Comment by DailisLangovskis** [comment]
It seems that i underestimated the issue, which is still relevant.
![Annotation 2020-08-20 161331](https://user-images.githubusercontent.com/46564459/90774424-22b4c980-e300-11ea-9b12-9e1c755c6062.png)
