### ISSUE TITLE
CSS is affecting parent page

### ISSUE THREAD

**Issue by bvj** [hslayers/hslayers-ng#445]
Example - in PrestaShop are menu styles in conflict (app.css from line 52).
It would be good to use hslayers CSS only for hslayers elements.

**Comment by raitisbe** [comment]
An option would be to contain all hslayers css in some container class ".hslng" for example 
and write in all css rules 
.hslng .menu ...
.hslng .lm-title {...

Did you notice any more classes except .menu? Menu seems to be a realy bad name for a css class.

**Comment by bvj** [comment]
noticed only the menu class, but for the future will be good solution your container class option

**Comment by jmacura** [comment]
Or maybe use 'hs-' prefix for every CSS class, as with the IDs here: #408 ?

**Comment by bvj** [comment]
Sounds good

**Comment by raitisbe** [comment]
Yes, prefixing is better. Because it protects from external css messing up hsl css, and not just other direction.

**Comment by raitisbe** [comment]
Also we should use ids less, because they wont work correctly when we have multiple hsl maps in the same page

**Comment by raitisbe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prefix possible conflicting css classes with 'hs' for embedding in hslayers in CMSes.](https://trello.com/c/4ypWVKQ6/7-prefix-possible-conflicting-css-classes-with-hs-for-embedding-in-hslayers-in-cmses)
