### ISSUE TITLE
Styles are not updated after SLD upload

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#4486]
# Bug

**Describe the bug**
Styles are not upadeted after SLD file is uploaded in the Styler panel

**To Reproduce**
1. Go to 'Styler' panel
2. Upload SLD file
3. See the styles in the panel are applied but are not propagated to the map

**Expected behavior**
Styles shall be updated also in the map view.

**Screenshots**
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/16fc07cc-0d2b-41fe-be44-b3c9d865d2fa)
=>
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/d4c0268d-bb5f-46c4-8af1-b49dd7708797)

**Additional context**
* SLD upload is also broken for File upload when SLD is attached to the other files (tested with Shapefile).
* I also propose to move the upload tools to the top, so they are again close to the "upload"/"download" buttons which were also moved to the top.
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/a15bc8ce-d9c9-44af-91a1-b1ea395ec97a)

**Comment by FilipLeitner** [comment]
Seems to be fixed by 002e4fa4b9d6cb11ee275ff1f12cfc0e9b2b6527

**Comment by jmacura** [comment]
Yes, the bug is resolved, as well as my side-notes. Thanks.
