### ISSUE TITLE
Layer title for WMS layer not reflected

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#4617]
# Bug

**Describe the bug**
When adding new layer(s) from WMS, the title text field is not used and title from the service layer name is used instead.

**To Reproduce**
1. Go to 'Datasources' > URL > WMS
2. Connect to some service, fill some title and select some layer(s)
3. Add them to the map
4. See different title in LayerManager

**Expected behavior**
The title from the "title" field in the add-data form shall be used in LayerManager.

**Screenshots**
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/206e10ed-9715-43d5-b3cf-fb173754b335)
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/e4f84f21-9139-467d-986a-19397330ea8d)

**Additional context**
none

**Comment by FilipLeitner** [comment]
This ones a bit tricky? Not so straightforward
It works only for base layers...kinda (seems like for multiselection only the first one is used - will fix this one first) 


![Image](https://github.com/hslayers/hslayers-ng/assets/44566616/0ec046b6-003f-4065-ba6c-6fbcd72b1a12)


On top of that when multiple layers from list are selected each will be added as a independent layer. Is that what we want?  Its been lake that for a quite some time so I suppose there are a reasons @fzadrazil

**Comment by FilipLeitner** [comment]
Basemap content fixed in #4620 by including all relevant layers in LAYERS param

**Comment by fzadrazil** [comment]
> On top of that when multiple layers from list are selected each will be added as a independent layer. Is that what we want? Its been lake that for a quite some time so I suppose there are a reasons @fzadrazil

Well, I would prefere to have multiple selected layers added as a group, but there were different opinions back then. Let's talk about it on the next meeting and decide.

**Comment by fzadrazil** [comment]
> > On top of that when multiple layers from list are selected each will be added as a independent layer. Is that what we want? Its been lake that for a quite some time so I suppose there are a reasons [@fzadrazil](https://github.com/fzadrazil)
> 
> Well, I would prefere to have multiple selected layers added as a group, but there were different opinions back then. Let's talk about it on the next meeting and decide.

The conclusion is that there will be an option whether to add as a group or independent layers, see #4630. The title would be taken over only in the case of group layer.
