### ISSUE TITLE
Option to add WMS layers as one group or separate layers

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#4630]
# Feature Request

**Is your feature request related to a problem? Please describe.**
There is currently no way to selected whether to add WMS layers as one group layer or as a set of separate layers to the map.

**Describe the solution you'd like**
Let the user decide whether to add selected layers as one group (and just one request for WMS) or separate layers. Group name should take over the title set in the textbox. If separated layers are selected, the title textbox would be hidden on disabled
![image](https://github.com/hslayers/hslayers-ng/assets/48727502/27341266-beee-4de1-9881-7551c9c4f9a5)

Group would be default option.

**Comment by jmacura** [comment]
Done for 13.x in 87a7303
