### ISSUE TITLE
Print components not toggleable

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#4634]
# Bug

**Describe the bug**
In the "print" panel, the "preview" is only generated when no sub-options (Legend, Imprint, Scale) are selected. When they are, the "preview" does not do anything. The same applies for "Print" action itself.

**To Reproduce**
1. Go to 'Print'
2. Tick 'Legend' or 'Imprint' or 'Scale'
3. Click on 'Preview' or 'Print'
4. See loading bar and then nothing happens.

**Expected behavior**
Preview shall open (in case of "Preview") and print dialog opened (in case of "Print")

**Screenshots**
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/280ded12-a94e-4e77-bbcc-9aa39f2fb78b)

**Additional context**
found on hub4everybody.com

**Comment by FilipLeitner** [comment]
Error: Uncaught (in promise): SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
![image](https://github.com/hslayers/hslayers-ng/assets/44566616/1dbb0edd-09fc-4ec2-9b95-39ff610a6c75)

**Comment by jmacura** [comment]
Fixed for 13.x in 49d449c
