### ISSUE TITLE
Layout changes

### ISSUE THREAD

**Issue by FilipLeitner** [hslayers/hslayers-ng#468]
- Placement of search and measure tools could be configurable between sidebar and toolbar 
    (to place tool to sidebar add 'desired-tool':true to config. panelsEnabled)
- Sidebar buttons visibility handling inside ng-if statement with function is slow and called many times, unnecessarily
Improvements:
- Add thumbnails for basemap gallery - possible TODO : configurable
- Move additional info block toggle to icon inside layerlist 
- Move reset map button from toolbar to layermanager

**Comment by FilipLeitner** [comment]
#469

**Comment by FilipLeitner** [comment]
- Little basemap gallery behavior changes
- Enhnace czech translation + add .js files for gettext() content to gruntfile

**Comment by FilipLeitner** [comment]
#518

**Comment by jmacura** [comment]
Can this issue be closed @FilipLeitner ?
