### ISSUE TITLE
Styler defaults

### ISSUE THREAD

**Issue by FilipLeitner** [hslayers/hslayers-ng#4689]
cbe93c52d3e42d3daa2047ac1dc4e71533a4c435

**Comment by jmacura** [comment]
Thanks for the fixes in https://github.com/hslayers/hslayers-ng/commit/cbe93c52d3e42d3daa2047ac1dc4e71533a4c435 !

**Comment by FilipLeitner** [comment]
One more thing to be added.
062c75c5f007d2e44d6786a3562ffced74c1f3a0

As per https://github.com/geostyler/geostyler-openlayers-parser/pull/757 opactiy woraround should not be necessary. Tried exporting/loading SLD and opacity was displayed correctly

Will close #3677 after port to 14x is merged
