### ISSUE TITLE
Use inject() function to inject hsLayoutService into HsPanelBaseComponent

### ISSUE THREAD

**Issue by FilipLeitner** [hslayers/hslayers-ng#4707]
Using inject() eg. 

![Image](https://github.com/hslayers/hslayers-ng/assets/44566616/8fc61f7c-b1d8-4a8e-81f7-76f62859ea0b)

instead of constructor injection in base components such as `HsPanelBaseComponent` enables skipping of injection of nececssary services in components that extent base component.
`super()` constructor call can be executed without arguments. Services of base components are accessible from child as if injected in constructor

Functionally theres no difference, just better DX.

**Comment by jmacura** [comment]
Feels like old AngularJS :-)
