### ISSUE TITLE
Configuration parameter for Ctrl+mouse wheel zoom

### ISSUE THREAD

**Issue by bvj** [hslayers/hslayers-ng#474]
Will be nice, if we have config parameter for map zoom using Ctrl+mouse wheel instead mouse wheel only.

**Comment by jmacura** [comment]
Sounds very Google Maps-ish...

**Comment by bvj** [comment]
Yes, but if we have map on portal and user look on map and then want scroll down to bootom of page, he zoom map instead scrolling.

**Comment by bvj** [comment]
Here is code we used on one project:
```
module.controller('Main', ['$scope', 'Core', 'config', 'hs.map.service', '$rootScope',
			function($scope, Core, config, hsMap, $rootScope) {

	$rootScope.$on('map.loaded', function() {
					var oldFn = hsMap.interactions.MouseWheelZoom.handleEvent;
					hsMap.interactions.MouseWheelZoom.handleEvent = function (e) {
						var type = e.type;
						if (type !== "wheel" && type !== "wheel") {
							return true;
						}

						if (!e.originalEvent.ctrlKey) {
							return true
						}

						oldFn.call(this, e);
					}
				});
```

**Comment by jmacura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Extend config with scrolling option.](https://trello.com/c/xPspXiFy/6-extend-config-with-scrolling-option)
