### ISSUE TITLE
Use annotate technique (change naming of services)

### ISSUE THREAD

**Issue by ChcJohnie** [hslayers/hslayers-ng#478]
Suggestion for next major release (very breaking)

Enable usage of ng-annotate or its babel variant ( https://www.npmjs.com/package/babel-plugin-angularjs-annotate ) 
You dont need to double dependency definition and still be safe during minification.

For start change of service naming is needed as these need to be variable name friendly - hs.map.service -> hsMapService or simply hsMap

**Comment by raitisbe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use annotate technique (change naming of services)](https://trello.com/c/HpVSx32p/65-use-annotate-technique-change-naming-of-services)
