### ISSUE TITLE
Use $location everywhere in hs.permalink.url

### ISSUE THREAD

**Issue by ChcJohnie** [hslayers/hslayers-ng#479]
Use $location instead of window.location in all places.
In certain edge cases of angular url building $location is more reliable.

**Comment by raitisbe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use $location everywhere in hs.permalink.url](https://trello.com/c/K935xCM0/66-use-location-everywhere-in-hspermalinkurl)
