### ISSUE TITLE
Permalink is not working correctly

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#48]
If I am working with this Map composition on OTN portal http://goo.gl/T03mDE , the code is correct  , if I am copping this code into other browser it works well. However if I am sharing it on Facebook of Google, there is not shared permalink, but whole composition. See attaached file 
![permalink](https://cloud.githubusercontent.com/assets/16701286/16538294/6d814466-4020-11e6-8e42-dd24ceede81b.png)

**Comment by wohnout** [comment]
Fixed in git. Update is needed on HUB
