### ISSUE TITLE
Missing "Plus button" in Datasources component

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#482]
The plus button (Datasources panel) to add layer to map dissapears for some screen resolutions. It seems the button is floating on the page and is not properly positioned.

**Comment by jmacura** [comment]
![obrazek](https://user-images.githubusercontent.com/5598693/73356619-0d604b00-429b-11ea-9870-3cc1ca363381.png)
![obrazek](https://user-images.githubusercontent.com/5598693/73356647-1cdf9400-429b-11ea-9507-ed53acf922b9.png)

**Comment by fzadrazil** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Missing plus button in Datasources panel](https://trello.com/c/CEBvbrkr/4-missing-plus-button-in-datasources-panel)

**Comment by raitisbe** [comment]
yes, it has position: fixed. Probably has to take width of sidebar into account
