### ISSUE TITLE
Load WMS with the "ignore extent" option

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#4863]
# Feature Request

**Is your feature request related to a problem? Please describe.**
When a layer is loaded from composition or from catalogue, there is no way how to ignore its extent by default. That can lead to clipped symbols on the borders of the extent. It can later be set in layer manager, but user doesn't have to know about that (it can be even an application without sidebar).

![image](https://github.com/hslayers/hslayers-ng/assets/48727502/f9b2f96e-64ea-4332-b8ab-6e241b760a3e)
https://geoportal.az/geoserver/fzadrazil_wms/ows

**Describe the solution you'd like**
Have an option to save layer with ignoring extent to map composition. That would require change in the map-composition schema. Possibly set "ignore extent" as default when loading layer from catalogue or map composition?

**Comment by jmacura** [comment]
This is constantly annoying. As a first step, we might brute-force add a larger extra space around to the calculated bbox.

**Comment by fzadrazil** [comment]
1. Add layer - automatically extend the extent by, let's say, 10%.

2. Save current map - Save "ignoreExtent" as a temporary workaround as a param of the layer.

```
     "params": {
        "FORMAT": "image/png; mode=8bit",
        "INFO_FORMAT": "application/vnd.ogc.gml",
        "LAYERS": "chargers",
        "STYLES": "",
        "VERSION": "1.3.0",
        "ignoreExtent": true
      },
```
