### ISSUE TITLE
Problems with Embeded on SDI4Apps Blog

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#49]
I don’t know, if it is generic error in Embedded or if it is problem with WordPress or only on SDI4Apps , but I have such problems with Embeding. Could be, that it is only question of configuration of SDI4Apps Web pages, but I am not able to check it.
So I am using next permalink http://goo.gl/T03mDE. I am generating iframe code
<iframe src="http://goo.gl/T03mDE" width="1000" height="700"></iframe>
And putting it into editor for blog. See 
![test 1](https://cloud.githubusercontent.com/assets/16701286/16538333/c98c9660-4021-11e6-93a9-b33359541a35.png)
If I am switching to visual code it is OK
![test 2](https://cloud.githubusercontent.com/assets/16701286/16538338/11006e72-4022-11e6-8ed9-126308e2598d.png)
However when I am publishing it, it disappear. See
![test 3](https://cloud.githubusercontent.com/assets/16701286/16538348/6a3851ee-4022-11e6-8372-435f1cbc9511.png)

**Comment by wohnout** [comment]
I had try it here http://ng.hslayers.org/2016/07/09/embeded/ . Looks that it works
