### ISSUE TITLE
WMS-t broken

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#5059]
# Bug

**Describe the bug**
WMS-t layer stuck with "Fetching available times..." in LayerManager

**To Reproduce**
1. Go to test-app
2. Go to LayerManager
3. See layer "Optical satellite basemap" stucks at loading times

**Expected behavior**
Available times shall be fetched and displayed.

**Screenshots**
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/7ed62698-7041-4957-ba7d-e07e021b45ec)

![image](https://github.com/hslayers/hslayers-ng/assets/5598693/1f7067b1-8354-4053-8476-fc31d754daa5)

**Additional context**
Works fine in v13.1 as can be seen e.g. at https://hub4everybody.com/map/

**Comment by FilipLeitner** [comment]
For the 'Optical satellite basemap' it is the timing issue. 
`layerDimensionDefinitionChanges` is emitted before subscriber is setup in `HsLayerManagerService`
![image](https://github.com/hslayers/hslayers-ng/assets/44566616/311de6c0-4f3f-45ca-a0a5-eef9517c4fff)
When increasing timeout of emittion to 1s one more caveat to consider appears - layerDesriptor is created late
![image](https://github.com/hslayers/hslayers-ng/assets/44566616/8a121200-a2b5-4d6c-805d-9e9b7a1e5455)

Maybe we could wait for mapEventHandlersSet before the emittion but I am not really familiar with the dimensions part of the code so maybe it needs to be handled more robustly not just this hack.

**Comment by jmacura** [comment]
Thanks for investigating this, @FilipLeitner ! I wil try to look at that.
