### ISSUE TITLE
Map Compositions Count for OTN

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#52]
COmming from Irene https://redmine.ccss.cz/issues/5959
![countcompositions2](https://cloud.githubusercontent.com/assets/16701286/16626992/8edbc4ea-43ab-11e6-9e21-c69db613a8bd.png)
![countcompositions](https://cloud.githubusercontent.com/assets/16701286/16626993/8ef410c2-43ab-11e6-9ec7-878c60b54682.png)

As a usability feature, I would propose adding in the map component one extra textbox below the "compositions" tab (see attached) to show total number of compositions that would change following zooming in and zooming out (by map extent).

In the same sense, it would be very helpful to have an annotation of paging as we have in the listing of datasets (see attached no2).

Please check its feasibility and give me a timeframe as it is considered as an important usability feature.

Many thanks in advance for this consideration.

**Comment by wohnout** [comment]
Done. Update of hsl-ng is needed
