### ISSUE TITLE
Check icons on the toolbox

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#53]
Issue from Irene

Please. check the behaviour of the tool box in the map composer.

when i click on an icon, then it stucks over the second icon (see attached) and no matter which icon I choose, this stays there stuck just changing the icon in the middle.
Also, when making mouse over, the icons are changing their alignment and placing on the toolbox.

Also, I thought we have added some more transport icons after Prague meeting, but now seems a bit old here. Have we made any changes since then?

Many thanks.

![toolbox](https://cloud.githubusercontent.com/assets/16701286/16712700/1c7f0ce0-468f-11e6-9d9c-e9466e28bba7.png)

**Comment by wohnout** [comment]
Resolved
