### ISSUE TITLE
Sharing of a map composition - allow to hide all elements on top of the map except the map

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#55]
When sharing a map composition via URL (iframe), allow user to hide all the elements displayed on top of the map screen (left menu, OTN register/sign in, search tool, OTN menu etc.). This would allow users to create maps in OTN for publishing on their websites in 'clean' design without being disturbed by all the menus and tools. The layers menu could stay but shall be hidden by default (and possible to open by clicking on the icon). This setting for sharing via URL (hide/display elements on top of the map) could be done when saving the compostion

Probably will be good made some parametrisation

**Comment by wohnout** [comment]
Done

**Comment by kcharvat** [comment]
Is there some testing link?
