### ISSUE TITLE
pureMap with controls

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#555]
In config, we can now use either `sidebarClosed`, which makes the panel closed on start, but it can be opened and used normally, or `pureMap` which removes the panel completely, but also stops all interactions leaving only a map as an image.

What is requested by this issue is another option in config, which should lead to a compromise: remove the side panels, but keeps the zoom controls, pan interaction and so on..

**Comment by jmacura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pureMap with controls](https://trello.com/c/bsNuSQof/51-puremap-with-controls)

**Comment by raitisbe** [comment]
I think we need to refactor this into multiple config parameters, which could still be set with pureMap function to have backwards compatibility, but would support single-responsibility principle. In layout.html would not use pureMap at all but those config params.
The configs could be:

- sidebarVisible (visible at all - could be visible, but closed)
- toolbarVisible: true/false
- mapInteractionsEnabled: true/false
- maybe something else?

**Comment by jmacura** [comment]
Sounds legitimate. Backwards compatibility is important.
"sidebarVisible" and "toolbarVisible" param names align with "locationButtonVisible", so we can go that way.
Or we can create param availableComponents which would be and object like
```
availableComponents: {
  sidebar: true/false
  toolbar: true/false
  mapInteractions: true/false
  ...
}
```

**Comment by raitisbe** [comment]
Like the idea of available components dictionary. mapInteractions dont realy fit there imho, but rest is definitely more readable.

**Comment by jmacura** [comment]
Agree, mapInteractions don't fit into it that much, but I feel that the number of config params grows too quickly and it can become hard to find the correct config option in the enless list soon. Hence I tend to merge similar params together if possible...
Then, we can go with a dictionary simply called "visibleComponents" where we can put sidebar, toolbar and locationButton, for now. mapInteractionsEnabled would be separated. What you mean?

**Comment by raitisbe** [comment]
I'm a bit worried about the distinction between component and panel even though they do the same thing - hide or show different elements. panelsEnabled is quite ingrained everywhere in the code. Maybe we should just use the existing panelsEnabled and populate them with toolbar, geolocation and sidebar?

**Comment by raitisbe** [comment]
Or have the panelsEnabled just for the sections in the sidebar and use components for everything else

**Comment by raitisbe** [comment]
Added an example for the config options demo: at https://github.com/hslayers/examples/blob/master/components-visible/app.js

**Comment by jmacura** [comment]
Comment on:
```
componentsEnabled: {
      sidebar: true/false,
      toolbar: true/false,
      guiOverlay: true/false,
      drawToolbar: true/false,
      searchToolbar: true/false,
      measureToolbar: true/false,
      golocationButton: true/false
    },
    mapInteractionsEnabled: true/false,
    mapControlsEnabled: true/false,
```

Looks good, but I have several notes:

`mapControls` can go into `componentsEnabled`, I think.
I don't like that some combinations does not make sense, e.g. when you set `guiOverlay=false` + `searchToolbar=true`. The latter will be ignored. Or `toolbar=false` + `drawToolbar=true`.
Do we need `guiOverlay` at all?

**Comment by raitisbe** [comment]
I think its nice to be able to disable all extra overlays with one config, but also have controll over the children in a hierarchy. Maybe some note in documentation might be needed reveal the hierarchy, but otherwise is a common practice that parent element might be hidden and children configured to be visible, but in rality hidden because of parent. 
I don't have a clear reasoning about mapControls so will just go with your suggestion then. Just keep the mapInteractionsEnabled out of the componentsEnabled.

**Comment by jmacura** [comment]
I was just thinking about a nested system like this:

```
componentsEnabled: true/false or Object {
      sidebar: true/false,
      toolbars: true/false or Object {
          drawToolbar: true/false,
          searchToolbar: true/false,
          measureToolbar: true/false,
      },
      golocationButton: true/false
      mapControls: true/false,
    },
    mapInteractionsEnabled: true/false,
```

true/false on `componentsEnabled` would set true/false for all its subparameters. The same for `toolbars`. If a consumer wants to set the visibility of components individually, then he/she would use the object (dictionary) instead of simple boolean value.

But maybe it's overcomplicated.... ❓

**Comment by jmacura** [comment]
This also leads me to a separate, but related, idea that a stand-alone service, that would be parsing and validating the config object might be useful...?
So we can provide a user-friendly config options, while not polluting the Core and layout components with too many hooks?

**Comment by raitisbe** [comment]
It's indeed too complicated if the user needs to know the full hierarchy to be able to hide some component. He should be able to just inspect html element and guess the name of the property to set from there.

Regarding the configparsing, how about having multiple seperate smaller services to parse and act on config inside the modules instead of a big one + some common functions extracted to common/config.utils.js?

**Comment by jmacura** [comment]
> It's indeed too complicated if the user needs to know the full hierarchy to be able to hide some component. He should be able to just inspect html element and guess the name of the property to set from there.

Valid argument. Changes approved, the PR can be merged and this issue can be resolved.

> Regarding the configparsing, how about having multiple seperate smaller services to parse and act on config inside the modules instead of a big one + some common functions extracted to common/config.utils.js?

This needs to be reasoned further and I would like more opinions about that. But common/config.utils.js sounds as a good way to go :-)
