### ISSUE TITLE
RSS channel for new compossition

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#56]
It will be usefull to be informed about newest compossitions on portal

**Comment by wohnout** [comment]
This is done by micka. for example http://opentransportnet.eu/php/metadata/csw/?request=GetRecords&query=type%3D%27application%27&format=application/xml&MaxRecords=9999&StartPosition=&language=eng&outputSchema=http://www.georss.org/georss

**Comment by kcharvat** [comment]
So it means, that it has to be done on portal level to implement this?

**Comment by wohnout** [comment]
yes

**Comment by wohnout** [comment]
Or you need to have micka to store compositions
