### ISSUE TITLE
Be able dirrectly publish any new map compossition on selected conected profile on FAcebook or Twiter

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#58]
Somethng such is in Wordpress, where you can any news in blog automaticly publish on Twiter or Facebook account. It will be usefull also for Map compossitions

**Comment by wohnout** [comment]
That is not easy to do because you need to create firstly application on fb and then you can publish. I have never done anything with development of fb application

**Comment by kcharvat** [comment]
We can close this, I think, that with the link is OK
