### ISSUE TITLE
Support #5965: Browser compatibility 

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#59]
Description

The explore maps has a white screen since the transfer to the new server. Browser compatibility needs to be checked. Does not work for me on Macbook Safari (9.1.1)
Add

Related issues
History
#1
Updated by Richard Brown about 3 hours ago

    Assignee changed from Richard Brown to Irene Matzakou

Comment Edit

Explore Maps is HSRS's component.
#2
Updated by Irene Matzakou about 3 hours ago

    Assignee changed from Irene Matzakou to Karel Charvat

Comment Edit

Can you please check this with some priority? Many thanks

**Comment by wohnout** [comment]
it works for me. Propably just network problem
