### ISSUE TITLE
Error in Publishing on Facebook

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#60]
when I am publishing Map compossition on FAcebook, there is some error message ":Invalid App ID: 0"

**Comment by wohnout** [comment]
Unfortunatelly selected type of sharing on facebook has stopped working. I had to start using different one which doesn't provide too much info to share. Just url ...

**Comment by kcharvat** [comment]
Doesnt exist some other solution, to share only url is not good. Minimaly will be needed to add some manual text

**Comment by wohnout** [comment]
This is not problem of solution. This is problem of Facebook. You must create full facebook app to allow this.

**Comment by kcharvat** [comment]
What does it mean to create full Facebook App? I dont understand

**Comment by raitisbe** [comment]
We could provide the title description in the peralonk url and use serverside scripting to generate the metatags in html since facebook doesnt execute javascript when inspectin the url in the post. A bit outside hsl scope but doable i think. Have to check if php can access variables after # . I have my doubts

**Comment by kcharvat** [comment]
OK

**Comment by kcharvat** [comment]
There is streng behaiviour for sharink data via Pure sharing or permalink. See http://goo.gl/RIS7u0 and  http://goo.gl/fRPhND or http://goo.gl/gvua0y and http://goo.gl/Rhp85z. It is dispalyng layers, but if you go to list, you see there Vykricnik. In permalink in some cases is also displayed previous compossition together with new

**Comment by wohnout** [comment]
This is problem of WMS it has restrited size of 2048x2048 pixels. I have turned on by default use tiles for wms and added warning when you turn it off. Nothing more can be done, I think
