### ISSUE TITLE
Add tittle of compossition, when commposstion is published trough Embeded on FAcebook or Twiter

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#61]
It will be good to add tittle of commpossition, when I am publishing Composstion on social networks trough Embeded functionality. look please on this

**Comment by wohnout** [comment]
This is not possible.

**Comment by kcharvat** [comment]
Why note,dont understand, without this we can remove function.

**Comment by kcharvat** [comment]
It is necessary to thinking about some other solution, which could help

**Comment by wohnout** [comment]
this is not about solution. This is policy of facebook.

**Comment by kcharvat** [comment]
I dont undestand, you dont have problem to share links with cooments for example from Wordpress, you are normaly sharing tittle and links. Why it is not possible to do this here I dont understand

**Comment by kcharvat** [comment]
If I am sharing from SDI4Apps portal I am every time sharing tillte of contribution and link, why it is not possible here
