### ISSUE TITLE
Error with WMS from other projection

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#63]
Seems that projection transformation is not working. I tested on http://youth.sdi4apps.eu/ WMS from CENIA, for exampel http://geoportal.kr-vysocina.cz/arcgis/services/Biochory/MapServer/WMSServer?SERVICE=WMS&REQUEST=GetCapabilities or http://geoportal.gov.cz/arcgis/services/CENIA/cenia_aleje/MapServer/WmsServer?SERVICE=WMS&REQUEST=GetCapabilities
It is not working

**Comment by raitisbe** [comment]
The server replies with Error 500 Internal server error
http://youth.sdi4apps.eu/cgi-bin/proxy4ows.cgi?OWSURL=http://geoportal.kr-vysocina.cz/arcgis/services/Biochory/MapServer/WmsServer?&owsService=WMS&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=0&INFO_FORMAT=application/vnd.esri.wms_featureinfo_xml&FROMCRS=EPSG:4326&CRS=EPSG:4326&STYLES=&WIDTH=3186&HEIGHT=784&BBOX=7.601959977540446,-88.06640625,86.77340871813976,233.61328125

**Comment by raitisbe** [comment]
I dont have the permission to connect to youth.sdi4apps.eu. Maybe proxy4ows service is not configured correctly? mapserver?

**Comment by kcharvat** [comment]
Marek Premek could you give access to Raitis

**Comment by bvj** [comment]
Configuration updated, now i got error:
`<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException>
msWMSLoadGetMapParams(): WMS server error. Image size out of range, WIDTH and HEIGHT must be between 1 and 2048 pixels.
</ServiceException>
</ServiceExceptionReport>`

**Comment by raitisbe** [comment]
can you increase the width limit?

**Comment by bvj** [comment]
I think, problem is on server, you are calling:
`http://geoportal.kr-vysocina.cz/arcgis/services/Biochory/MapServer/WmsServer?&owsService=WMS&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=0&INFO_FORMAT=application/vnd.esri.wms_featureinfo_xml&FROMCRS=EPSG:4326&CRS=EPSG:4326&STYLES=&WIDTH=3186&HEIGHT=784&BBOX=7.601959977540446,-88.06640625,86.77340871813976,233.61328125`
this is returning to me:
`<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException code="InvalidFormat">Parameter 'width' contains unacceptable value.</ServiceException>
</ServiceExceptionReport>`

**Comment by wohnout** [comment]
This was propably fixed by doing changes to permalink
