### ISSUE TITLE
Add possibilities to registered servis in Micka

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#65]
![register service](https://cloud.githubusercontent.com/assets/16701286/18309156/402abfee-74f8-11e6-8fbc-b9589f2d2388.png)
This could be one from functions to extended and put all client functionality into Micka. 
If I am adding some services WMS, KML, JSON into Map compossition, will be good  also offer possibilities directly registered this service data in Micka

**Comment by raitisbe** [comment]
1) Will this functionality be enabled by default?
2) Will the user need to be authorized to do it or we will use some hard-coded user/password to connect to micka?
3) Which micka instance should I use if it will be completely centralized or if not which can I use for tests?

**Comment by kcharvat** [comment]
It has sense only for portal solution. I think that it could be as with storing data composition, this function will be enable only if you will be registered.

I don’t know, which Micka is used for development, speak eventually with Premek or Marek
