### ISSUE TITLE
zoomWithModifierKey no longer does what it should

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#662]
Even if `zoomWithModifierKey` config option is set to `true`, the map zooms without the modifier key.
Discovered by @bvj .

**Comment by jmacura** [comment]
This actually never worked as documented, because the param is named `zoomWithModifierKeyOnly` (my bad..), hence there are two options now:

1. align documentation to implementation
2. align implementation do documentation

opinion, @fzadrazil ?

**Comment by fzadrazil** [comment]
Ok, please correct the documentation then.

**Comment by jmacura** [comment]
Corrected at https://github.com/hslayers/hslayers-ng/wiki/Config-parameters#map
