### ISSUE TITLE
Open Layer manager after loading a composition

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#673]
Automatically switch to Layer manager right after loading a composition (Compositions panel) as it changes the content of the map. It makes sense the most from the perspective of the user. He can immediately see the current layer list.

**Comment by fzadrazil** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Open Layer manager after loading a composition](https://trello.com/c/wjLbfuw0/68-open-layer-manager-after-loading-a-composition)

**Comment by raitisbe** [comment]
set config variable open_lm_after_comp_loaded: true
