### ISSUE TITLE
Refactor cesium modules

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#682]

**Comment by raitisbe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cesium rendering error](https://trello.com/c/yRLhHILV/69-cesium-rendering-error)

**Comment by raitisbe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rewrite hscesium module](https://trello.com/c/1oKXCNdQ/90-rewrite-hscesium-module)

**Comment by jmacura** [comment]
Safe to close this, @raitisbe ?

**Comment by raitisbe** [comment]
ok, maybe the actual rewrite to ng9 should be a seperate issue since this has so many commits, that its hard to track
