### ISSUE TITLE
WFS 2.0 client

### ISSUE THREAD

**Issue by xarabiburacaramba** [hslayers/hslayers-ng#69]
In context of ELF project - we need to discuss whether we need to implement possibility to read WFS 2.0 services directly into HSLayers. The format that is sent by the service is GML 3.2 . Another question whether we need it? May be after the ELF review next week the situation will be clearer.
Anyhow , please, for now tell how difficult for you to implement WFS 2.0 layer with GML 3.2 features in HSLayers NG?

**Comment by raitisbe** [comment]
I think it doesnt make much sense to do it before openlayers supports parshing of gml3.2 responses. After 3 years it still doesnt.
