### ISSUE TITLE
Delete features button in hover popup

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#697]

**Comment by raitisbe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Delete features button in hover popup](https://trello.com/c/GfWS5urv/72-delete-features-button-in-hover-popup)

**Comment by raitisbe** [comment]
![image](https://user-images.githubusercontent.com/395514/83515465-12016e00-a4de-11ea-9a65-c3f9ff50f724.png)

**Comment by jmacura** [comment]
Solved by #698
