### ISSUE TITLE
Adding any WMS through Datasources panel does not work

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#701]
See eg. https://www.smartafrihub.com/cs/map1 and try to add any WMS from Micka. It adds the layer to Layer manager but doesn't draw it.

angular.js:15570 TypeError: Cannot read property 'indexOf' of undefined at Object.getLegendUrl (legend.service.js:277)
Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined at Object.requestGetCapabilities (get-capabilities.service.js:74)

**Comment by raitisbe** [comment]
71f1ee341a7f193c425d976bccd09e3f1140ca41
