### ISSUE TITLE
Explore migration to Angular 9

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#725]
https://www.digitalocean.com/community/tutorials/how-to-upgrade-from-angularjs-to-angular-with-ngupgrade
https://stackblitz.com/edit/angular-ng-upgrade-downgrade?file=src%2Fangular%2Findex.ts
https://github.com/ui-router/sample-app-angular-hybrid/tree/master/app/contacts

**Comment by jmacura** [comment]
This issue might be better separated into individual issues and group by a project or a milestone.

**Comment by jmacura** [comment]
and the third part about filters etc.:
https://www.digitalocean.com/community/tutorials/how-to-upgrade-angular-sorting-filters

**Comment by raitisbe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrade to angular 9](https://trello.com/c/3URQG641/76-upgrade-to-angular-9)

**Comment by raitisbe** [comment]
References issue #733
