### ISSUE TITLE
WMS Layer Feature Info popup

### ISSUE THREAD

**Issue by bvj** [hslayers/hslayers-ng#78]
As on attached screenshot, the info popup looks out too ugly.
![image](https://cloud.githubusercontent.com/assets/8994271/23010613/b3875d3c-f41c-11e6-89c5-25c945e3d303.png)

**Comment by bvj** [comment]
Maybe we can have some option in app.js for choosing show info in panel and/or in popup.  But the popup still need graphical (css?) improvement.

**Comment by bvj** [comment]
If we (you) add this option this must be optional. In case of old app.js files the map must working without it.

**Comment by ChcJohnie** [comment]
I change Info popup system little bit. Works better now?
