### ISSUE TITLE
Unused type errors in tslint

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#791]
![image](https://user-images.githubusercontent.com/395514/86612991-a23d4200-bfb9-11ea-9768-ca66b3f7e434.png)

Getting errors about unused imports, even though they are used when injecting services into classes constructor.

**Comment by raitisbe** [comment]
Screenshot from layer-editor-vector-layer.service.ts

**Comment by raitisbe** [comment]
Similarily == comparison with undefined is valid thing in typescript.

![image](https://user-images.githubusercontent.com/395514/86618225-33fc7d80-bfc1-11ea-8a27-767fa5163211.png)

**Comment by jmacura** [comment]
> 
> 
> Similarily == comparison with undefined is valid thing in typescript.
> 
>

It is a valid thing in JavaScript as well, but it's generally discouraged to use double equal comparison where triple equal comparison can be used.
Does this ESLint error causes webpack to fail or does it only spoils your "problems" log?

**Comment by raitisbe** [comment]
Just the problem log. It wants me to use angular.isUndefined which doesnt
exist for ng9

**Comment by jmacura** [comment]
> 
> Just the problem log. It wants me to use angular.isUndefined which doesnt exist for ng9

Sure, I get it. That's an easy fix then. The other I will have to investigate.

**Comment by jmacura** [comment]
FYI the vars were unused as such, only as type definitions, which is not recognised in JS. I have changed the order in which the eslint rules are applied, thus now the TS rules have priority over "classic" JS rules coming from openlayers. And usage of variables in type definitions is of course recognised in TS, so eslint should only log warnings, not errors, from now on. We can disable the rule for good if requested.
