### ISSUE TITLE
Map crashes when resizing window

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#804]
![image](https://user-images.githubusercontent.com/395514/86977986-79b67300-c186-11ea-9073-2257433c2df9.png)

**Comment by raitisbe** [comment]
f7a1de3fcb3094fb5ac50f474203389700bb5950 and 7ffcdfd750bd74372a46e8ceb5a2f8beb281fe86 partly solves that but sometimes the errors still appears

**Comment by FilipLeitner** [comment]
Mostly comes from default css set to body element (margin 8px ). CSS and JS changes are calculated with different values of 'app' width. CSS responds to screen media query (currentyl set to 767px), JS to layoutContainer. If the values (in fullscreen mode) are not the same, the difference bugs the layout.  

Happens while map is resized/initiated with the screen width in range of 768-783px (corresponds to 752-767px in terms of layoutElement width).
Container mode should be working properly. 
...however it still can happen if the function is called too often, should be rare tho.

**Comment by raitisbe** [comment]
Did you manage to fix this @FilipLeitner ?
