### ISSUE TITLE
Uncaught (in Promise): [object Undefined] randomly happening in the console

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#828]
![image](https://user-images.githubusercontent.com/5598693/87981361-6e900b00-cad5-11ea-8d91-61d670418229.png)

This error sometimes appears in my console (and when it appears, then always twice). It also results in a vector layer which won't get clustered (despite it should be) and an empty Layer Manager.
Can't see where it comes from, as all the files listed as the source of the error in the console are Angular files, not ours.

**Comment by Gmarquis45** [comment]
Same problem here with 2.1.1 version.
Only sometimes, hard to reproduce... :(

**Comment by raitisbe** [comment]
I think its due to loaded() {
    return new Promise((resolve, reject) => {
      if (this.map) {
        resolve(this.map);
        return;
      } else {
        this.$timeout(() => {
          if (this.map) {
            resolve(this.map);
          } else {
            reject();
          }
        }, 1000);
      }
    });
  }
in map.service.js. Map didn't manage to initialize itself in 1000 miliseconds probably. Should write this in a more clever way.

**Comment by raitisbe** [comment]
Easy to catch this error when having debugger; in some service and while it stops the execution, the promise gets rejected.     constructor(private HsMapService: HsMapService, private HsEventBusService: HsEventBusService) {
        debugger;
        this.HsEventBusService.cesiumLoads.subscribe((data) => {
            debugger;
            this.init(data.viewer);
        })
    }
