### ISSUE TITLE
Smooth map resize (suggestion)

### ISSUE THREAD

**Issue by ChcJohnie** [hslayers/hslayers-ng#83]
Map jumps when map element is resized (sidebar expansion) which might be unpleasant to users.
Possible solutions:
a) Animated move of map (like in mapy.cz)
b) Stationary map (Gui elements floating above - like in Gmaps)

Booth solutions seems much more comfortable.

**Comment by raitisbe** [comment]
At the beginning of hslayers we had b) , but it was deemed to be bad. Don't remember the exact reasoning, but probably it was due to map and some of its controls being overlaid and not accessible. I would go with a) if its doable.
