### ISSUE TITLE
[2.1.2] - TypeError: Cannot read property 'Layer' of undefined

### ISSUE THREAD

**Issue by Gmarquis45** [hslayers/hslayers-ng#843]
HSlayer version : 2.1.2 with the full example (angular9 branch)

I got this error from my layer when I click to the arrow near the layer title. 
Screenshot join and my appexternal.js for adding my layers : [issue.zip](https://github.com/hslayers/hslayers-ng/files/4981238/issue.zip)

FYI, I disable the proxy by adding `proxyPrefix: ''` in the hslayersNgConfig function and by editing the package.json by :
`"start": "http-server -a localhost -p 8000 --cors",`

**Comment by raitisbe** [comment]
The fix will be available in 2.2.0 version today or tomorrow.
Thanks @Gmarquis45  for the tip. Does printing or map thumbnail work in sharing panel after you disabled the proxy?

**Comment by Gmarquis45** [comment]
When I disable the proxy (via the cors option), the layer adding by code works but not the legend (corb error in console).
It does not work adding external layer.
I will try today for printing and map thumbnail and I come back to you.
Thanks for your reactivity!

**Comment by raitisbe** [comment]
@Gmarquis45 we were also never really successful without a proxy, maybe just ins some isolated cases like you said. Btw version 2.2.0 is published, which fixes this issue.

**Comment by jmacura** [comment]
> FYI, I disable the proxy by adding `proxyPrefix: ''` in the hslayersNgConfig function and by editing the package.json by :
> `"start": "http-server -a localhost -p 8000 --cors",`

Hi @Gmarquis45 ! Have you also set `useProxy: false` in the config? `proxyPrefix: ''` might not be enough.

**Comment by Gmarquis45** [comment]
Hi @jmacura, no I don't use this option, I will try it. Thanks!
