### ISSUE TITLE
first drawn feature disappears

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#844]
Steps to reproduce:
* run the full example
* open drawing **toolbar**
* add new drawing layer
* draw first feature
* draw second feature

What happens:
* first feature disappears

What should happen:
* should not disappear

_Originally posted by @jmacura in https://github.com/hslayers/hslayers-ng/pull/834#issuecomment-664249183_

**Comment by raitisbe** [comment]
I have no explanation why it works, but it does. Seems again to be some context magic

**Comment by jmacura** [comment]
Sadly, I have to report that #846 does not resolve this issue. It keeps happening still, but under more tricky circumstances perhaps. I can't find a pattern which triggers it, but play with the drawing for a while. It happens in the end.

**Comment by jmacura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release 2.2.0](https://trello.com/c/WjVYw3Tb/91-release-220)

**Comment by raitisbe** [comment]
> Sadly, I have to report that #846 does not resolve this issue. It keeps happening still, but under more tricky circumstances perhaps. I can't find a pattern which triggers it, but play with the drawing for a while. It happens in the end.

What happens when the feature disappears and you use the styler to set the styling for the layer? For me all lost features appeared.

**Comment by jmacura** [comment]
> What happens when the feature disappears and you use the styler to set the styling for the layer? For me all lost features appeared.

I only keep revealing more and more bugs... :-(

**Comment by jmacura** [comment]
> 
> What happens when the feature disappears and you use the styler to set the styling for the layer? For me all lost features appeared.

Finally I agree. The restyling of all features in the layer makes the hidden features appear.

**Comment by raitisbe** [comment]
It works when this: ![image](https://user-images.githubusercontent.com/395514/88601140-b0dabe80-d078-11ea-89c9-a29e2200d289.png)

**Comment by raitisbe** [comment]
Actually the overriding of geometry for cluster layer style happens here https://github.com/hslayers/hslayers-ng/blob/develop/components/layermanager/layer-editor-vector-layer.service.ts#L106
