### ISSUE TITLE
No default option for styling

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#854]
When styling is set for "Fill" and "Line", but not for "Point", it behaves like "None" is set for points.

![image](https://user-images.githubusercontent.com/5598693/88593509-f048e100-d05f-11ea-9d2d-24aa2cecc00f.png)

![image](https://user-images.githubusercontent.com/5598693/88593489-e626e280-d05f-11ea-891f-c901d5d0bf62.png)

![image](https://user-images.githubusercontent.com/5598693/88593596-179fae00-d060-11ea-838f-574a59396825.png)

**Comment by DailisLangovskis** [comment]
My PR didn't resolve this error, will do it correctly now
