### ISSUE TITLE
Nonsense text in WMS layer settings

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#859]
"Scaleto 1:" should probably be "Min scale 1:123" (Or "Max scale 1:123"?)
![image](https://user-images.githubusercontent.com/5598693/88674373-056a5200-d0ea-11ea-9341-d8872c311be9.png)

Analogically here:
![image](https://user-images.githubusercontent.com/5598693/88674736-76aa0500-d0ea-11ea-806b-015a3eec457e.png)

**Comment by jmacura** [comment]
Not a critical issue, can be fixed in 2.3.0, no need to postpone 2.2.0 any longer.

**Comment by raitisbe** [comment]
Now will be 
![image](https://user-images.githubusercontent.com/395514/88904700-11772080-d25e-11ea-99eb-f1c05637534d.png)
