### ISSUE TITLE
Add custom panel in HSL application

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#903]
This was previously done via
```
        const el = angular.element(
          '<pra-adjuster></pra-adjuster>'
        )[0];
        HsLayoutService.panelListElement.appendChild(el);
        $compile(el)($scope);
```
and
```
        const toolbarButton = angular.element(
          '<pra-adjuster-sidebar-btn></pra-adjuster-sidebar-btn>'
        )[0];
        HsLayoutService.sidebarListElement.appendChild(toolbarButton);
        $compile(toolbarButton)(event.targetScope);
```
of which neither `angular.element()`, neither `$compile()` are available in Ng9.

So we have to provide a way to dynamically append components on our side.

**Comment by FilipLeitner** [comment]
For now it should be possible to add **sidebar menu-item** by pushing into HsSidebarService.buttons array from inside of MainController in app-js.ts
```
      HsSidebarService.buttons.push({
        panel: 'predictor',
        module: 'hs.predictor',
        order: 3,
        title: 'Sentinel predictor',
        description: 'Schedule job',
        icon: 'icon-time'
      });
```

**Comment by jmacura** [comment]
@FilipLeitner I have tried that and also `HsSidebarService.extraButtons.push()` but none of it works for me...

**Comment by raitisbe** [comment]
> by



> For now it should be possible to add **sidebar menu-item** by pushing into HsSidebarService.buttons array from inside of MainController in app-js.ts
> 
> ```
>       HsSidebarService.buttons.push({
>         panel: 'predictor',
>         module: 'hs.predictor',
>         order: 3,
>         title: 'Sentinel predictor',
>         description: 'Schedule job',
>         icon: 'icon-time'
>       });
> ```

But thats only for the menu button, not the panel itself right?

**Comment by jmacura** [comment]
> 
> 
> > For now it should be possible to add **sidebar menu-item** by pushing into HsSidebarService.buttons array from inside of MainController in app-js.ts

> 
> But thats only for the menu button, not the panel itself right?

Yes, that's why Filip has emphasized it and why I have changed the subject of this issue 😉 The panel still has to be compiled.
