### ISSUE TITLE
SPOI some problem with Search

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#92]
I didnt succed to find for example Jinočany, but also not Jinocany. Seesm that there is now some problem with search

**Comment by raitisbe** [comment]
The webservice doesnt return anything http://portal.sdi4apps.eu/openapi/search?q=Jinocany&_=1487846588288 so must be server side, or Im missing some parameter? What service is it, whos developing it?

**Comment by kcharvat** [comment]
I dont know ask Stepan, but I am not sure

**Comment by bvj** [comment]
This service was developed Runar.
