### ISSUE TITLE
'angular-material-bottom-sheet-collapsible' Module not found

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#937]
![image](https://user-images.githubusercontent.com/5598693/90753584-1406ec00-e2d9-11ea-8497-fdd3035c4db7.png)

Do you encounter this as well?
It happens to me with the latest develop version.

**Comment by jmacura** [comment]
Very curious.  When I run `npm i` more times in a row, then it installs some more packages on the second/third run 😵

**Comment by raitisbe** [comment]
Yes i had this too. Package got installed in
node_modules/hslayers-ng/node_modules. The only way how i could get around
it was install hslayers through git url instead of npm registry.
https://github.com/hslayers/project-rostenice/blob/upgrade-hslayers-2/package.json#L26
