### ISSUE TITLE
SPOI SPOI are not displayed in IE

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#95]
In Chrome and FF is working, but not in IE

**Comment by bvj** [comment]
In MSIE 11 is it working, but getting
_Uncaught ReferenceError: fc709aa7583177282b2d5271e66ec2dfd26f807c2 is not defined_ in Chrome
and
_SCRIPT5009: Object fc709aa7583177282b2d5271e66ec2dfd26f807c2 not defined._ in MSIE

**Comment by kcharvat** [comment]
I tried again and it is till now not working. Please check it

**Comment by raitisbe** [comment]
forgot to update openlayers also on server. Was still running on 3.11.2
