### ISSUE TITLE
SPOI Editing is not working

### ISSUE THREAD

**Issue by kcharvat** [hslayers/hslayers-ng#96]
Please check it

**Comment by raitisbe** [comment]
Was working for me for some random point. Which browser, layer and property?

**Comment by raitisbe** [comment]
Ah yes, in IE selecting doesnt work

**Comment by kcharvat** [comment]
Please check all time aslo IE. It is till now used by many people

**Comment by kcharvat** [comment]
I tried again now also in Chrome and I didnt succed

**Comment by raitisbe** [comment]
What are you doing exactly? I found that selecting features in IE doesnt work because of some bug in openlayers and in newer version which requires some changes to hsl code, other svg feature icons dont work which im now trying to overcome somehow.

**Comment by raitisbe** [comment]
Confirmed. Editing doesnt work.

**Comment by raitisbe** [comment]
To enable editing had to rewrite spoi example since Jan was refactoring query module. Unfortunately to solve IE bugs, OpenLayers needs to be upgraded from 3.11 to 3.21 but then we can upgrade to 4.0.1 altogether because its the next version since 3.21. Marek are you ready?
