### ISSUE TITLE
Map becomes grainy

### ISSUE THREAD

**Issue by raitisbe** [hslayers/hslayers-ng#972]
When map is panned after a small delay it becomes grainy. Since its delayed I suspect it might be connected to the thumbnail generation in save-map or share module. 
![image](https://user-images.githubusercontent.com/395514/91275999-2f627300-e781-11ea-86f0-0a6c55db3f16.png)
Tested on windows, chrome, nothing special about dpi of display.

**Comment by jmacura** [comment]
You are right. I observe this as well.
Can't it be connected to the layout changes #940 ?

**Comment by FilipLeitner** [comment]
Possibly yes, gonna check it out

**Comment by FilipLeitner** [comment]
I am not sure I am able to reproduce the issue. Also not sure if it can be caused by changes in layout. I suspect that if it is beacause of wrong viewport size it could be solved by calling updateSize(), which  doesnt seem to be the thing

**Comment by jmacura** [comment]
To be clear, the map is somewhat blurred on certain levels, but can't say how large is the difference from previous versions.
![image](https://user-images.githubusercontent.com/5598693/91897707-fa7f8000-ec9a-11ea-91e7-14c9b49282de.png)

**Comment by raitisbe** [comment]
Yes its hard to reproduce. Maybe even got fixed with the layout rewrite, so lets leave it for now.

**Comment by FilipLeitner** [comment]
Can still be observed and its caused by this function call: https://github.com/hslayers/hslayers-ng/blob/develop/components/permalink/share-url.service.ts#L99.

**Comment by jmacura** [comment]
How did you find out @FilipLeitner ? 😮

**Comment by FilipLeitner** [comment]
Was rewriting map module and it suddently started to happen all the tíme, quite obvioisly at the same tíme url gets rewriten. So I just hunt it down.
Dont know how its connected but by commenting out the section the Bug dissaperas

**Comment by FilipLeitner** [comment]
Seems to be fixed by 97f5f8b62df83c750b193fc4694069a8316a9e49
